### ISSUE TITLE
`conda build` issue on windows with python 3.5

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#1013]
Tried to build windows packages (anaconda3 with python 3.5 and setuptools 21) using the build matrix script but got:
```
[Anaconda3] C:\Users\Emiri\Anaconda3\zipline-master>python etc\conda_build_matrix.py
build failure: python=2.7 numpy=1.9
Error: bad character '=' in package name dependency 'pip>=7.1.0'
```

Replacing all `>=` with ` >=` (adding a space in the front) in requirements.txt solved the issue. Then, I got:

```
Traceback (most recent call last):
 File "C:\Users\Emiri\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
   sys.exit(main())
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\main_build.py", line 192, in main
   args_func(args, p)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\main_build.py", line 486, in args_func
   args.func(args, p)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\main_build.py", line 367, in execute
   m = MetaData(recipe_dir)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\metadata.py", line 340, in __init__
   self.parse_again(permit_undefined_jinja=True)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\metadata.py", line 351, in parse_again
   self.meta = parse(self._get_contents(permit_undefined_jinja))
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\metadata.py", line 620, in _get_contents
   return template.render(environment=env)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\jinja2\environment.py", line 989, in render
   return self.environment.handle_exception(exc_info, True)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
   reraise(exc_type, exc_value, tb)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
   raise value.with_traceback(tb)
 File "C:\Users\Emiri\Anaconda3\zipline-master\conda\zipline\meta.yaml", line 1, in top-level template code
   {% set data = load_setuptools() %}
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\jinja_context.py", line 46, in load_setuptools
   exec(code, ns, ns)
 File "setup.py", line 239, in <module>
   conda_format=conda_build,
 File "setup.py", line 229, in module_requirements
   "No requirements found for %s." % module_names - found
TypeError: unsupported operand type(s) for -: 'str' and 'set'
```

**Comment by richafrank** [comment]
@twiecki Would you try out my branch named [conda_win] (https://github.com/quantopian/zipline/tree/conda_win)?

**Comment by twiecki** [comment]
Probably only next week.

**Comment by twiecki** [comment]
```Emiri Wiecki (emiriyamaguchi@gmail.com, emiri.yamaguchi@gmail.com)
[Anaconda3] C:\Users\Emiri\Anaconda3\zipline-conda_win>python conda_build_matrix.py
python: can't open file 'conda_build_matrix.py': [Errno 2] No such file or directory

[Anaconda3] C:\Users\Emiri\Anaconda3\zipline-conda_win>python etc\conda_build_matrix.py
build failure: python=2.7 numpy=1.9
fatal: repository '../../' does not exist
Using Anaconda Cloud api site https://api.anaconda.org
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

   https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
 File "C:\Users\Emiri\Anaconda3\Scripts\conda-build-script.py", line 4, in <module>
   sys.exit(main())
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\main_build.py", line 192, in main
   args_func(args, p)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\main_build.py", line 486, in args_func
   args.func(args, p)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\main_build.py", line 409, in execute
   include_recipe=args.include_recipe)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\build.py", line 411, in build
   source.provide(m.path, m.get_section('source'))
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\source.py", line 279, in provide
   git_source(meta, recipe_dir)
 File "C:\Users\Emiri\Anaconda3\lib\site-packages\conda_build\source.py", line 121, in git_source
   check_call(args + [git_url, cache_repo_arg],  cwd=recipe_dir)
 File "C:\Users\Emiri\Anaconda3\lib\subprocess.py", line 584, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Emiri\\Anaconda3\\Library\\bin\\git.exe', 'clone', '--mirror', '../../', 'C:/Users/Emiri/Anaconda3/conda-bld/git_cache/Users_Emiri_Anaconda3_zipline-conda_win']' returned non-zero exit status 128```

**Comment by richafrank** [comment]
Now that we're building conda packages on appveyor, I'm going to close this.  Let me know if you think otherwise @twiecki .
