### ISSUE TITLE
Cannot unit test Pipeline against a "data bundle"

### ISSUE THREAD

**Issue by fredfortier** [quantopian/zipline#1239]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Mac OS 10.11
* Python Version:  Python 2.7.11
* Python Bitness: 64
* How did you install Zipline: pip git+https://github.com/quantopian/zipline
* Python packages:
alabaster==0.7.8
appnope==0.1.0
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcolz==0.12.1
bokeh==0.11.1
Bottleneck==1.0.0
cachetools==1.1.5
certifi==2016.2.28
click==4.0
configparser==3.3.0.post2
contextlib2==0.4.0
cycler==0.10.0
cyordereddict==0.2.2
Cython==0.22.1
decorator==4.0.0
docutils==0.12
entrypoints==0.2.1
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.0.5
gevent==1.1.1
gnureadline==6.3.3
greenlet==0.4.9
imagesize==0.7.1
intervaltree==2.1.0
ipykernel==4.3.1
ipyparallel==5.0.1
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==5.1.3
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
Logbook==0.12.5
MarkupSafe==0.23
matplotlib==1.5.1+1866.g4e1792b
mercurial==3.8.1
mistune==0.7.2
mock==2.0.0
multipledispatch==0.4.8
nbconvert==4.2.0
nbformat==4.0.1
networkx==1.9.1
nose==1.3.7
notebook==4.2.0
numexpr==2.4.6
numpy==1.11.0
pandas==0.17.1
pandas-datareader==0.2.1
path.py==8.2.1
pathlib2==2.1.0
patsy==0.4.0
pbr==1.9.1
pexpect==4.0.1
pickleshare==0.7.2
ptyprocess==0.5.1
pyclip==0.1
pyfolio==0.5.0
Pygments==2.1.3
pykalman==0.9.5
pymc==2.3.6
pyparsing==2.1.3
python-dateutil==2.4.2
pytz==2015.4
PyYAML==3.11
pyzmq==15.2.0
qtconsole==4.2.1
requests==2.9.1
requests-file==1.4
scikit-learn==0.18.dev0
scipy==0.18.0.dev0+e1fbfab
seaborn==0.7.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sortedcontainers==1.4.4
Sphinx==1.4.1
SQLAlchemy==1.0.8
statsmodels==0.6.1
terminado==0.6
testpath==0.3
Theano==0.9.0.dev1
toolz==0.7.4
tornado==4.3
traitlets==4.2.1
vboxapi==1.0
widgetsnbextension==1.2.2
zipline==1.0.0+41.g3ffe9a0

Now that you know a little about me, let me tell you about the issue I am
having:

I am able to run an algorithm with a Pipeline against a Data Bundle (hopefully I am expressing this correctly). My problem starts when I attempt more granular unit tests.

Specifically, I am trying to run a Pipeline in a unit test outside of the algorithm. Reading the source the code, I found an "engine_from_files" method which intuitively seems to do what I want. My code looks like this:
```python
log.debug('testing the Momentum factor in pipeline...')
path = '/Users/fredfortier/.zipline/data/quantopian-quandl/2016-05-26T18;48;21.408210'
pipe = Pipeline()

dates = date_range(
    Timestamp('2016-01-01', tz='utc'),
    Timestamp('2016-05-22', tz='utc'),
    freq='D',
    tz='UTC',
)

engine = engine_from_files(daily_bar_path=path + '/daily_equities.bcolz',
                           adjustments_path=path + '/adjustments.sqlite',
                           asset_db_path=path + '/assets-3.sqlite',
                           calendar=dates,
                           warmup_assets=True)
engine.run_pipeline(pipe, dates[0], dates[-1])
```
It fails with this stack trace:
```
Error
Traceback (most recent call last):
  File "tests/pipeline.py", line 55, in test_momentum_factor
    warmup_assets=True)
  File "/usr/local/lib/python2.7/site-packages/zipline/pipeline/__init__.py", line 41, in engine_from_files
    asset_finder = AssetFinder(asset_db_path)
  File "/usr/local/lib/python2.7/site-packages/zipline/assets/assets.py", line 109, in __init__
    metadata.reflect(only=asset_db_table_names)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3594, in reflect
    with bind.connect() as conn:
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2018, in connect
    return self._connection_cls(self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 72, in __init__
    if connection is not None else engine.raw_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2104, in raw_connection
    self.pool.unique_connection, _connection)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 318, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (sqlite3.OperationalError) unable to open database file
```
Sincerely,
Frederic

**Comment by ssanderson** [comment]
@fredfortier this looks like sqlite is failing trying to open the database file.  Are you sure the path you're passing is the correct location?  What happens if you do `sqlite3 '/path/to/assets.db'`?

**Comment by llllllllll** [comment]
This is most likely related to the windows issue with data bundles: https://github.com/quantopian/zipline/pull/1282

**Comment by llllllllll** [comment]
Sorry, bad pattern matching on my part.

**Comment by llllllllll** [comment]
There is also a `zipline.data.bundles.load` function which should give you the loaders that you need instead of digging into the storage format of the bundle manually with `from_files`.

http://www.zipline.io/appendix.html#zipline.data.bundles.load

**Comment by ssanderson** [comment]
@llllllllll an `engine_from_bundle` function might be nice as a convenience for the use-case of running pipelines using bundle data?
