### ISSUE TITLE
Errors when fetching some stocks using Yahoo Finance

### ISSUE THREAD

**Issue by fredfortier** [quantopian/zipline#1241]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment
- Operating System: OS X 10.11
- Python Version: Python 2.7.11
- Python Bitness: 64
- How did you install Zipline: pip
- Python packages: 

```
alabaster==0.7.8
appnope==0.1.0
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
bcolz==0.12.1
blaze==0.10.1
bokeh==0.11.1
Bottleneck==1.0.0
cachetools==1.1.5
certifi==2016.2.28
click==4.0
configparser==3.3.0.post2
contextlib2==0.4.0
cycler==0.10.0
cyordereddict==0.2.2
Cython==0.22.1
datashape==0.5.2
decorator==4.0.0
docutils==0.12
entrypoints==0.2.1
Flask==0.11
Flask-Cors==2.1.2
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.0.5
gevent==1.1.1
gnureadline==6.3.3
greenlet==0.4.9
imagesize==0.7.1
intervaltree==2.1.0
ipykernel==4.3.1
ipyparallel==5.0.1
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==5.1.3
itsdangerous==0.24
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
Logbook==0.12.5
MarkupSafe==0.23
matplotlib==1.5.1+1866.g4e1792b
mercurial==3.8.1
mistune==0.7.2
mock==2.0.0
multipledispatch==0.4.8
nbconvert==4.2.0
nbformat==4.0.1
networkx==1.9.1
nose==1.3.7
notebook==4.2.0
numexpr==2.4.6
numpy==1.11.0
odo==0.5.0
pandas==0.17.1
pandas-datareader==0.2.1
path.py==8.2.1
pathlib2==2.1.0
patsy==0.4.0
pbr==1.9.1
pexpect==4.0.1
pickleshare==0.7.2
psutil==4.2.0
ptyprocess==0.5.1
pyclip==0.1
pyfolio==0.5.0
Pygments==2.1.3
pykalman==0.9.5
pymc==2.3.6
pymongo==3.2.2
pyparsing==2.1.3
python-dateutil==2.4.2
pytz==2015.4
PyYAML==3.11
pyzmq==15.2.0
qtconsole==4.2.1
requests==2.9.1
requests-file==1.4
scikit-learn==0.18.dev0
scipy==0.18.0.dev0+e1fbfab
seaborn==0.7.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sortedcontainers==1.4.4
Sphinx==1.4.1
SQLAlchemy==1.0.8
statsmodels==0.6.1
stringcase==1.0.6
terminado==0.6
testpath==0.3
Theano==0.9.0.dev1
toolz==0.7.4
tornado==4.3
traitlets==4.2.1
vboxapi==1.0
Werkzeug==0.11.10
widgetsnbextension==1.2.2
zipline==1.0.1+2.g85327d8
```

Now that you know a little about me, let me tell you about the issue I am
having:

I am using a Yahoo Finance bundle to fetch an array of stock symbols. All seem to go well except for a few odd stocks which result in an application error.

I was able to locate the problematic symbols by lowering my sample size until I could match the error to a specific index. I eliminated most errors by filtering out securities with zero market cap. However, a small subset of securities like "APHB", for which I cannot discern a systematic problem, continue to error out.

I believe that the issue is two fold,
1. A small percentage of securities, without an obvious common denominator, cause the system to throw a nondescript (insofar as it does not reveal the culprit) error
2. When ingesting an array of symbols, there is no option to continue continue after those errors

For me personally, point 2 is a more important problem.

I have registered my bundle in extension.py following these instructions: http://www.zipline.io/bundles.html#yahoo-bundle-factories

I invoke this command:

```
zipline ingest -b health-care-bundle
```

And get this output:

```
Downloading Yahoo pricing data:   [###########################---------]   75%  00:00:32

Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 9, in <module>
    load_entry_point('zipline==1.0.1+2.g85327d8', 'console_scripts', 'zipline')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zipline/__main__.py", line 300, in ingest
    show_progress,
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 375, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/yahoo.py", line 122, in ingest
    daily_bar_writer.write(_pricing_iter(), show_progress=True)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 252, in write
    return self._write_internal(it, assets)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 312, in _write_internal
    for asset_id, table in iterator:
  File "/usr/local/lib/python2.7/site-packages/click/_termui_impl.py", line 240, in next
    rv = next(self.iter)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 245, in <genexpr>
    ((sid, to_ctable(df, invalid_data_behavior)) for sid, df in data),
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/yahoo.py", line 98, in _pricing_iter
    session=session,
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/data.py", line 94, in DataReader
    session=session).read()
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/yahoo/daily.py", line 77, in read
    df = super(YahooDailyReader, self).read()
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 173, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 80, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 91, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 117, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv
```

In this particular example, I was able to determine that the failure occurs with security: "APHB".

Here is what happens when slicing my array of symbols to include only the problematic security:

```
Downloading Yahoo pricing data:   [####################################]  100%

Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 9, in <module>
    load_entry_point('zipline==1.0.1+2.g85327d8', 'console_scripts', 'zipline')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zipline/__main__.py", line 300, in ingest
    show_progress,
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 375, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/yahoo.py", line 122, in ingest
    daily_bar_writer.write(_pricing_iter(), show_progress=True)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 252, in write
    return self._write_internal(it, assets)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 312, in _write_internal
    for asset_id, table in iterator:
  File "/usr/local/lib/python2.7/site-packages/click/_termui_impl.py", line 240, in next
    rv = next(self.iter)
  File "/usr/local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 245, in <genexpr>
    ((sid, to_ctable(df, invalid_data_behavior)) for sid, df in data),
  File "/usr/local/lib/python2.7/site-packages/zipline/data/bundles/yahoo.py", line 98, in _pricing_iter
    session=session,
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/data.py", line 94, in DataReader
    session=session).read()
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/yahoo/daily.py", line 77, in read
    df = super(YahooDailyReader, self).read()
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 173, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 80, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 91, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/local/lib/python2.7/site-packages/pandas_datareader/base.py", line 117, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv
```

**Comment by paulperry** [comment]
Zipline should at least catch the pandas_datareader exception for the stock and provide a better error message .  It's a real pain to narrow down which stock is causing the problem.

**Comment by ssanderson** [comment]
> Zipline should at least catch the pandas_datareader exception for the stock and provide a better error message . It's a real pain to narrow down which stock is causing the problem.

I definitely agree with this.  

> 1. A small percentage of securities, without an obvious common denominator, cause the system to throw a nondescript (insofar as it does not reveal the culprit) error
2. When ingesting an array of symbols, there is no option to continue continue after those errors

For point 1, I tried making some raw API requests to yahoo on the APHB, and they just don't seem to have data for that stock available.  I don't think there's much that Zipline could do to make this work other than throwing a more informative error.

For point 2, I'm a little wary of adding an option to ignore failures.  Bundles are composed of a several different resources (pricing data, adjustments, asset masters), and if one of those datasets has entries for an asset when the others don't, it's liable to create many subtle bugs.  The main use-case I see would be to run the full bundle so that you can see all the failures at once and then manually remove them, but I would still consider that a failed load at the end of the run.  Maybe what we want is a `--fail-fast/--fail-slow` option that determines whether we abort immediately after a stock fails?

Also, @fredfortier this is a great bug report!  Sorry it's taken so long for us to get back to you.

**Comment by femtotrader** [comment]
I think we (on pandas-reader side) should provide a more explicit message with URL parameters
so user will be aware of which stock is causing problem.
So I've just open an issue on our side https://github.com/pydata/pandas-datareader/issues/216

**Comment by FreddieV4** [comment]
Hmm interesting that we had seen this issue this long ago as well.

x-ref #1812 #1776

**Comment by FreddieV4** [comment]
Hi there. This should be fixed in the latest release :). Going to close this. Feel free to reopen if you see this issue again. 

Check out the release notes on zipline.io for more info
