### ISSUE TITLE
zipline module fails to load

### ISSUE THREAD

**Issue by jdgd1** [quantopian/zipline#1284]
Clean install of Anaconda Python (64bit) w/ python 3.4 on Windows. Zipline 1.0.1 installed successfully via conda. However when I try to a simple "from zipline.api import history" I get the following error:

`Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pandas\__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas\src\numpy.pxd", line 157, in init pandas.hashtable (pandas\hashtable.c:38262)
  File "C:\Anaconda3\lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.`

Any idea what I need to do to get zipline working?

**Comment by jdgd1** [comment]
As an update I downgraded numpy to version 1.10.1 (from 1.11) and now get this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\zipline\__init__.py", line 23, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Anaconda3\lib\site-packages\zipline\utils\run_algo.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "C:\Anaconda3\lib\site-packages\zipline\algorithm.py", line 84, in <module>
    from zipline.pipeline.engine import (
  File "C:\Anaconda3\lib\site-packages\zipline\pipeline\__init__.py", line 4, in <module>
    from .classifiers import Classifier, CustomClassifier
  File "C:\Anaconda3\lib\site-packages\zipline\pipeline\classifiers\__init__.py", line 1, in <module>
    from .classifier import (
  File "C:\Anaconda3\lib\site-packages\zipline\pipeline\classifiers\classifier.py", line 22, in <module>
    from ..filters import ArrayPredicate, NullFilter, NumExprFilter
  File "C:\Anaconda3\lib\site-packages\zipline\pipeline\filters\__init__.py", line 1, in <module>
    from .filter import (
  File "C:\Anaconda3\lib\site-packages\zipline\pipeline\filters\filter.py", line 19, in <module>
    from zipline.lib.rank import is_missing
  File "zipline\lib\rank.pyx", line 18, in init zipline.lib.rank (zipline/lib\rank.c:4695)
  File "C:\Anaconda3\lib\site-packages\scipy\stats\__init__.py", line 338, in <module>
    from .stats import *
  File "C:\Anaconda3\lib\site-packages\scipy\stats\stats.py", line 180, in <module>
    import scipy.special as special
  File "C:\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 627, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.`

However, scipy loads on it's own. Any ideas how to get this working?
