### ISSUE TITLE
Issue with  "zipline ingest -b quandl"

### ISSUE THREAD

**Issue by pamiro** [quantopian/zipline#1295]
Hello,
I am not able to download **quandl** data bundle (although I have no issue with **quantopian-quandl**). I wonder if anybody else is facing similar issue?
## My environment
- Operating System: Linux x86_64 or OSX
- Python Version: anaconda python 3.4
- Python Bitness: 64
- How did you install Zipline:  pip
- Python packages: 
  ....
  zipline   1.0.1      <pip>
  ....
## Reproduction Steps
1. Register on Quandl, grab QUANDL_API_KEY
2. QUANDL_API_KEY=<<key>> zipline ingest -b quandl

this fails with exception ::

Merging daily equity files:  [-----------------------------------#]  2076[2016-06-21 15:43:32.588062] ERROR: zipline.data.bundles.quandl: Exception raised reading Quandl data. Retrying.
Traceback (most recent call last):
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/utils/cache.py", line 225, in **getitem**
    with open(self._keypath(key), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pmironchyk/.zipline/data/quandl/.cache/TEST123456789'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/bundles/quandl.py", line 242, in gen_symbol_data
    raw_data = cache[symbol]
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/utils/cache.py", line 230, in **getitem**
    raise KeyError(key)
KeyError: 'TEST123456789'

During handling of the above exception, another exception occurred:
.....
Traceback (most recent call last):
  File "/home/pmironchyk/anaconda3/envs/py34/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/__main__.py", line 300, in ingest
    show_progress,
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/bundles/core.py", line 375, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/bundles/quandl.py", line 301, in quandl_bundle
    show_progress=show_progress,
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/us_equity_pricing.py", line 252, in write
    return self._write_internal(it, assets)
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/us_equity_pricing.py", line 312, in _write_internal
    for asset_id, table in iterator:
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/click/_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/us_equity_pricing.py", line 245, in <genexpr>
    ((sid, to_ctable(df, invalid_data_behavior)) for sid, df in data),
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/bundles/quandl.py", line 250, in gen_symbol_data
    end_date=end_date,
  File "/home/pmironchyk/anaconda3/envs/py34/lib/python3.4/site-packages/zipline/data/bundles/quandl.py", line 204, in fetch_single_equity
    symbol, retries
ValueError: Failed to download data for 'TEST123456789' after 5 attempts.

Sincerely,
Pavel Mironchyk

**Comment by westonplatter** [comment]
@pamiro are you still having this issue?

**Comment by quocgfy** [comment]
I can't get QUANDL data either. So we're stuck with quantopian data, which doesn't work ( SEE - float is required error). GREAT

**Comment by FreddieV4** [comment]
@quocgfy are you getting the exact same error? with the same version of zipline?

**Comment by freddiev4** [comment]
This should be fixed on master 🙂

**Comment by freddiev4** [comment]
Going to close this as it is fixed in the latest release. Feel free to check out the release announcement [here](https://groups.google.com/forum/#!topic/zipline/p0LwaEBUJ9s).
