### ISSUE TITLE
AttributeError: 'module' object has no attribute 'client'

### ISSUE THREAD

**Issue by yuanhuanglin** [quantopian/zipline#1395]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
* Operating System: Linux ubuntu-new-install 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 3.4.5
* Python Bitness:  64
* How did you install Zipline: pip
* Python packages: 

> backports-abc==0.4
> bcolz==0.12.1
> Bottleneck==1.1.0
> cachetools==1.1.6
> click==6.6
> contextlib2==0.5.4
> cycler==0.10.0
> cyordereddict==1.0.0
> Cython==0.24.1
> decorator==4.0.10
> entrypoints==0.2.2
> intervaltree==2.1.0
> ipykernel==4.4.1
> ipython==5.1.0
> ipython-genutils==0.1.0
> Jinja2==2.8
> jsonschema==2.5.1
> jupyter-client==4.3.0
> jupyter-core==4.1.1
> Logbook==1.0.0
> lxml==3.6.1
> MarkupSafe==0.23
> matplotlib==1.5.1
> mistune==0.7.3
> multipledispatch==0.4.8
> nbconvert==4.2.0
> nbformat==4.1.0
> networkx==1.11
> notebook==4.2.2
> numexpr==2.6.1
> numpy==1.11.1
> pandas==0.18.1
> pandas-datareader==0.2.1
> patsy==0.4.1
> pexpect==4.2.0
> pickleshare==0.7.4
> prompt-toolkit==1.0.6
> ptyprocess==0.5.1
> Pygments==2.1.3
> pyparsing==2.1.8
> python-dateutil==2.5.3
> pytz==2016.6.1
> pyzmq==15.4.0
> requests==2.11.0
> requests-file==1.4
> scipy==0.18.0
> simplegeneric==0.8.1
> six==1.10.0
> sortedcontainers==1.5.3
> SQLAlchemy==1.0.14
> statsmodels==0.6.1
> TA-Lib==0.4.9
> terminado==0.6
> toolz==0.8.0
> tornado==4.4.1
> traitlets==4.2.2
> tushare==0.5.0
> wcwidth==0.1.7
> zipline==1.0.1

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
* What did you expect to happen?
I am testing the notebook tutorial(https://github.com/quantopian/zipline/blob/master/docs/notebooks/tutorial.ipynb).
* What happened instead?
But when I ran the command in jupyter notebook as below, I got the error message instead.
`!python /usr/local/lib/python3.4/site-packages/zipline/utils/run_algo.py --help`

Full error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pandas/compat/__init__.py", line 46, in <module>
    import __builtin__ as builtins
ImportError: No module named '__builtin__'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/zipline/utils/run_algo.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "/usr/local/lib/python3.4/site-packages/zipline/__init__.py", line 19, in <module>
    from . import data
  File "/usr/local/lib/python3.4/site-packages/zipline/data/__init__.py", line 1, in <module>
    from . import loader
  File "/usr/local/lib/python3.4/site-packages/zipline/data/loader.py", line 18, in <module>
    import logbook
  File "/usr/local/lib/python3.4/site-packages/logbook/__init__.py", line 14, in <module>
    from .base import (
  File "/usr/local/lib/python3.4/site-packages/logbook/base.py", line 22, in <module>
    from logbook.helpers import (PY2, cached_property, integer_types, iteritems,
  File "/usr/local/lib/python3.4/site-packages/logbook/helpers.py", line 60, in <module>
    from http import client as http_client
  File "/usr/local/lib/python3.4/http/client.py", line 69, in <module>
    import email.parser
  File "/usr/local/lib/python3.4/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/local/lib/python3.4/email/feedparser.py", line 27, in <module>
    from email import message
  File "/usr/local/lib/python3.4/email/message.py", line 16, in <module>
    from email import utils
  File "/usr/local/lib/python3.4/email/utils.py", line 29, in <module>
    import socket
  File "/usr/local/lib/python3.4/socket.py", line 53, in <module>
    from enum import IntEnum
  File "/usr/local/lib/python3.4/site-packages/zipline/utils/enum.py", line 27, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.4/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python3.4/site-packages/pandas/compat/__init__.py", line 59, in <module>
    import http.client as httplib
AttributeError: 'module' object has no attribute 'client'
```

Here is how you can reproduce this issue on your machine:
## Reproduction Steps

1. Compiling python 3.4.5 from source and successfully installed pip.
2. Install jupyter notebook, and upgrade to 5.0.
3. Replace the run_algo.py path with my one.
4. Run.

## What steps have you taken to resolve this already?

1. I tried Pandas 0.17, the error message is the same. So I also tried the 0.18 version, nothing changed.
2. I tried two commands like below in Jupyter notebook, they worked!
`from http import client as http_client
import http.client as httplib
`
...

Sincerely,
`Yuan`

**Comment by richafrank** [comment]
Hi @yuanhuanglin !  Sorry for the trouble - looks like that doc uses the old command and no longer works.  From the command line, you can run `zipline run --help`, or in a jupyter notebook you can `import zipline` and then use the `%%zipline` cell magic.

**Comment by richafrank** [comment]
Regarding the AttributeError, as the package containing the entry point, the zipline/utils directory is added to your PYTHONPATH, and then zipline.utils.enum is shadowing python3's stdlib enum.  So then we're importing pandas again, which is partially initialized... and so on.

**Comment by richafrank** [comment]
I updated the docs in https://github.com/quantopian/zipline/pull/1409.  Let us know if the new command works for you.

**Comment by richafrank** [comment]
Haven't heard anything, so closing for now.
