### ISSUE TITLE
Calling `history` on daily data does not work in quantopian research environment

### ISSUE THREAD

**Issue by sketchytechky** [quantopian/zipline#1482]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
# Environment

In quantopian research environment - https://www.quantopian.com/research/

Now that you know a little about me, let me tell you about the issue I am
having:
# Description of Issue
- What did you expect to happen?

When running https://www.quantopian.com/research/notebooks/Tutorials%20and%20Documentation/9.%20Tutorial%20(Advanced)%20-%20Backtesting%20with%20Zipline.ipynb

Expect the notebook to run without error.
- What happened instead?

We got the following error stack trace:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-793de63940a0> in <module>()
     19 #perf_manual = algo_obj.run(data.transpose(2,1,0))
     20 
---> 21 perf_manual = algo_obj.run(data.transpose(2,1,0))

/build/src/qexec_repo/zipline_repo/zipline/algorithm.pyc in run(self, data, overwrite_sim_params)
    686         try:
    687             perfs = []
--> 688             for perf in self.get_generator():
    689                 perfs.append(perf)
    690 

/build/src/qexec_repo/zipline_repo/zipline/gens/tradesimulation.pyc in transform(self)
    217             for dt, action in self.clock:
    218                 if action == BAR:
--> 219                     for capital_change_packet in every_bar(dt):
    220                         yield capital_change_packet
    221                 elif action == SESSION_START:

/build/src/qexec_repo/zipline_repo/zipline/gens/tradesimulation.pyc in every_bar(dt_to_use, current_data, handle_data)
    130                     perf_tracker.process_commission(commission)
    131 
--> 132             handle_data(algo, current_data, dt_to_use)
    133 
    134             # grab any new orders from the blotter, then clear the list.

/build/src/qexec_repo/zipline_repo/zipline/utils/events.pyc in handle_data(self, context, data, dt)
    182                     context,
    183                     data,
--> 184                     dt,
    185                 )
    186 

/build/src/qexec_repo/zipline_repo/zipline/utils/events.pyc in handle_data(self, context, data, dt)
    201         """
    202         if self.rule.should_trigger(dt):
--> 203             self.callback(context, data)
    204 
    205 

/build/src/qexec_repo/zipline_repo/zipline/algorithm.pyc in handle_data(self, data)
    457     def handle_data(self, data):
    458         if self._handle_data:
--> 459             self._handle_data(self, data)
    460 
    461         # Unlike trading controls which remain constant unless placing an

<ipython-input-39-8ec833e89575> in handle_data(context, data)
     18     # history() has to be called with the same params
     19     # from above and returns a pandas dataframe.
---> 20     short_mavg = history(100, '1d', 'price').mean()
     21     long_mavg = history(300, '1d', 'price').mean()
     22 

/build/src/qexec_repo/zipline_repo/zipline/utils/api_support.pyc in wrapped(*args, **kwargs)
     49     def wrapped(*args, **kwargs):
     50         # Get the instance and call the method
---> 51         return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
     52     # Add functor to zipline.api
     53     setattr(zipline.api, f.__name__, wrapped)

/build/src/qexec_repo/zipline_repo/zipline/utils/api_support.pyc in wrapped_method(self, *args, **kwargs)
     96             if not self.initialized:
     97                 raise exception
---> 98             return method(self, *args, **kwargs)
     99         return wrapped_method
    100     return decorator

/build/src/qexec_repo/zipline_repo/zipline/algorithm.pyc in history(self, bar_count, frequency, field, ffill)
   2033             self._calculate_universe(),
   2034             field,
-> 2035             ffill
   2036         )
   2037 

/build/src/qexec_repo/zipline_repo/zipline/algorithm.pyc in get_history_window(self, bar_count, frequency, assets, field, ffill)
   2044                 frequency,
   2045                 field,
-> 2046                 ffill,
   2047             )
   2048         else:

/build/src/qexec_repo/zipline_repo/zipline/data/data_portal.pyc in get_history_window(self, assets, end_dt, bar_count, frequency, field, ffill)
    710             if field == "price":
    711                 df = self._get_history_daily_window(assets, end_dt, bar_count,
--> 712                                                     "close")
    713             else:
    714                 df = self._get_history_daily_window(assets, end_dt, bar_count,

/build/src/qexec_repo/zipline_repo/zipline/data/data_portal.pyc in _get_history_daily_window(self, assets, end_dt, bar_count, field_to_use)
    582 
    583         data = self._get_history_daily_window_data(
--> 584             assets, days_for_window, end_dt, field_to_use
    585         )
    586         return pd.DataFrame(

/build/src/qexec_repo/zipline_repo/zipline/data/data_portal.pyc in _get_history_daily_window_data(self, assets, days_for_window, end_dt, field_to_use)
    624             elif field_to_use == 'close':
    625                 minute_value = self._daily_aggregator.closes(
--> 626                     assets, end_dt)
    627             elif field_to_use == 'volume':
    628                 minute_value = self._daily_aggregator.volumes(

/build/src/qexec_repo/zipline_repo/zipline/data/resample.pyc in closes(self, assets, dt)
    381                         continue
    382                 except KeyError:
--> 383                     val = self._minute_reader.get_value(
    384                         asset, dt, 'close')
    385                     if pd.isnull(val):

AttributeError: 'NoneType' object has no attribute 'get_value'
```
## Reproduction Steps
1. Run example notebook at https://www.quantopian.com/research/notebooks/Tutorials%20and%20Documentation/9.%20Tutorial%20(Advanced)%20-%20Backtesting%20with%20Zipline.ipynb, expect the notebook to run.

...
## What steps have you taken to resolve this already?

I have a brief investigation, and it seems like related to 

```
    short_mavg = history(100, '1d', 'price').mean()
```

That when the `handle_date` method is run at non-midnight, https://github.com/quantopian/zipline/blob/bf4079dcebbd19f3e3d5403d342cc4a4686ddfe4/zipline/data/data_portal.py#L656  causes it to try to use the code path in `minute_mode`.

...
# Anything else?

If we use `minute` data, this would work (but quiet slow/impossible) to look back at the 300 days moving average as the example intended.
...

Sincerely,
boris

**Comment by hamannj** [comment]
I have tried using the example in the docs about using the history()/add_history() functions. I have been using zipline 1.0.2 and don't know enough about the environment to know if it's a bug or there's something I am not doing correctly. I saw that the add_history() function has been deprecated, but the history() call returns:
Traceback (most recent call last):
  File "/home/jeff/anaconda2/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.0.2', 'console_scripts', 'zipline')()
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/__main__.py", line 240, in run
    environ=os.environ,
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 180, in _run
    overwrite_sim_params=False,
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/algorithm.py", line 688, in run
    for perf in self.get_generator():
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/gens/tradesimulation.py", line 220, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/gens/tradesimulation.py", line 133, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/utils/events.py", line 184, in handle_data
    dt,
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/utils/events.py", line 203, in handle_data
    self.callback(context, data)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/algorithm.py", line 459, in handle_data
    self._handle_data(self, data)
  File "algos/8c0d71b6-8698-11e6-b87e-3b70015c2f14.py", line 23, in handle_data
    hist = history(21,'1d','close')
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/utils/api_support.py", line 51, in wrapped
    return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/utils/api_support.py", line 98, in wrapped_method
    return method(self, *args, **kwargs)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/algorithm.py", line 2065, in history
    ffill
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/algorithm.py", line 2076, in get_history_window
    ffill,
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/data_portal.py", line 777, in get_history_window
    field)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/data_portal.py", line 646, in _get_history_daily_window
    assets, days_for_window, end_dt, field_to_use
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/data_portal.py", line 688, in _get_history_daily_window_data
    assets, end_dt)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/resample.py", line 385, in closes
    asset, dt, 'close')
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/dispatch_bar_reader.py", line 84, in get_value
    return r.get_value(sid, dt, field)
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 1068, in get_value
    value = self._open_minute_file(field, sid)[minute_pos]
  File "/home/jeff/anaconda2/lib/python2.7/site-packages/zipline/data/minute_bars.py", line 1015, in _open_minute_file
    mode='r')
  File "bcolz/carray_ext.pyx", line 1026, in bcolz.carray_ext.carray.__cinit__ (bcolz/carray_ext.c:13751)
  File "bcolz/carray_ext.pyx", line 1326, in bcolz.carray_ext.carray._read_meta (bcolz/carray_ext.c:18289)
IOError: [Errno 2] No such file or directory: u'/home/jeff/.zipline/data/my-yahoo-equities-bundle/2016-09-29T19;49;38.499378/minute_equities.bcolz/00/00/000000.bcolz/close/meta/sizes'

after calling:

	hist = history(21,'1d','close')

**Comment by curzonj** [comment]
I get the same error as @hamannj

**Comment by hamannj** [comment]
Doh! I found my problem... 

	hist = data.history(context.stocks, 'close', 21, '1d')

did the trick...

**Comment by FreddieV4** [comment]
A call to `history()` is deprecated and we use `data.history()` now, as @hamannj has stated above. If you experience this issue again, feel free to open another issue 😃
