### ISSUE TITLE
Error backtesting custom minute data: The requested TradingCalendar, TEST, does not exist.

### ISSUE THREAD

**Issue by jkleint** [quantopian/zipline#1532]
I'm trying to load custom minute data with `run_algorithm()`, but running into all kinds of trouble.

```
#!/usr/bin/env python3

from datetime import datetime

import pandas as pd
import pytz
import zipline
from zipline.api import order, symbol


def initialize(context):
    context.symbol = symbol('AAPL')


def handle_data(context, data):
    hist = data.history(context.symbol, ('open', 'high', 'low', 'close'), 1, '1m')
    print(hist)
    if data.can_trade(context.symbol):
        order(context.symbol, 1)
    else:
        print("Can't trade at {}".format(context.get_datetime()))


def main():
    """Run backtest using Zipline."""
    data = pd.DataFrame({
        'open': [1, 2, 3, 4],
        'high': [1, 2, 3, 4],
        'low': [1, 2, 3, 4],
        'close': [1, 2, 3, 4],
        'volume': [1, 2, 3, 4],
    }, index=pd.DatetimeIndex((datetime(2016, 10, 6, 13, 31), datetime(2016, 10, 6, 13, 32), datetime(2016, 10, 7, 13, 31), datetime(2016, 10, 7, 13, 32),), tz=pytz.timezone('UTC')))
    data = pd.Panel({'AAPL': data})
    print(data)
    zipline.run_algorithm(initialize=initialize, handle_data=handle_data, start=data['AAPL'].index.min(), end=data['AAPL'].index.max(), data=data, data_frequency='minute', capital_base=100000)


if __name__ == "__main__":
    main()

```

```
$ python --version
Python 3.5.2
$ pip freeze | grep zipline
zipline==1.0.2+163.g00a053c
$ ./bug1.py

<class 'pandas.core.panel.Panel'>
Dimensions: 1 (items) x 4 (major_axis) x 5 (minor_axis)
Items axis: AAPL to AAPL
Major_axis axis: 2016-10-06 13:31:00+00:00 to 2016-10-07 13:32:00+00:00
Minor_axis axis: close to volume
                           close  high  low  open
2016-10-06 13:31:00+00:00    1.0   1.0  1.0   1.0
Can't trade at 2016-10-06 13:31:00+00:00
                           close  high  low  open
2016-10-06 13:32:00+00:00    2.0   2.0  2.0   2.0
Can't trade at 2016-10-06 13:32:00+00:00
                           close  high  low  open
2016-10-06 13:33:00+00:00    NaN   NaN  NaN   NaN
Can't trade at 2016-10-06 13:33:00+00:00


[...snip...]


                           close  high  low  open
2016-10-07 13:31:00+00:00    3.0   3.0  3.0   3.0
Traceback (most recent call last):
  File "/quantopian/python/lib/python3.5/site-packages/zipline/utils/calendars/calendar_utils.py", line 82, in get_calendar
    factory = self._calendar_factories[canonical_name]
KeyError: 'TEST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bug1.py", line 39, in <module>
    main()
  File "./bug1.py", line 35, in main
    zipline.run_algorithm(initialize=initialize, handle_data=handle_data, start=data['AAPL'].index.min(), end=data['AAPL'].index.max(), data=data, data_frequency='minute', capital_base=100000)
  File "/quantopian/python/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 361, in run_algorithm
    environ=environ,
  File "/quantopian/python/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 180, in _run
    overwrite_sim_params=False,
  File "/quantopian/python/lib/python3.5/site-packages/zipline/algorithm.py", line 697, in run
    for perf in self.get_generator():
  File "/quantopian/python/lib/python3.5/site-packages/zipline/gens/tradesimulation.py", line 222, in transform
    for capital_change_packet in every_bar(dt):
  File "/quantopian/python/lib/python3.5/site-packages/zipline/gens/tradesimulation.py", line 135, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/quantopian/python/lib/python3.5/site-packages/zipline/utils/events.py", line 214, in handle_data
    dt,
  File "/quantopian/python/lib/python3.5/site-packages/zipline/utils/events.py", line 233, in handle_data
    self.callback(context, data)
  File "/quantopian/python/lib/python3.5/site-packages/zipline/algorithm.py", line 467, in handle_data
    self._handle_data(self, data)
  File "./bug1.py", line 18, in handle_data
    if data.can_trade(context.symbol):
  File "zipline/_protocol.pyx", line 125, in zipline._protocol.check_parameters.__call__.assert_keywords_and_call (zipline/_protocol.c:3031)
  File "zipline/_protocol.pyx", line 477, in zipline._protocol.BarData.can_trade (zipline/_protocol.c:6275)
  File "zipline/_protocol.pyx", line 510, in zipline._protocol.BarData._can_trade_for_asset (zipline/_protocol.c:6743)
  File "zipline/assets/_assets.pyx", line 230, in zipline.assets._assets.Asset.is_exchange_open (zipline/assets/_assets.c:4165)
  File "/quantopian/python/lib/python3.5/site-packages/zipline/utils/calendars/calendar_utils.py", line 85, in get_calendar
    raise InvalidCalendarName(calendar_name=name)
zipline.errors.InvalidCalendarName: The requested TradingCalendar, TEST, does not exist.

```

**Comment by richafrank** [comment]
Hi @jkleint , It looks like the asset stored in `context.symbol` has its exchange set to `"TEST"`.  So when your code calls `can_trade`, zipline tries to ask the trading calendar for that exchange whether it's open at the current simulation time; however, it can't find a calendar registered with that name.  

Unfortunately, it looks like a [regression] (https://github.com/quantopian/zipline/blob/0ace6f7b8f6b5bc4d8d609103c74ed60ddaf0170/zipline/assets/synthetic.py#L90-L90) in the [now-deprecated] (https://github.com/quantopian/zipline/blob/ec6f298972e53838afb8367da29df2f06f476e1c/zipline/algorithm.py#L751-L751) method of providing assets to the zipline simulator for the first time via the `data` panel.  That behavior of checking whether the exchange is open is new.

The new method, which _should_ work, is to write your assets (and pricing data) once to a custom [data bundle] (http://www.zipline.io/bundles.html), and then run your simulation multiple times with that bundle specified.

**Comment by ernestoeperez88** [comment]
Looks like this thread has gone stale. Please feel free to reopen if you have any more questions.
