### ISSUE TITLE
Error when running dual_moving_average.py example - Error parsing datetime string

### ISSUE THREAD

**Issue by jongheekang** [quantopian/zipline#1652]
# Description of issue

I just installed zipline and ran the basic dual_moving_average.py example with
zipline run -f dual_moving_average.py --start 2011-1-1 --end 2012-1-1 -o dma.pickle

However I received the following error

ValueError: Error parsing datetime string "2011-1-1" at position 5

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1681, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/lib/python3.6/site-packages/zipline/utils/cli.py", line 52, in convert
    return self.parser(value)
  File "/usr/local/lib/python3.6/site-packages/zipline/utils/cli.py", line 89, in parser
    ts = super(Date, self).parser(value)
  File "/usr/local/lib/python3.6/site-packages/zipline/utils/cli.py", line 44, in parser
    return pd.Timestamp(value, tz=self.tz)
  File "pandas/tslib.pyx", line 298, in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:8967)
  File "pandas/tslib.pyx", line 1146, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:22303)
  File "pandas/tslib.pyx", line 1254, in pandas.tslib.convert_str_to_tsobject (pandas/tslib.c:23902)
  File "pandas/src/datetime.pxd", line 139, in datetime._string_to_dts (pandas/tslib.c:80274)
SystemError: <class 'str'> returned a result with an error set

# Environment

* Operating System: macOS 10.12.2
* Python Version: 3.6.0
* Zipline Version: 1.0.2
* pip3 Version: 9.0.1
* pandas Version: 0.17.0 (I downgraded it due to avoid warnings see #1485 )

Thanks.

**Comment by youzhonghui** [comment]
I got this error too.

**Comment by Georgantas** [comment]
I get this too.

**Comment by litch** [comment]
If you do:

`--start 2011-01-01 --end 2012-01-01`

instead of:

`--start 2011-1-1 --end 2012-1-1`

It should get past that phase.  I just got bitten by this as well, though am having other issues now with this same Python & Zipline & OS version combination.

**Comment by litch** [comment]
It should be noted that if you try to do the conda install (`conda install -c Quantopian zipline`) it will error with python3.6.  And I had to downgrade to python 3.4 (`conda create --name py34 python=3.4 && source activate py34`) in order to install it.

That installed fine, but everything seems totally broken still with a new error.  I'm wondering if this is just a broken project.

**Comment by Georgantas** [comment]
Yeah, the documentation isn't too amazing either. It'd be nice if we could get a list of dependancy versions for a functioning instance.

**Comment by litch** [comment]
FWIW, it looks like this example

`examples/buyapple.ipynb` works.  At least in the docker container version of this (python 2.7???) that I finally resorted to.  The ema example we were referencing before still does not work in a "pristine" zipline environment.

**Comment by FreddieV4** [comment]
Hi @jongheekang thanks for notifying us of your issue. So it looks like @litch has posted the fix to this above ^^ in that you'll need to use py27 or py34.

@litch sorry, we don't have conda packages for Python 3.5+ yet, but feel free to open a new issue with the new error you're having after downgrading to py34

**Comment by HyperionSounds** [comment]
I just got this error today after updating to the newest Mac OS High Sierra 10.13.6... any thoughts?

**Comment by freddiev4** [comment]
@HyperionSounds what version of Python are you running / can you fill out a new issue template?

**Comment by HyperionSounds** [comment]
@freddiev4 Hi Frieddie,
I am running 3.6.3; It was in running zipline-live in trying to connect with interactive brokers... I'll mess around with it for a little while, and open a new issue template if it continues

**Comment by freddiev4** [comment]
@HyperionSounds FWIW, we don't create packages for Python 3.6 or test for Py36 either. I'd recommend downgrading to Py35
