### ISSUE TITLE
Error in installing zipline via conda

### ISSUE THREAD

**Issue by jonsariaatmadja** [quantopian/zipline#1797]
Hi Zipline maintainers,

I've tried to install zipline via conda using: conda install -c Quantopian zipline but came to the error below. Please help.

Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/Qantopian

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.......

PackageNotFoundError: Package missing in current osx-64 channels:
  - zipline

**Comment by jonsariaatmadja** [comment]
I also tried this in the terminal: 
```conda install -c Quantopian -c https://conda.anaconda.org/Quantopian/label/ci zipline```

but, the result is that despite having zipline installed, there is an error during import:

```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-caeca508216f> in <module>()
----> 1 import zipline

//anaconda/lib/python2.7/site-packages/zipline/__init__.pyc in <module>()
     39 from . import gens
     40 from . import utils
---> 41 from .utils.run_algo import run_algorithm
     42 from ._version import get_versions
     43 # These need to happen after the other imports.

//anaconda/lib/python2.7/site-packages/zipline/utils/run_algo.py in <module>()
     16 
     17 from zipline.algorithm import TradingAlgorithm
---> 18 from zipline.data.bundles.core import load
     19 from zipline.data.data_portal import DataPortal
     20 from zipline.finance.trading import TradingEnvironment

//anaconda/lib/python2.7/site-packages/zipline/data/bundles/__init__.py in <module>()
      1 # These imports are necessary to force module-scope register calls to happen.
----> 2 from . import quandl  # noqa
      3 from .core import (
      4     UnknownBundle,
      5     bundles,

//anaconda/lib/python2.7/site-packages/zipline/data/bundles/quandl.py in <module>()
     13 from six.moves.urllib.parse import urlencode
     14 
---> 15 from . import core as bundles
     16 from zipline.utils.cli import maybe_show_progress
     17 

//anaconda/lib/python2.7/site-packages/zipline/data/bundles/core.py in <module>()
     22 )
     23 from zipline.assets import AssetDBWriter, AssetFinder, ASSET_DB_VERSION
---> 24 from zipline.assets.asset_db_migrations import downgrade
     25 from zipline.utils.cache import (
     26     dataframe_cache,

//anaconda/lib/python2.7/site-packages/zipline/assets/asset_db_migrations.py in <module>()
      1 from functools import wraps
      2 
----> 3 from alembic.migration import MigrationContext
      4 from alembic.operations import Operations
      5 import sqlalchemy as sa

//anaconda/lib/python2.7/site-packages/alembic/__init__.py in <module>()
      6 
      7 
----> 8 from . import op  # noqa
      9 from . import context  # noqa

//anaconda/lib/python2.7/site-packages/alembic/op.py in <module>()
      4 # create proxy functions for
      5 # each method on the Operations class.
----> 6 util.create_module_class_proxy(Operations, globals(), locals())

AttributeError: 'module' object has no attribute 'create_module_class_proxy'```

**Comment by FreddieV4** [comment]
Hi @jonsariaatmadja you're seeing this error because we have not yet built OS-X packages for the latest version of zipline. For now, I'd recommend downloading zipline from the master branch on GitHub.

**Comment by jonsariaatmadja** [comment]
Thanks FreddieV4,

I tried your recommendation and still got this error:

PackageNotFoundError: Package missing in current osx-64 channels:
  - git+https://github.com/quantopian/zipline.git

**Comment by FreddieV4** [comment]
@jonsariaatmadja did you try installing via pip?

**Comment by jonsariaatmadja** [comment]
Yes I used both pip and conda. (Since I have Anaconda and have 2 versions) of numpy, pandas and zipline. I think my mac uses conda when using it in terminal and iPython:

```zipline                   1.0.2               np110py27_0    Quantopian
zipline                   1.1.0+133.gbe8ea7c           <pip>```

```pandas                    0.21.0.dev0+54.g0d43131           <pip>
pandas                    0.17.1              np110py27_0```

```numpy                     1.12.1                    <pip>
numpy                     1.10.2                   py27_0```

**Comment by jonsariaatmadja** [comment]
I tried to force update my pandas but it came to the following outcomes:

```conda install pandas=0.18
Fetching package metadata .........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pandas 0.18*
  - zipline -> pandas >=0.16.1,<0.18
Use "conda info <package>" to see the dependencies for each package.```

**Comment by jonsariaatmadja** [comment]
I upgraded my pandas to 0.17 and came out with a new error when importing zipline:

```import zipline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/zipline/__init__.py", line 20, in <module>
    from . import data
  File "//anaconda/lib/python2.7/site-packages/zipline/data/__init__.py", line 1, in <module>
    from . import loader
  File "//anaconda/lib/python2.7/site-packages/zipline/data/loader.py", line 20, in <module>
    from pandas_datareader.data import DataReader
  File "//anaconda/lib/python2.7/site-packages/pandas_datareader/data.py", line 7, in <module>
    from pandas_datareader.google.daily import GoogleDailyReader
  File "//anaconda/lib/python2.7/site-packages/pandas_datareader/google/daily.py", line 1, in <module>
    from pandas_datareader.base import _DailyBaseReader
  File "//anaconda/lib/python2.7/site-packages/pandas_datareader/base.py", line 11, in <module>
    from pandas.core.common import PandasError, is_number
ImportError: cannot import name PandasError```

**Comment by FreddieV4** [comment]
Can you try installing the latest version of zipline using `pip install -U zipline`?

**Comment by jonsariaatmadja** [comment]
Yes I did.

**Comment by FreddieV4** [comment]
Sorry, I meant to also mention that we recently did a new release of zipline, `1.1.1`. Did that install work for you?

**Comment by kkshyu** [comment]
@jonsariaatmadja  I have faced the same issue and I tried the followings then it works...

1. create a new conda env: `conda create -n dev && activate dev`
2. do not install anaconda, it may limit your pandas and other packages' version
3. install zipline with conda: `conda install -c quantopian zipline`

Notice: if you are using jupyter, you should install jupyter again in the new conda env. In my case, i didn't reinstall jupyter notebook in the new conda env and got the same error with you for a long time... 

Hope it may help you.
