### ISSUE TITLE
set_benchmark not working

### ISSUE THREAD

**Issue by ikfdarba** [quantopian/zipline#1827]
Zipline 1.0.2

Hello,

i am trying to set a different benchmark in a zipline simulation but am not being successful:

this is the simple code i  am running

```
from zipline.api import order, record, symbol, set_benchmark


def initialize(context):
    set_benchmark(symbol('AAPL'))


def handle_data(context, data):
    order(symbol('AAPL'), 10)
```

and am however getting incorrect results:

```
algo_volatility  algorithm_period_return     alpha  \
2016-08-18 20:00:00              NaN             0.000000e+00       NaN   
2016-08-19 20:00:00         0.000001            -1.000000e-07 -0.000008   
2016-08-22 20:00:00         0.000008            -1.050000e-06 -0.000040   

                     benchmark_period_return  benchmark_volatility      beta  \
2016-08-18 20:00:00                -0.001282                   NaN       NaN   
2016-08-19 20:00:00                 0.001282              0.043202 -0.000026   
2016-08-22 20:00:00                -0.006501              0.082955  0.000089   
```
 the alögor and benchmark returns should be the same....

what is the problem?

**Comment by ernestoeperez88** [comment]
Hi @ikfdarba. Could you please share with us the full error/stack trace? 

Are you otherwise able to run backtests in minute mode (by commenting out ```set_benchmark(symbol('AAPL'))```)? Note that the default data bundles do not include minute frequency data. You would need to provide your own data, and [create a custom bundle](http://www.zipline.io/bundles.html#writing-a-new-bundle) with it.

**Comment by lukevs** [comment]
Also experiencing this. Imported a custom bundle from CSV with minute data.

Here's the stack trace:
```Traceback (most recent call last):
  File "/projects/spy.py", line 27, in <module>
    end=pd.Timestamp('05-2013', tz='UTC'))
  File "/zipline/zipline/utils/run_algo.py", line 371, in run_algorithm
    environ=environ,
  File "/zipline/zipline/utils/run_algo.py", line 186, in _run
    overwrite_sim_params=False,
  File "/zipline/zipline/algorithm.py", line 721, in run
    for perf in self.get_generator():
  File "/zipline/zipline/algorithm.py", line 608, in get_generator
    return self._create_generator(self.sim_params)
  File "/zipline/zipline/algorithm.py", line 587, in _create_generator
    self._create_benchmark_source(),
  File "/zipline/zipline/algorithm.py", line 559, in _create_benchmark_source
    benchmark_returns=benchmark_returns,
  File "/zipline/zipline/sources/benchmark_source.py", line 49, in __init__
    self.data_portal
  File "/zipline/zipline/sources/benchmark_source.py", line 173, in _initialize_precalculated_series
    ffill=True
  File "/zipline/zipline/data/data_portal.py", line 910, in get_history_window
    "close", data_frequency)
  File "/zipline/zipline/data/data_portal.py", line 757, in _get_history_daily_window
    assets, days_for_window, end_dt, field_to_use, data_frequency
  File "/zipline/zipline/data/data_portal.py", line 780, in _get_history_daily_window_data
    extra_slot=False
  File "/zipline/zipline/data/data_portal.py", line 1063, in _get_daily_window_data
    extra_slot)
  File "/zipline/zipline/data/history_loader.py", line 550, in history
    is_perspective_after)
  File "/zipline/zipline/data/history_loader.py", line 432, in _ensure_sliding_windows
    array = self._array(prefetch_dts, needed_assets, field)
  File "/zipline/zipline/data/history_loader.py", line 574, in _array
    assets,
  File "/zipline/zipline/data/dispatch_bar_reader.py", line 120, in load_raw_arrays
    for t in asset_types if sid_groups[t]}
  File "/zipline/zipline/data/dispatch_bar_reader.py", line 120, in <dictcomp>
    for t in asset_types if sid_groups[t]}
  File "/zipline/zipline/data/us_equity_pricing.py", line 629, in load_raw_arrays
    assets,
  File "/zipline/zipline/data/us_equity_pricing.py", line 619, in _compute_slices
    assets,
  File "zipline/data/_equities.pyx", line 44, in zipline.data._equities._compute_row_slices
  File "zipline/data/_equities.pyx", line 103, in zipline.data._equities._compute_row_slices
K```

Here's the example algorithm:
```import pandas as pd
from zipline import run_algorithm, api


def initialize(context):
    """called once at the start of the algorithm"""

    security = api.symbol('SPY')
    api.set_benchmark(security)


def handle_data(context, data):
    print('Date: {}'.format(context.get_datetime()))

    security = api.symbol('SPY')
    api.order_target_percent(security, 1.0)


if __name__ == '__main__':
    perf = run_algorithm(
        initialize=initialize,
        capital_base=2500000,
        bundle='custom-csv-bundle',
        handle_data=handle_data,
        data_frequency='minute',
        start=pd.Timestamp('02-2013', tz='UTC'),
        end=pd.Timestamp('05-2013', tz='UTC'))

    perf.to_pickle('result.pickle')
```

Running inside a container from the included Dockerfile with
`docker exec -it zipline python /projects/spy.py`

Commenting out the `set_benchmark` does silence the error, but also breaks the results pickle in a weird way since the default benchmark is daily (not sure why it does this, separate bug):
```%pylab inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

perf = pd.read_pickle('result.pickle')

fig = plt.figure(figsize=(20, 20))
ax = fig.add_subplot(211)
perf.portfolio_value.plot(ax=ax)
((perf.benchmark_period_return + 1) * perf.portfolio_value[0]).plot(ax=ax)```
![image](https://user-images.githubusercontent.com/5885679/34910534-5376fd30-f885-11e7-8874-0d9664e32256.png)
