### ISSUE TITLE
ImportError: cannot import name information_ratio

### ISSUE THREAD

**Issue by ginward** [quantopian/zipline#1855]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: OS X 10.12.5
* Python Version: `python --2.7.13`
* Python Bitness: `64`
* How did you install Zipline: (`pip`)
* Python packages:
```
alembic==0.9.2
appdirs==1.4.3
appnope==0.1.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
bleach==2.0.0
Bottleneck==1.2.1
certifi==2017.4.17
chardet==3.0.4
click==6.7
conda==4.3.16
configparser==3.5.0
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.25.2
decorator==4.0.11
empyrical==0.3.0
entrypoints==0.2.2
enum34==1.1.6
functools32==3.2.3.post2
html5lib==0.999999999
idna==2.5
intervaltree==2.1.0
ipykernel==4.6.1
ipython==5.3.0
ipython-genutils==0.2.0
ipywidgets==6.0.0
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
Logbook==1.0.0
lru-dict==1.1.6
Mako==1.0.6
MarkupSafe==1.0
mistune==0.7.4
multipledispatch==0.4.9
nbconvert==5.1.1
nbformat==4.3.0
networkx==1.11
notebook==5.0.0
numexpr==2.6.2
numpy==1.12.1
packaging==16.8
pandas==0.18.1
pandas-datareader==0.4.0
pandocfilters==1.4.1
pathlib2==2.2.1
patsy==0.4.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pycosat==0.6.1
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2017.2
pyzmq==16.0.2
qtconsole==4.3.0
requests==2.18.1
requests-file==1.4.2
requests-ftp==0.3.1
ruamel.ordereddict==0.4.9
ruamel.yaml==0.15.9
sas7bdat==2.0.7
scandir==1.5
scipy==0.19.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.11
statsmodels==0.8.0
tables==3.4.2
terminado==0.6
testpath==0.3
toolz==0.8.2
tornado==4.5.1
traitlets==4.3.2
urllib3==1.21.1
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==2.0.0
zipline==1.1.0
```

Now that you know a little about me, let me tell you about the issue I am
having:

# ImportError: cannot import name information_ratio

I was simply importing zipline and then it throws and error: ImportError: cannot import name information_ratio

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. pip install zipline 
2. create a py file "zip.py"
3. write `import zipline.api` or `import zipline` or `from zipline.api import order, record, symbol`
4. write on terminal `python zip.py`

## What steps have you taken to resolve this already?

`$ brew install freetype pkg-config gcc openssl`

`$ pip install zipline`

`$ pip install empyrical `

...

# Traceback

```
Traceback (most recent call last):
  File "zip.py", line 1, in <module>
    import zipline.api
  File "/usr/local/lib/python2.7/site-packages/zipline/__init__.py", line 42, in <module>
    from .utils.run_algo import run_algorithm
  File "/usr/local/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "/usr/local/lib/python2.7/site-packages/zipline/algorithm.py", line 85, in <module>
    from zipline.finance.performance import PerformanceTracker
  File "/usr/local/lib/python2.7/site-packages/zipline/finance/performance/__init__.py", line 16, in <module>
    from . tracker import PerformanceTracker
  File "/usr/local/lib/python2.7/site-packages/zipline/finance/performance/tracker.py", line 69, in <module>
    import zipline.finance.risk as risk
  File "/usr/local/lib/python2.7/site-packages/zipline/finance/risk/__init__.py", line 16, in <module>
    from . report import RiskReport
  File "/usr/local/lib/python2.7/site-packages/zipline/finance/risk/report.py", line 64, in <module>
    from . period import RiskMetricsPeriod
  File "/usr/local/lib/python2.7/site-packages/zipline/finance/risk/period.py", line 28, in <module>
    from empyrical import (
ImportError: cannot import name information_ratio
```

Sincerely,
`Jinhua Wang`

**Comment by richafrank** [comment]
Hi @ginward ! The latest empyrical release broke compatibility with zipline, so you can either downgrade empyrical to 0.2.2 or install the [compatibility branch](https://github.com/quantopian/zipline/pull/1854) of zipline that hasn't been merged to master yet.

**Comment by ginward** [comment]
Thanks. It seems that I can use conda instead to install it.

**Comment by sokol11** [comment]
This is still an issue on empyrical 0.5.3

**Comment by richafrank** [comment]
Hi @sokol11 , `information_ratio` was removed from empyrical and then from [zipline in v1.1.1](https://github.com/quantopian/zipline/pull/1854/commits/0d759ad80fc7666db287c40a624fada502acc2a3) (released July 5, 2017). It sounds like you have an old version of zipline that still depends on `information_ratio`.
