### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by ginward** [quantopian/zipline#1856]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: OS X 10.12.5
* Python Version: `Python 2.7.13 :: Continuum Analytics, Inc.`
* Python Bitness: `64`
* How did you install Zipline: (conda)
* Python packages: 
```
alembic                   0.7.7                    py27_0    Quantopian
asn1crypto                0.22.0                   py27_0  
bcolz                     0.12.1              np110py27_0  
bottleneck                1.0.0               np110py27_1  
cachetools                1.1.6                    py27_0    Quantopian
cffi                      1.10.0                   py27_0  
click                     6.7                      py27_0  
conda                     4.3.22                   py27_0  
conda-env                 2.6.0                         0  
contextlib2               0.5.5                    py27_0  
cryptography              1.8.1                    py27_0  
cyordereddict             0.2.2                    py27_0    Quantopian
cython                    0.25.2                   py27_0  
decorator                 4.0.11                   py27_0  
empyrical                 0.2.0                    py27_0    Quantopian
enum34                    1.1.6                    py27_0  
idna                      2.5                      py27_0  
intervaltree              2.1.0                    py27_0    Quantopian
ipaddress                 1.0.18                   py27_0  
logbook                   0.12.5                   py27_0    Quantopian
mako                      1.0.6                    py27_0  
markupsafe                0.23                     py27_2  
mkl                       11.3.3                        0  
multipledispatch          0.4.9                    py27_0  
networkx                  1.11                     py27_0  
numexpr                   2.6.0               np110py27_0  
numpy                     1.10.4                   py27_2  
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
pandas                    0.17.1              np110py27_0  
pandas-datareader         0.4.0                    py27_0  
patsy                     0.4.1                    py27_0  
pip                       9.0.1                    py27_1  
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0  
pytz                      2017.2                   py27_0  
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
requests-file             1.4.1                    py27_0  
requests-ftp              0.3.1                    py27_0  
ruamel_yaml               0.11.14                  py27_1  
scipy                     0.17.1              np110py27_1  
setuptools                27.2.0                   py27_0  
six                       1.10.0                   py27_0  
sortedcontainers          1.4.4                    py27_0    Quantopian
sqlalchemy                1.1.11                   py27_0  
sqlite                    3.13.0                        0  
statsmodels               0.6.1               np110py27_1  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zipline                   1.0.2               np110py27_0    Quantopian
zlib                      1.2.8                         3
```

Now that you know a little about me, let me tell you about the issue I am
having:

# UnboundLocalError: local variable 'data' referenced before assignment

I was running the [example code](/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/examples) with command zipline run -f ../../zipline/examples/buyapple.py --start 2000-1-1 --end 2014-1-1 -o buyapple_out.pickle: 

```
from zipline.api import order, record, symbol


def initialize(context):
    pass


def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))

```

* Expected to output something like: 

```
AAPL
[2015-11-04 22:45:32.820166] INFO: Performance: Simulated 3521 trading days out of 3521.
[2015-11-04 22:45:32.820314] INFO: Performance: first open: 2000-01-03 14:31:00+00:00
[2015-11-04 22:45:32.820401] INFO: Performance: last close: 2013-12-31 21:00:00+00:00

```

* What happened instead?

Throw errors: 

```
[2017-06-21 14:47:50.402748] INFO: Loader: Cache at /Users/jinhuawang/.zipline/data/^GSPC_benchmark.csv does not have data from 1990-01-02 00:00:00+00:00 to 2017-06-19 00:00:00+00:00.
Downloading benchmark data for '^GSPC'.
[2017-06-21 14:47:50.418038] ERROR: Loader: failed to cache the new benchmark returns
Traceback (most recent call last):
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/data/loader.py", line 248, in ensure_benchmark_data
    last_date,
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/data/benchmarks.py", line 59, in get_benchmark_returns
    squeeze=True,  # squeeze tells pandas to make this a Series
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 498, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 262, in _read
    compression=kwds.get('compression', None))
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/pandas/io/common.py", line 258, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "/Users/jinhuawang/miniconda2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
Traceback (most recent call last):
  File "/Users/jinhuawang/miniconda2/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.0.2', 'console_scripts', 'zipline')()
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/__main__.py", line 240, in run
    environ=os.environ,
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 132, in _run
    env = TradingEnvironment(asset_db_path=connstr)
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/finance/trading.py", line 96, in __init__
    self.bm_symbol,
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/data/loader.py", line 165, in load_market_data
    trading_day,
  File "/Users/jinhuawang/miniconda2/lib/python2.7/site-packages/zipline/data/loader.py", line 253, in ensure_benchmark_data
    if not has_data_for_dates(data, first_date, last_date):
UnboundLocalError: local variable 'data' referenced before assignment
```

I think the cause of the problem might be some url to the datasets is not set properly. From my understanding zipline uses Yahoo Finance. Do I need to setup something before using it? Also, can I use live (real-time) trading data?

## What steps have you taken to resolve this already?

I tried to installed the data bundles using the command `zipline ingest`

Sincerely,
`Jinhua Wang`

**Comment by FreddieV4** [comment]
Hi @ginward previous releases of zipline do not currently work because of changes Yahoo made to their API (see #1776). You'll need to install the latest master branch of zipline. You can do that by:

- Forking zipline
- Cloning that repo
- Run `pip install zipline/` on your local zipline directory

When we cut a new release you'll be able to just `conda install` zipline or `pip install -U` zipline
