### ISSUE TITLE
ImportError when zipline ingest runs

### ISSUE THREAD

**Issue by pellertson** [quantopian/zipline#1885]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux debianbeast 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
* Python Version: python 2.7.9
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: 
alembic==0.9.3
apipkg==1.4
asteval==0.9.1
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.4.17
cffi==0.8.6
chardet==2.3.0
click==6.7
colorama==0.3.2
contextlib2==0.5.5
cov-core==1.15.0
coverage==4.4.1
cryptography==0.6.1
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.25.2
DBUtils==1.1
decorator==4.0.11
defusedxml==0.4.1
docutils==0.12
ecdsa==0.11
empyrical==0.3.0
enum==0.4.6
execnet==1.4.1
feedparser==5.1.3
funcsigs==1.0.2
functools32==3.2.3.post2
html5lib==0.999
idna==2.5
intervaltree==2.1.0
Jinja2==2.7.3
linecache2==1.0.0
Logbook==1.0.0
lru-dict==1.1.6
lxml==3.4.0
Mako==1.0.6
MarkupSafe==0.23
matplotlib==2.0.2
mock==1.0.1
multipledispatch==0.4.9
mutagen==1.25.1
mysql-connector-python==1.2.3
mysql-utilities==1.3.5
networkx==1.11
nose==1.3.7
numexpr==2.6.2
numpy==1.13.1
nupic==1.0.0
nupic.bindings==1.0.0
ordereddict==1.1
pandas==0.18.1
pandas-datareader==0.4.0
paramiko==1.15.1
pathlib2==2.3.0
patsy==0.4.1
pbr==3.1.1
peewee==2.10.1
pexpect==3.2
Pillow==2.6.1
ply==3.4
poloniex==0.0.8
prettytable==0.7.2
psutil==5.2.2
py==1.4.34
pyasn1==0.1.7
pycapnp==0.5.12
pycparser==2.10
pycrypto==2.6.1
pycups==1.9.63
pycurl==7.19.5
Pygments==2.0.1
pygobject==3.14.0
pygpgme==0.3
pyinotify==0.9.4
PyMySQL==0.7.11
pyOpenSSL==0.14
pyparsing==2.2.0
pyproj==1.9.5.1
pysmbc==1.0.15.3
pysqlite==2.6.3
pytest==3.1.3
pytest-cov==2.5.1
pytest-xdist==1.18.1
python-apt==0.9.3.12
python-dateutil==2.6.1
python-debian==0.1.27
python-editor==1.0.3
pytz==2017.2
PyYAML==3.12
quodlibet==3.2.2
reportbug==6.6.3
reportlab==3.1.8
requests==2.4.3
requests-file==1.4.2
requests-ftp==0.3.1
roman==2.0.0
scandir==1.5
scikit-learn==0.18.2
scipy==0.19.1
six==1.8.0
sklearn==0.0
SOAPpy==0.12.22
sortedcontainers==1.5.7
Sphinx==1.2.3
SQLAlchemy==1.1.11
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.10
tables==3.4.2
toolz==0.8.2
traceback2==1.4.0
unittest2==1.1.0
urllib3==1.9.1
uTidylib==0.2
validictory==1.1.1
vboxapi==1.0
wstools==0.4.3
zipline==1.1.1

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I ran `zipline ingest`, but it only returned an ImportError saying ti can't import `viewkeys`

Output:
```
Traceback (most recent call last):
  File "/home/pellertson/Documents/python_virtual_envs/zipline/bin/zipline", line 7, in <module>
    from zipline.__main__ import main
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/__init__.py", line 20, in <module>
    from . import data
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/data/__init__.py", line 1, in <module>
    from . import loader
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/data/loader.py", line 31, in <module>
    from zipline.utils.calendars import get_calendar
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/utils/calendars/__init__.py", line 16, in <module>
    from .trading_calendar import TradingCalendar
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/utils/calendars/trading_calendar.py", line 36, in <module>
    from zipline.utils.input_validation import (
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/utils/input_validation.py", line 25, in <module>
    from zipline.utils.functional import getattrs
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/utils/functional.py", line 4, in <module>
    from six import viewkeys
ImportError: cannot import name viewkeys

```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `sudo apt-get install libatlas-base-dev python-dev gfortran pkg-config libfreetype6-dev`
2. `pip install zipline`
3. `zipline ingest`

## What steps have you taken to resolve this already?
I did try running `zipline ingest -b quantopian-quandl` but I only got the same output

Please help! :cry: 

Sincerely,
pellertson

**Comment by FreddieV4** [comment]
Hi @therasputinmachine it looks like you have some versions of libraries that are different from the ones zipline uses.

In zipline we use `six==1.10.0`and `numpy==1.11.1` whereas you have `six==1.8.0` and `numpy=1.13.1`. Can you try uninstalling and reinstalling zipline using `pip uninstall zipline` and `pip install zipline`?

**Comment by therasputinmachine** [comment]
Thank you @FreddieV4 for the comment!

After some fiddling, I found that I had installed an old version of six installed in `/usr/lib/python`, but the right one in the virtualenv. Now I have `six==1.10.0`, and I just made sure I had the same version of numpy as you suggested.

I ran the command again and it's still throwing an ImportError, but the logs are different:
```
Traceback (most recent call last):
  File "/home/pellertson/Documents/python_virtual_envs/zipline/bin/zipline", line 7, in <module>
    from zipline.__main__ import main
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/algorithm.py", line 89, in <module>
    from zipline.pipeline import Pipeline
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/pipeline/__init__.py", line 4, in <module>
    from .classifiers import Classifier, CustomClassifier
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/pipeline/classifiers/__init__.py", line 1, in <module>
    from .classifier import (
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/pipeline/classifiers/classifier.py", line 25, in <module>
    from ..filters import ArrayPredicate, NotNullFilter, NullFilter, NumExprFilter
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/pipeline/filters/__init__.py", line 1, in <module>
    from .filter import (
  File "/home/pellertson/Documents/python_virtual_envs/zipline/local/lib/python2.7/site-packages/zipline/pipeline/filters/filter.py", line 7, in <module>
    from numpy import (
ImportError: cannot import name nanpercentile
```
Does zipline require any other versions of libraries to work correctly?

**Comment by FreddieV4** [comment]
It looks like there's a few other libraries that are not the same versions that zipline uses. Did you try just uninstalling and reinstalling zipline within your virtualenv?

If not, just make a fresh virtualenv and try again

**Comment by therasputinmachine** [comment]
I have tried that. I did it when I made my last comment. I'll go ahead and give the fresh virtualenv a shot and I'll see if that works!

**Comment by therasputinmachine** [comment]
Nope. Still getting the same error.

**Comment by FreddieV4** [comment]
Hmm... If you'd like to, we can chat in our gitter channel? Or a Google
Hangout? Need to setup a time though as I'm currently out right now.

**Comment by therasputinmachine** [comment]
Hey I'm really sorry for the delayed response. Had some things I needed to take care of and this left my mind until recently. I still would like to fix this issue. I don't know what glitter is, but I do have my gmail listed on my profile.

**Comment by FreddieV4** [comment]
Hi @therasputinmachine you can find the Gitter channel [here](gitter.im/quantopian/zipline) and the [mailing list](https://groups.google.com/forum/#!forum/zipline) here 🙂

**Comment by freddiev4** [comment]
Hi @pellertson I'm going to close this due to inactivity but feel free to re-open if you have further issues.
