### ISSUE TITLE
Tuple Index out of range - timestamp issue with Pandas

### ISSUE THREAD

**Issue by ssattert** [quantopian/zipline#1900]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python 3.6.0 
* Python Bitness: `
* How did you install Zipline: Pip
* Python packages: `$ pip freeze` or `$ conda list`

alabaster==0.7.9
alembic==0.9.3
anaconda-client==1.6.0
anaconda-navigator==1.5
anaconda-project==0.4.1
astroid==1.4.9
astropy==1.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
bcolz==0.12.1
beautifulsoup4==4.5.3
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.4
boto==2.45.0
Bottleneck==1.2.0
cffi==1.9.1
chardet==2.3.0
chest==0.2.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.3.7
conda==4.3.14
configobj==5.0.6
contextlib2==0.5.4
cryptography==1.7.1
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.13.0
datashape==0.5.4
decorator==4.0.11
dill==0.2.5
docutils==0.13.1
empyrical==0.3.0
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12
Flask-Cors==3.0.2
gevent==1.2.1
greenlet==0.4.11
h5py==2.6.0
HeapDict==1.0.0
idna==2.2
imagesize==0.7.1
intervaltree==2.1.0
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.9.4
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
lazy-object-proxy==1.2.2
llvmlite==0.15.0
locket==0.2.0
Logbook==1.1.0
lru-dict==1.1.6
lxml==3.7.2
Mako==1.0.7
MarkupSafe==0.23
matplotlib==2.0.0
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.9
nbconvert==4.2.0
nbformat==4.2.0
networkx==1.11
nltk==3.2.2
nose==1.3.7
notebook==4.3.1
numba==0.30.1
numexpr==2.6.1
numpy==1.11.3
numpydoc==0.6.0
odo==0.5.0
openpyxl==2.4.1
pandas==0.18.1
pandas-datareader==0.5.0
partd==0.3.7
pathlib2==2.2.0
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
ply==3.9
prompt-toolkit==1.0.9
protobuf==3.3.0
psutil==5.0.1
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.5.0
Pygments==2.1.3
pylint==1.6.4
pyOpenSSL==16.2.0
pyparsing==2.1.4
pytest==3.0.5
python-dateutil==2.6.0
python-editor==1.0.3
pytz==2016.10
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.3
qtconsole==4.2.1
QtPy==1.2.1
redis==2.10.5
requests==2.12.4
requests-file==1.4.2
requests-ftp==0.3.1
resampy==0.1.5
rope-py3k==0.9.4.post1
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.18.1
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
sortedcontainers==1.5.7
SoundFile==0.9.0.post1
Sphinx==1.5.1
spyder==3.1.2
SQLAlchemy==1.1.5
statsmodels==0.6.1
sympy==1.0
tables==3.3.0
tensorflow-gpu==1.1.0
terminado==0.6
toolz==0.8.2
tornado==4.4.2
traitlets==4.3.1
unicodecsv==0.14.1
update==0.4.4
wcwidth==0.1.7
Werkzeug==0.11.15
widgetsnbextension==1.2.6
wrapt==1.10.8
xlrd==1.0.0
XlsxWriter==0.9.6
xlwt==1.2.0
zipline==1.1.1

Now that you know a little about me, let me tell you about the issue I am
having:

# I cannot examine my zipline pickle file due to errors. I have tried multiple fixes with nothing working. 

>>> perf = pd.read_pickle("test.pickle")
Traceback (most recent call last):
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 52, in try_read
    return pkl.load(fh)
  File "pandas/tslib.pyx", line 295, in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:9203)
  File "pandas/tslib.pyx", line 1343, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:25854)
TypeError: Cannot convert input to Timestamp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 57, in try_read
    return pc.load(fh, encoding=encoding, compat=False)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 117, in load
    return up.load()
  File "/opt/python/3.6-GPU/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 17, in load_reduce
    if type(args[0]) is type:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 65, in read_pickle
    return try_read(path)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 62, in try_read
    return pc.load(fh, encoding=encoding, compat=True)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 117, in load
    return up.load()
  File "/opt/python/3.6-GPU/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 17, in load_reduce
    if type(args[0]) is type:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 52, in try_read
    return pkl.load(fh)
  File "pandas/tslib.pyx", line 295, in pandas.tslib.Timestamp.__new__ (pandas/tslib.c:9203)
  File "pandas/tslib.pyx", line 1343, in pandas.tslib.convert_to_tsobject (pandas/tslib.c:25854)
TypeError: Cannot convert input to Timestamp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 57, in try_read
    return pc.load(fh, encoding=encoding, compat=False)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 117, in load
    return up.load()
  File "/opt/python/3.6-GPU/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 17, in load_reduce
    if type(args[0]) is type:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 68, in read_pickle
    return try_read(path, encoding='latin1')
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/io/pickle.py", line 62, in try_read
    return pc.load(fh, encoding=encoding, compat=True)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 117, in load
    return up.load()
  File "/opt/python/3.6-GPU/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/ihome/ssattert/.local/lib/python3.6/site-packages/pandas/compat/pickle_compat.py", line 17, in load_reduce
    if type(args[0]) is type:
IndexError: tuple index out of range

* What did you expect to happen?

I wanted to access the performance data of the algorithm. 

* What happened instead?
Error code shown above

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. use the beginner algorithm that Zipline provides
2. run the algorithm 
3. trying to access the pickle file using pandas.read_pickle
...

## What steps have you taken to resolve this already?
Tried to edit tslib.pyx, but my version is tslib.cpython-36m-x86_64-linux-gnu.so

Sincerely,
Steve

**Comment by FreddieV4** [comment]
Hi @ssattert it looks like there are some versions of libraries that are not consistent with the versions that zipline uses. We also don't support Python 3.6. We do support Python 2.7, 3.4, and 3.5.

You'll want to `pip install zipline` in a virtualenv that uses a different Python version or use a `conda env`.

**Comment by freddiev4** [comment]
Hi @ssattert I'm going to close this due to inactivity. Feel free to re-open if you have issues again or more questions 🙂
