### ISSUE TITLE
ImportError: cannot import name 'get_pytables_version'

### ISSUE THREAD

**Issue by thomas2004ch** [quantopian/zipline#1948]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows Server 2016 (64-bit)
* Python Version: 3.6.1
* Python Bitness: 
* How did you install Zipline: pip install zipline
* Python packages: The list is too long to post here

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I am successfully installed the zipline-1.1.1 under Python 3.6.1. But now I encounter another problem. If I run my following simple code as follow:
`import sys  
import os  
import pandas as pd
from zipline.api import fetch_csv, record, sid

def main():  
    print('Hello World!')

if __name__ == '__main__':  
    main()`

I get error message as follow:

...
runfile('D:/Python_Program/FetchCsv.py', wdir='D:/Python_Program')
Traceback (most recent call last):

  File "<ipython-input-1-6519ba671207>", line 1, in <module>
    runfile('D:/Python_Program/FetchCsv.py', wdir='D:/Python_Program')

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Python_Program/FetchCsv.py", line 7, in <module>
    from zipline.api import fetch_csv, record, sid

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\zipline\__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\zipline\utils\run_algo.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\zipline\algorithm.py", line 40, in <module>
    from zipline.data.data_portal import DataPortal

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\zipline\data\data_portal.py", line 47, in <module>
    from zipline.data.resample import (

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\zipline\data\resample.py", line 29, in <module>
    from zipline.data.minute_bars import MinuteBarReader

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\zipline\data\minute_bars.py", line 29, in <module>
    import tables

  File "C:\Users\Administrator\Anaconda3\lib\site-packages\tables\__init__.py", line 90, in <module>
    from .utilsextension import (

ImportError: cannot import name 'get_pytables_version'
...

* What did you expect to happen?
No error

* What happened instead?
Errror. See above-

## What steps have you taken to resolve this already?
I am looking for...
...

Sincerely,
Thomas

**Comment by thomas2004ch** [comment]
This does not happend by Python 3.5.4.

**Comment by freddiev4** [comment]
Hi @thomas2004ch as we're not yet building Python 3.6 packages I'm not so surprised this error occurred. Seems like this might be another thing to add to our list for when we want to start building Py36 packages.

**Comment by gurhanc** [comment]
I have the same issue with 2.7 version.

**Comment by DogeWatch** [comment]
> @thomas2004ch I have the same issue with 2.7 version.

have you solved it yet?

**Comment by ArthurSS** [comment]
seems that `pip install tables==3.3.0` works (recommended version in requirements.txt is 3.4.3)
