### ISSUE TITLE
KeyError issue: the label [2015-01-02 00:00:00+00:00] is not in the [index]

### ISSUE THREAD

**Issue by ezfine** [quantopian/zipline#1950]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Win10
* Python Version: Python 3.4.5
* Python Bitness: 64
* Python packages:
alabaster                 0.7.9                    py34_0  
alembic                   0.7.7                    py34_0    Quantopian
astroid                   1.4.9                    py34_0  
babel                     2.3.4                    py34_0  
backports_abc             0.5                      py34_0  
bcolz                     0.12.1              np111py34_0    Quantopian
bleach                    1.5.0                    py34_0  
bottleneck                1.2.0               np111py34_0  
bzip2                     1.0.6                    vc10_3  [vc10]
chardet                   3.0.4                    py34_0  
click                     6.7                      py34_0  
colorama                  0.3.9                    py34_0  
contextlib2               0.5.4                    py34_0  
cycler                    0.10.0                   py34_0  
cyordereddict             0.2.2                    py34_0    Quantopian
cython                    0.26                     py34_0  
decorator                 4.1.2                    py34_0  
docutils                  0.13.1                   py34_0  
empyrical                 0.2.2                    py34_0    Quantopian
entrypoints               0.2.3                    py34_0  
fix-yahoo-finance         0.0.18                    <pip>
hdf5                      1.8.17                   vc10_0  [vc10]
html5lib                  0.999                    py34_0  
icu                       57.1                     vc10_0  [vc10]
imagesize                 0.7.1                    py34_0  
intervaltree              2.1.0                    py34_0    Quantopian
ipykernel                 4.6.1                    py34_0  
ipython                   5.3.0                    py34_0  
ipython_genutils          0.2.0                    py34_0  
ipywidgets                5.2.2                    py34_1  
isort                     4.2.5                    py34_0  
jedi                      0.9.0                    py34_1  
jinja2                    2.9.6                    py34_0  
jpeg                      9b                       vc10_0  [vc10]
jsonschema                2.6.0                    py34_0  
jupyter                   1.0.0                    py34_3  
jupyter_client            5.1.0                    py34_0  
jupyter_console           5.0.0                    py34_0  
jupyter_core              4.3.0                    py34_0  
lazy-object-proxy         1.2.2                    py34_0  
libpng                    1.6.27                   vc10_0  [vc10]
logbook                   0.12.5                   py34_0    Quantopian
lru-dict                  1.1.4                    py34_0    Quantopian
m2-msys2-runtime          2.5.0.17080.65c939c               3  
mako                      1.0.6                    py34_0  
markupsafe                0.23                     py34_2  
matplotlib                2.0.0               np111py34_0  
mistune                   0.7.4                    py34_0  
mkl                       2017.0.3                      0  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.4.9                    py34_0  
multitasking              0.0.4                     <pip>
nbconvert                 5.2.1                    py34_0  
nbformat                  4.3.0                    py34_0  
networkx                  1.11                     py34_0  
notebook                  5.0.0                    py34_0  
numexpr                   2.6.1               np111py34_2  
numpy                     1.11.3                   py34_0  
numpydoc                  0.6.0                    py34_0  
openssl                   1.0.2l                   vc10_0  [vc10]
pandas                    0.18.1              np111py34_0  
pandas-datareader         0.2.1                    py34_0  
pandocfilters             1.4.1                    py34_0  
path.py                   10.0                     py34_0  
patsy                     0.4.1                    py34_0  
pep8                      1.7.0                    py34_0  
pickleshare               0.7.4                    py34_0  
pip                       9.0.1                    py34_1  
prompt_toolkit            1.0.14                   py34_0  
psutil                    5.0.1                    py34_0  
pyflakes                  1.5.0                    py34_0  
pygments                  2.2.0                    py34_0  
pylint                    1.6.4                    py34_1  
pyparsing                 2.2.0                    py34_0  
pyqt                      5.6.0                    py34_2  
pytables                  3.3.0               np111py34_0  
python                    3.4.5                         0  
python-dateutil           2.6.1                    py34_0  
pytz                      2017.2                   py34_0  
pyzmq                     16.0.2                   py34_0  
qt                        5.6.2                    vc10_5  [vc10]
qtawesome                 0.4.3                    py34_0  
qtconsole                 4.2.1                    py34_2  
qtpy                      1.2.1                    py34_0  
requests                  2.14.2                   py34_0  
requests-file             1.4.1                    py34_0  
rope                      0.9.4                    py34_1  
scipy                     0.19.1              np111py34_0  
setuptools                27.2.0                   py34_1  
simplegeneric             0.8.1                    py34_1  
sip                       4.18                     py34_0  
six                       1.10.0                   py34_0  
snowballstemmer           1.2.1                    py34_0  
sortedcontainers          1.4.4                    py34_0    Quantopian
sphinx                    1.5.1                    py34_0  
spyder                    3.1.2                    py34_0  
sqlalchemy                1.1.5                    py34_0  
statsmodels               0.6.1               np111py34_1  
TA-Lib                    0.4.10                    <pip>
testpath                  0.3.1                    py34_0  
tk                        8.5.18                   vc10_0  [vc10]
toolz                     0.8.2                    py34_0  
tornado                   4.5.1                    py34_0  
traitlets                 4.3.2                    py34_0  
vs2010_runtime            10.00.40219.1                 2  
wcwidth                   0.1.7                    py34_0  
wheel                     0.29.0                   py34_0  
widgetsnbextension        1.2.6                    py34_0  
win_unicode_console       0.5                      py34_0  
wrapt                     1.10.8                   py34_0  
zipline                   1.1.1               np111py34_0    Quantopian
zlib                      1.2.8                    vc10_3  [vc10]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

After several days works I found the KeyError issuse is caused by the [benchmark_return](https://github.com/quantopian/zipline/blob/77922ddedced4458fba7d2cb4c2a0826260f82fc/zipline/finance/trading.py#L96) data which was downloaded from Google finance by default. However, it only downloads for the past 1 year period and the KeyError exception is because my testing period starts more than one year. So, I tried to replace the cache file (SPY_benchmark.csv) by the one downloaded from [here](https://github.com/quantopian/zipline/blob/master/zipline/resources/market_data/SPY_benchmark.csv) (it contains a longer data to 1993). Unfortunately, zipline always replace by downloading a new one from Google finance. 

What can I do?

Jones

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. BuyApple.py
```python
from collections import OrderedDict
import pytz
from datetime import timedelta
from zipline import TradingAlgorithm
import pandas as pd
from zipline.api import (order, symbol)

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('AAPL'), 10)

data = OrderedDict()
data['AAPL'] = pd.read_csv('aapltest.csv', index_col='Date', parse_dates=['Date'])
panel = pd.Panel(data)
algo_obj = TradingAlgorithm(initialize=initialize, handle_data=handle_data)
perf_manual = algo_obj.run(panel)
```
2.aapltest.csv
```
Date,Open,High,Low,Close,Adj Close,Volume
2015-01-02,111.389999,111.440002,107.349998,109.33000200000001,103.86646999999999,53204600
2015-01-05,108.290001,108.650002,105.410004,106.25,100.940392,64285500
2015-01-06,106.540001,107.43,104.629997,106.260002,100.94989,65797100
2015-01-07,107.199997,108.199997,106.699997,107.75,102.36544,40105900
2015-01-08,109.230003,112.150002,108.699997,111.889999,106.29853100000001,59364500
2015-01-09,112.66999799999999,113.25,110.209999,112.010002,106.412552,53645500
2015-01-12,112.599998,112.629997,108.800003,109.25,103.790474,49650800
2015-12-14,112.18,112.68,109.790001,112.480003,108.679771,64318700
```
3. Error as below
```
Traceback (most recent call last):
  File "D:/Jones/Projects/Quant Study/BuyApple/BuyApple.py", line 19, in <module>
    perf_manual = algo_obj.run(panel)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\algorithm.py", line 709, in run
    for perf in self.get_generator():
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\gens\tradesimulation.py", line 230, in transform
    handle_benchmark(normalize_date(dt))
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\gens\tradesimulation.py", line 190, in handle_benchmark
    benchmark_source.get_value(date)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\sources\benchmark_source.py", line 75, in get_value
    return self._precalculated_series.loc[dt]
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1296, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1466, in _getitem_axis
    self._has_valid_type(key, axis)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1403, in _has_valid_type
    error()
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1390, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [2015-01-02 00:00:00+00:00] is not in the [index]'
```

**Comment by joneschg** [comment]
One more question.
I decide to work around this issue by using a more recent data as below:

```
Date,Open,High,Low,Close,Adj Close,Volume
2017-01-03,115.800003,116.33000200000001,114.760002,116.150002,114.72269399999999,28781900
2017-01-04,115.849998,116.510002,115.75,116.019997,114.594292,21118100
2017-01-05,115.91999799999999,116.860001,115.809998,116.610001,115.17703999999999,22193600
2017-01-06,116.779999,118.160004,116.470001,117.910004,116.461075,31751900
2017-01-09,117.949997,119.43,117.940002,118.989998,117.527794,33387600
2017-01-10,118.769997,119.379997,118.300003,119.110001,117.646317,24462100
2017-01-11,118.739998,119.93,118.599998,119.75,118.278458,27588600
```
The above KeyError is disappear, but I got a different but similar KeyError exception:
 ```
Traceback (most recent call last):
  File "C:\Program Files\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\PyCharm Community Edition 2017.1.4\helpers\pydev\pydevd.py", line 1023, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\PyCharm Community Edition 2017.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Jones/Projects/Quant Study/BuyApple/BuyApple.py", line 19, in <module>
    perf_manual = algo_obj.run(panel)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\algorithm.py", line 709, in run
    for perf in self.get_generator():
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\gens\tradesimulation.py", line 222, in transform
    for capital_change_packet in every_bar(dt):
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\gens\tradesimulation.py", line 120, in every_bar
    blotter.get_transactions(current_data)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\finance\blotter.py", line 367, in get_transactions
    slippage.simulate(bar_data, asset, asset_orders):
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\finance\slippage.py", line 126, in simulate
    price = data.current(asset, "close")
  File "zipline\_protocol.pyx", line 120, in zipline._protocol.check_parameters.__call__.assert_keywords_and_call (zipline\_protocol.c:3168)
  File "zipline\_protocol.pyx", line 331, in zipline._protocol.BarData.current (zipline\_protocol.c:4731)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\data\data_portal.py", line 528, in get_spot_value
    return get_single_asset_value(assets)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\data\data_portal.py", line 513, in get_single_asset_value
    asset, field, session_label,
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\data\data_portal.py", line 699, in _get_daily_spot_value
    return reader.get_value(asset, dt, column)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\data\dispatch_bar_reader.py", line 97, in get_value
    return r.get_value(asset, dt, field)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\zipline\data\us_equity_pricing.py", line 844, in get_value
    return self.panel.loc[sid, dt, field]
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1294, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 784, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 933, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1294, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 784, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 933, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1296, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1466, in _getitem_axis
    self._has_valid_type(key, axis)
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1403, in _has_valid_type
    error()
  File "C:\Users\jones\AppData\Local\conda\conda\envs\envZipline\lib\site-packages\pandas\core\indexing.py", line 1390, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [close] is not in the [index]'
```
Any idea is appreciated!

**Comment by zxweed** [comment]
Have the same issue, please help...

**Comment by marfeljoergsen** [comment]
Have the same issue here - appreciate something that could help...

**Comment by ezfine** [comment]
As @FreddieV4 closed tag above, there is the answer.

**Comment by FreddieV4** [comment]
The reason for this is because Google has now limited us to about 251 days worth of data, so you can't run backtests over a year. There is a fix currently being worked on.

There are duplicates of this issue so I'm just going to direct everyone to this issue: https://github.com/quantopian/zipline/issues/1965. I'll comment there when there is a fix on master
