### ISSUE TITLE
Install error (open CFI at the end of file)?

### ISSUE THREAD

**Issue by KojiIzawa** [quantopian/zipline#2003]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
    Linux vultr.guest 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: `$ python --version`
    Python 2.7.5
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
    64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)
    not yet, but try to pip
* Python packages: `$ pip freeze` or `$ conda list`
```
# pip freeze
alabaster==0.7.10
arrow==0.10.0
astroid==1.5.3
Babel==2.5.1
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
backports.weakref==1.0.post1
beautifulsoup4==4.6.0
bleach==1.5.0
bokeh==0.12.9
certifi==2017.7.27.1
chardet==3.0.4
configobj==4.7.2
configparser==3.5.0
cycler==0.10.0
decorator==3.4.0
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
ete3==3.0.0b35
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.1.1
html5lib==0.9999999
idna==2.5
imagesize==0.7.1
inflection==0.3.1
iniparse==0.4
ipykernel==4.6.1
ipython==5.5.0
ipython-genutils==0.2.0
ipython-sql==0.3.8
ipywidgets==7.0.1
isort==4.2.15
jedi==0.11.0
Jinja2==2.9.6
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
lazy-object-proxy==1.3.1
lxml==4.1.0
Markdown==2.6.9
MarkupSafe==1.0
matplotlib==2.0.2
mccabe==0.6.1
mistune==0.7.4
mock==2.0.0
more-itertools==3.2.0
MySQL-python==1.2.5
mysqlclient==1.3.12
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.1.0
numpy==1.13.3
numpydoc==0.7.0
pandas==0.20.3
pandas-datareader==0.5.0
pandocfilters==1.4.2
parso==0.1.0
pathlib2==2.3.0
patsy==0.4.1
pbr==3.1.1
perf==0.1
pexpect==4.2.1
pickleshare==0.7.4
pivottablejs==0.8.0
prettytable==0.7.2
prompt-toolkit==1.0.15
protobuf==3.4.0
psutil==5.4.0
ptyprocess==0.5.2
pycodestyle==2.3.1
pycosat==0.6.1
pycurl==7.19.0
pyflakes==1.6.0
Pygments==2.2.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pylint==1.7.4
PyMySQL==0.7.11
PyOpenGL==3.1.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-linux-procfs==0.4.9
pytz==2017.2
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
Quandl==3.2.0
requests==2.17.3
requests-file==1.4.2
requests-ftp==0.3.1
rope==0.10.7
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.34
scandir==1.6
schedutils==0.4
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.8.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
slip==0.4.0
slip.dbus==0.4.0
snowballstemmer==1.2.1
Sphinx==1.6.5
sphinxcontrib-websupport==1.0.1
spyder==3.2.4
SQLAlchemy==1.1.14
sqlparse==0.2.4
statsmodels==0.8.0
subprocess32==3.2.7
tensorflow==1.3.0
tensorflow-tensorboard==0.1.8
terminado==0.6
testpath==0.3.1
tornado==4.5.2
traitlets==4.3.2
typing==3.6.2
urlgrabber==3.10
urllib3==1.21.1
version-information==1.0.3
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
widgetsnbextension==3.0.3
wrapt==1.10.11
yum-metadata-parser==1.1.4
```
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
    complete to install zipline

* What happened instead?
    occored below error
```
# pip install zipline
Collecting zipline
  Using cached zipline-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Pythran.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Lexicon.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Parsing.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Code.py because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Tempita/_tempita.py because it changed.
    [ 1/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Code.py
    [ 2/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/FlowControl.py
    [ 3/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Lexicon.py
    [ 4/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Parsing.py
    [ 5/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Pythran.py
    [ 6/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Scanning.py
    [ 7/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Compiler/Visitor.py
    [ 8/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Plex/Actions.py
    [ 9/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Plex/Scanners.py
    [10/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Runtime/refnanny.pyx
    [11/11] Cythonizing /tmp/easy_install-DEMa2O/Cython-0.27.2/Cython/Tempita/_tempita.py
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    {standard input}: Assembler messages:
    {standard input}:66435: Warning: end of file not at end of a line; newline inserted
    {standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
    gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://bugzilla.redhat.com/bugzilla> for instructions.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7FzOpD/zipline/setup.py", line 317, in <module>
        **conditional_arguments
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 698, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 4
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7FzOpD/zipline/
```
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `pip install zipline`
2.
3.
...

## What steps have you taken to resolve this already?
especially not
...

# Anything else?

...

Sincerely,
Koji

**Comment by freddiev4** [comment]
Hi @KojiIzawa have you looked at the full installation guide? http://www.zipline.io/install.html. Seeing as there is a gcc failure there I'm thinking you might not have the right packages installed on your Linux distro.

**Comment by KojiIzawa** [comment]
Hi @freddiev4, Thank you nice answer! Finally, I have installed dnf and the packages are needed. Thank you very much again.
