### ISSUE TITLE
Ingestion from quandl WIKI is impossible due to pandas 0.18.1 and numpy 1.13.3 incompatibility

### ISSUE THREAD

**Issue by VitalyErmilov** [quantopian/zipline#2015]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu
* Python Version: 2.7
 
* How did you install Zipline:  pip 
* Python packages:  
alembic==0.9.6
backports.functools-lru-cache==1.4
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.2
decorator==4.1.2
empyrical==0.3.2
idna==2.6
intervaltree==2.1.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
multipledispatch==0.4.9
networkx==1.9.1
numexpr==2.6.4
numpy==1.13.3
pandas==0.18.1
pandas-datareader==0.5.0
patsy==0.4.1
pkg-resources==0.0.0
pyparsing==2.2.0
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.2
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==0.19.1
six==1.11.0
sortedcontainers==1.5.7
SQLAlchemy==1.1.14
statsmodels==0.8.0
subprocess32==3.2.7
tables==3.4.2
toolz==0.8.2
urllib3==1.22
v==3.0.0
zipline==1.1.1

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
When trying to ingest data from quandl WIKI the following error appears:

 
(venv-zipline) ubuntu@ip-172-31-34-154:~/venv-zipline$ zipline ingest -b quandl
Downloading WIKI metadata:   [####################################]
Traceback (most recent call last):
  File "/home/ubuntu/venv-zipline/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.1.1', 'console_scripts', 'zipline')()
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/__main__.py", line 312, in ingest
    show_progress,
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/data/bundles/quandl.py", line 295, in quandl_bundle
    show_progress=show_progress,
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/zipline/data/bundles/quandl.py", line 129, in fetch_symbol_metadata_frame
    data['auto_close_date'] = data['end_date'] + pd.Timedelta(days=1)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/pandas/core/ops.py", line 609, in wrapper
    na_op)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/pandas/core/ops.py", line 569, in maybe_convert_for_time_op
    return cls(left, right, name, na_op)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/pandas/core/ops.py", line 282, in __init__
    lvalues = self._convert_to_array(left, name=name)
  File "/home/ubuntu/venv-zipline/local/lib/python2.7/site-packages/pandas/core/ops.py", line 398, in _convert_to_array
    if (inferred_type in ('datetime64', 'datetime', 'date', 'time') or
TypeError: data type "datetime" not understood

 

## What steps have you taken to resolve this already?
I did a little research on the issue, it looks like the error is due to incompatibility of pandas and numpy libraries versions that are installed by default in the current zipline package and could be resolved by upgrading pandas. 
 
Sincerely,
Vitaly

**Comment by ernestoeperez88** [comment]
Hi @VitalyErmilov,

This issue is addressed by https://github.com/quantopian/zipline/pull/1990. 

This update also uses Quandl's new API which significantly increases construction of the data bundle. It should be available soon.

**Comment by VitalyErmilov** [comment]
@ernestoeperez88  thank you for the answer

**Comment by ernestoeperez88** [comment]
Vitaly, I am closing this issue as it was fixed by the PR mentioned above. 

You can track the memory issue in https://github.com/quantopian/zipline/issues/2022
