### ISSUE TITLE
Installation Issue - module not found

### ISSUE THREAD

**Issue by sjdenison58** [quantopian/zipline#2019]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10 Home, 64-bit
* Python Version: 3.4.5
* Python Bitness: This returned "SyntaxError: EOL while scanning string literal", not sure if I'm a noob...
* How did you install Zipline: conda
* Python packages: 

alembic                   0.7.7                    py34_0    Quantopian
bcolz                     0.12.1              np111py34_0    Quantopian
bottleneck                1.2.0               np111py34_0
bzip2                     1.0.6                    vc10_3  [vc10]
click                     6.7                      py34_0
contextlib2               0.5.4                    py34_0
cyordereddict             0.2.2                    py34_0    Quantopian
cython                    0.26                     py34_0
decorator                 4.1.2                    py34_0
empyrical                 0.2.2                    py34_0    Quantopian
hdf5                      1.8.17                   vc10_0  [vc10]
intel-openmp              2018.0.0             hcd89f80_7
intervaltree              2.1.0                    py34_0    Quantopian
logbook                   0.12.5                   py34_0    Quantopian
lru-dict                  1.1.4                    py34_0    Quantopian
mako                      1.0.6                    py34_0
markupsafe                1.0                      py34_0
mkl                       2017.0.4             h6d528fc_0
multipledispatch          0.4.9                    py34_0
networkx                  1.11                     py34_0
numexpr                   2.6.1               np111py34_2
numpy                     1.11.3                   py34_0
pandas                    0.18.1              np111py34_0
pandas-datareader         0.2.1                    py34_0
patsy                     0.4.1                    py34_0
pip                       9.0.1                    py34_1
pytables                  3.3.0               np111py34_0
python                    3.4.5                         0
python-dateutil           2.6.1                    py34_0
pytz                      2017.2                   py34_0
requests                  2.14.2                   py34_0
requests-file             1.4.1                    py34_0
scipy                     0.19.1              np111py34_0
setuptools                27.2.0                   py34_1
six                       1.10.0                   py34_0
sortedcontainers          1.4.4                    py34_0    Quantopian
sqlalchemy                1.1.5                    py34_0
statsmodels               0.6.1               np111py34_1
toolz                     0.8.2                    py34_0
vc                        10                            0
vs2010_runtime            10.00.40219.1                 2
wheel                     0.29.0                   py34_0
zipline                   1.1.1               np111py34_0    Quantopian
zlib                      1.2.11                   vc10_0  [vc10]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I've been a quantopian user for some time now but have only ever used the IDE on the site. Recently, I've tried to install zipline, but I am fairly new to python and have been unable to do so successfully. 

So far I've:
- Installed Anaconda3
- Created a new environment running python 3.4.5 (I saw somewhere in a thread about a similar issue that 3.5 may not be supported?)
- Installed zipline [following these instructions](http://www.zipline.io/install.html#installing-with-conda)

I am now trying to follow [this tutorial](http://www.zipline.io/beginner-tutorial.html#basics) and run:

`zipline run --help`

However, I get the error:

```
(zipline) C:\Users\CoopPC-1>zipline run --help
Traceback (most recent call last):
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline==1.1.1', 'console_scripts', 'zipline')()
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\setuptools-27.2.0-py3.4.egg\pkg_resources\__init__.py", line 565, in load_entry_point
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\setuptools-27.2.0-py3.4.egg\pkg_resources\__init__.py", line 2598, in load_entry_point
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\setuptools-27.2.0-py3.4.egg\pkg_resources\__init__.py", line 2258, in load
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\setuptools-27.2.0-py3.4.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\utils\run_algo.py", line 17, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\algorithm.py", line 79, in <module>
    from zipline.finance.performance import PerformanceTracker
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\performance\__init__.py", line 16, in <module>
    from . tracker import PerformanceTracker
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\performance\tracker.py", line 69, in <module>
    import zipline.finance.risk as risk
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\risk\__init__.py", line 16, in <module>
    from . report import RiskReport
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\risk\report.py", line 64, in <module>
    from . period import RiskMetricsPeriod
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\risk\period.py", line 28, in <module>
    from empyrical import (
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\empyrical-0.2.2-py3.4.egg\empyrical\__init__.py", line 21, in <module>
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\empyrical-0.2.2-py3.4.egg\empyrical\stats.py", line 20, in <module>
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\scipy\stats\__init__.py", line 348, in <module>
    from .stats import *
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\scipy\stats\stats.py", line 175, in <module>
    import scipy.special as special
  File "C:\Users\CoopPC-1\Anaconda3\envs\zipline\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
```

## What steps have you taken to resolve this already?

I've tried running python, and then in help() looking at the modules and I see zipline, but if I try to just type in zipline i get the error:

```
>>>help()
help> modules
help> zipline
problem in zipline - ImportError: cannot import name 'data'
```

Any help would be sincerely appreciated! Thanks!

Sincerely,
Steve

**Comment by Suveshtr** [comment]
I'm facing the same issue and had done the exact same steps. What was the resolution to the problem please ?

**Comment by leoniloris** [comment]
pip install tables==3.5.2

**Comment by davidpasini** [comment]
I'm having the same issue both with new environments with Python 3.5 and 3.6. Any luck thus far, anybody?

**Comment by ndhuanhuan** [comment]
@davidpasini 
I ran into many issues, and following instructions work for me (windows 8):
```
1. conda config --set allow_conda_downgrades true
2. conda install conda=4.6.11
3. conda create -n env_zipline python=3.6
4. activate env_zipline
5. conda install -c Quantopian zipline (at this point, if I import zipline, I'll encounter the issue mentioned above)
6. conda install python=3.6.8=h9f7ef89_0
7. pip install tables==3.5.2 (at this point, error change to 'ValueError: numpy.ufunc size changed, may ind ted 216 from C header')
8. pip install numpy==1.16.1
```

**Comment by as11132003** [comment]
Thank you ndhuanhuan! It worked for me.  I had the issue in windows 10, python 3.6.12. Steps 7 and 8 were the critical for me.
