### ISSUE TITLE
when running the tutorial code, I get the error "KeyError: 'Close'"

### ISSUE THREAD

**Issue by sculd** [quantopian/zipline#2048]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macos Sierra
* Python Version: Python 2.7.10
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'` 64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`) pip
* Python packages: `$ pip freeze` or `$ conda list`
alembic==0.9.6
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2017.11.5
chardet==3.0.4
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
empyrical==0.3.3
idna==2.6
intervaltree==2.1.0
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
multipledispatch==0.4.9
networkx==2.0
numexpr==2.6.4
numpy==1.13.3
pandas==0.19.2
pandas-datareader==0.5.0
patsy==0.4.1
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
scipy==1.0.0
six==1.11.0
sortedcontainers==1.5.9
SQLAlchemy==1.1.15
statsmodels==0.8.0
tables==3.4.2
toolz==0.8.2
tslib==1.5.1
urllib3==1.22
zipline==1.1.1

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I am running sandboz_zipline.py

from zipline.api import order, record, symbol

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))

with 
zipline run -f sandbox_zipline.py -b quantopian-quandl -s 2015-01-01 -e 2016-01-01 -o aapl.pickle

* What did you expect to happen? run succeeds.
* What happened instead?
[2017-12-10 08:07:22.311439] INFO: Loader: Cache at /Users/hjunlim/.zipline/data/SPY_benchmark.csv does not have data from 1990-01-02 00:00:00+00:00 to 2017-12-06 00:00:00+00:00.

[2017-12-10 08:07:22.311746] INFO: Loader: Downloading benchmark data for 'SPY' from 1989-12-29 00:00:00+00:00 to 2017-12-06 00:00:00+00:00
Traceback (most recent call last):
  File "/Users/hjunlim/Documents/virtualenvs/zipline/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/__main__.py", line 240, in run
    environ=os.environ,
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 132, in _run
    env = TradingEnvironment(asset_db_path=connstr, environ=environ)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/finance/trading.py", line 99, in __init__
    self.bm_symbol,
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/data/loader.py", line 166, in load_market_data
    environ,
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/data/loader.py", line 230, in ensure_benchmark_data
    last_date,
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/zipline/data/benchmarks.py", line 53, in get_benchmark_returns
    data = data['Close']
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/Users/hjunlim/Documents/virtualenvs/zipline/lib/python2.7/site-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: 'Close'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. create virtual env with python2.7
2. install zipline using pip
3. zipine ingest
4. run zipline run command as above.

## What steps have you taken to resolve this already?
I can not resolve the issue. Please help me how to kick start using zipline.

# Anything else?
Thank you.

Sincerely,
Hyungjun Lim

**Comment by freddiev4** [comment]
Should be fixed in the zipline master branch (see #2031)

**Comment by freddiev4** [comment]
Closing this as this should be fixed in the latest release of zipline. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If you're still experiencing issues, please reopen this or open a new issue 🙂
