### ISSUE TITLE
use data from local csv file

### ISSUE THREAD

**Issue by prathameshjoshi** [quantopian/zipline#2088]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

> * Operating System: Linux X1-Carbon 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> * Python Version: Python 2.7.13 / 3
> * Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
> * How did you install Zipline: pip
> * Python packages: `$ pip freeze`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I am running following code and using local csv file. but when i run the code i get following error. I want to use custom csv file. Please let me know what can i do. 

# Error
```
Traceback (most recent call last):
  File "bollingerbands.py", line 97, in <module>
    Strategy = BollingerBands()
  File "/usr/local/lib/python3.5/dist-packages/zipline/algorithm.py", line 273, in __init__
    self.trading_environment = TradingEnvironment()
  File "/usr/local/lib/python3.5/dist-packages/zipline/finance/trading.py", line 99, in __init__
    self.bm_symbol,
  File "/usr/local/lib/python3.5/dist-packages/zipline/data/loader.py", line 166, in load_market_data
    environ,
  File "/usr/local/lib/python3.5/dist-packages/zipline/data/loader.py", line 230, in ensure_benchmark_data
    last_date,
  File "/usr/local/lib/python3.5/dist-packages/zipline/data/benchmarks.py", line 50, in get_benchmark_returns
    last_date
  File "/usr/local/lib/python3.5/dist-packages/pandas_datareader/data.py", line 137, in DataReader
    session=session).read()
  File "/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py", line 181, in read
    params=self._get_params(self.symbols))
  File "/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py", line 79, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py", line 90, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/local/lib/python3.5/dist-packages/pandas_datareader/base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?enddate=Jan+19%2C+2018&output=csv&q=SPY&startdate=Dec+29%2C+1989
```

# Code
```
import pandas as pd
import locale
import matplotlib.pyplot as plt
from zipline.algorithm import TradingAlgorithm
import zipline.finance.trading as


from datetime import datetime, date
from pytz import timezone
import pytz
from dateutil.tz import tzutc
from dateutil.parser import parse
from zipline.finance.slippage import FixedSlippage
from zipline.finance.commission import PerShare, PerTrade


central = timezone('US/Central')
HOLDTIME = 5
locale.setlocale( locale.LC_ALL, 'en_US.UTF-8')
COMMISSION=0.005

def date_utc(s):
    return parse(s, tzinfos=tzutc)


class BollingerBands(TradingAlgorithm):

    def initialize(self):
        self.invested       = False

        self.trade_size=1000
        self.long = False
        self.short = False
        self.closed = False
        self.trading_day_counter = 0
        self.pct_stop = 0.025
        self.long_stop_price =  0.0
        self.short_stop_price=0.0
        self.target=0.05
        commission_cost = self.trade_size * COMMISSION
        self.set_slippage(FixedSlippage(spread=0.10))
        self.set_commission(PerTrade(cost=commission_cost))

    def handle_data(self, data):


        if data['Close'].price >= data['upper'].price and not self.invested:
            self.order('Close', self.trade_size)
            self.long_stop_price =  data['Open'].price - data['Open'].price * float(self.pct_stop)
            self.short_stop_price =  data['Open'].price + data['Open'].price * float(self.target)
            self.long = True
            self.closed=False
            self.invested = True
            self.trading_day_counter = 0
        if data['Close'].price <= data['lower'].price and not self.invested:
            self.short_stop_price =  data['Open'].price + data['Open'].price * float(self.pct_stop)
            self.long_stop_price =  data['Open'].price - data['Open'].price * float(self.target)
            self.order('Close', -self.trade_size)
            self.short = True
            self.closed=False
            self.invested = True
            self.trading_day_counter = 0
        if self.invested and (data['Close'].price <=  self.long_stop_price or data['Close'].price >=  self.short_stop_price): #or self.trading_day_counter == HOLDTIME):

            if self.long:
                self.order('Close', -self.trade_size)
            if self.short:
                self.order('Close', self.trade_size)

            self.closed=True
            self.long=False
            self.short=False
            self.invested=False


        self.trading_day_counter =  self.trading_day_counter +1
        self.record(Close=data['Close'].price,
                    upper=data['upper'].price,
                    lower=data['lower'].price,
                    long=self.long,
                    short=self.short,
                    holdtime=self.trading_day_counter,
                    closed_position=self.closed,
                    shares=self.trade_size)


if __name__ == '__main__':
    df=pd.read_csv('2M.csv', index_col=0, parse_dates=True, names=["Date", "Open", "High", "Low", "Close", "Volume", "col6", "dividend", "col8", "col9"]) # contains Date, Open, High, Low, Close, Volume


    df['avg'] = pd.rolling_mean(df['Close'], 21)
    df['std'] = pd.rolling_std(df['Close'], 21)
    df['upper'] = df['avg'] + 2 * df['std']
    df['lower'] = df['avg'] - 2 * df['std']
    df = df.dropna()

    # # # # init Strat Class
    Strategy = BollingerBands()
    # #print df

    # # # # # # Run Strategy
    results = Strategy.run(df)
    results['algorithm_returns'] = (1 + results.returns).cumprod()


    results.to_csv('output.csv')
    print (results['algorithm_returns'].tail(1)[0]*100)

```

**Comment by freddiev4** [comment]
Hi @prathameshjoshi the error is a known issue (see #1965) and should be fixed in the next zipline release.

You can install the *latest* zipline in one of two ways:

**Using Pip**:
```
git clone git@github.com:quantopian/zipline.git
pip install zipline/
```

Or 
```
conda create -n py35 python=3.5 # creates a Py35 conda env
conda install -c quantopian/label/ci -c quantopian zipline
```

**Comment by prathameshjoshi** [comment]
Thanks that works

**Comment by prathameshjoshi** [comment]
@freddiev4 Any idea about this error? from above same code. 
# Error
```
Traceback (most recent call last):
  File "bollingerbands.py", line 102, in <module>
    results = Strategy.run(df)
  File "/usr/local/lib/python3.5/dist-packages/zipline/algorithm.py", line 645, in run
    if data.major_axis.tz is None:
AttributeError: 'RangeIndex' object has no attribute 'tz'

```

**Comment by freddiev4** [comment]
That error says the index of your dataframe is not a DatetimeIndex. The default index type for a dataframe is a RangeIndex.

If it doesn't use a DatetimeIndex, then your algorithm has no time reference to when certain things occur.

Also, there's a bundle called csvdir that you can use to ingest custom csv data. It's not yet in the zipline docs but if you look here on GitHub in zipline/docs/source/bundles.rst you should see a short tutorial on how to do that.

**Comment by freddiev4** [comment]
Closing this as you should be able to do this in the latest release of zipline. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If there are any problems, please open a new issue 🙂
