### ISSUE TITLE
Quickstart documentation example crash

### ISSUE THREAD

**Issue by raffam** [quantopian/zipline#2094]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
Linux raffaele-GL753VD 4.14.13-041413-generic #201801101001 SMP Wed Jan 10 10:02:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Python Version: `$ python --version`
Python 3.5.4 :: Anaconda, Inc.

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Zipline: (`pip`, `conda`, or `other (please explain)`)

As suggested in #2083 

conda create -n py35 python=3.5
source activate py35
conda install -c quantopian/label/ci -c quantopian zipline

* Python packages: `$ pip freeze` or `$ conda list`
# packages in environment at /home/raffaele/anaconda3/envs/py35:
#
alembic                   0.7.7                    py35_0    quantopian
asn1crypto                0.24.0                   py35_0  
bcolz                     0.12.1              np111py35_0    quantopian
bottleneck                1.2.1            py35he1b16f1_0  
bzip2                     1.0.6                h6d464ef_2  
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2018.1.18                py35_0  
cffi                      1.11.4           py35h9745a5d_0  
chardet                   3.0.4            py35hb6e9ddf_1  
click                     6.7              py35h353a69f_0  
contextlib2               0.5.5            py35h6690dba_0  
cryptography              2.1.4            py35hbeb2da1_0  
cyordereddict             0.2.2                    py35_0    quantopian
cython                    0.27.3           py35h6cdc64b_0  
decorator                 4.2.1                    py35_0  
empyrical                 0.3.3                    py35_0    quantopian
hdf5                      1.10.1               h9caa474_1  
idna                      2.6              py35h8605a33_1  
intel-openmp              2018.0.0             hc7b2577_8  
intervaltree              2.1.0                    py35_0    quantopian
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                h9f7466a_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
logbook                   0.12.5                   py35_0    quantopian
lru-dict                  1.1.4                    py35_0    quantopian
lzo                       2.10                 h49e0be7_2  
mako                      1.0.7            py35h69899ea_0  
markupsafe                1.0              py35h4f4fcf6_1  
mkl                       2017.0.4             h4c4d0af_0  
multipledispatch          0.4.9            py35h2ff591a_0  
ncurses                   6.0                  h9df7e31_2  
networkx                  1.11             py35hf333c83_0  
numexpr                   2.6.2               np111py35_0  
numpy                     1.11.3                   py35_0  
openssl                   1.0.2n               hb7f436b_0  
pandas                    0.18.1              np111py35_0  
pandas-datareader         0.5.0                    py35_0  
patsy                     0.5.0                    py35_0  
pip                       9.0.1            py35h7e7da9d_4  
pycparser                 2.18             py35h61b3040_1  
pyopenssl                 17.5.0           py35h4f8b8c8_0  
pysocks                   1.6.7            py35h6aefbb0_1  
pytables                  3.4.2            py35hfa98db7_2  
python                    3.5.4               h417fded_24  
python-dateutil           2.6.1            py35h90d5b31_1  
pytz                      2017.3           py35hb13c558_0  
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py35hb9e6ad1_1  
requests-file             1.4.1                    py35_0  
requests-ftp              0.3.1                    py35_0  
scipy                     0.19.0              np111py35_0  
setuptools                38.4.0                   py35_0  
six                       1.11.0           py35h423b573_1  
sortedcontainers          1.4.4                    py35_0    quantopian/label/ci
sqlalchemy                1.2.1            py35h14c3975_0  
sqlite                    3.21.0               h1bed415_0  
statsmodels               0.8.0            py35haa9d50b_0  
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                    py35_0  
urllib3                   1.22             py35h2ab6e29_0  
wheel                     0.30.0           py35hd3883cf_1  
xz                        5.2.3                h55aa19d_2  
zipline                   1.1.1           np111py35_230_gfb735e76    quantopian/label/ci
zlib                      1.2.11               ha838bed_2  

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
For the example provided [here](http://www.zipline.io/index.html) to work

* What happened instead?
It crashed

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Run the example provided [here](http://www.zipline.io/index.html) as the link describes
2. `zipline run -f dual_moving_average.py --start 2011-1-1 --end 2012-1-1 -o dma.pickle`

## What steps have you taken to resolve this already?
It seems to work with different dates (for example, 2017-1-1 and 2018-1-1)
...

# Anything else?

ERROR LOG:
[2018-01-27 13:58:42.966171] WARNING: Loader: Refusing to download new benchmark data because a download succeeded at 2018-01-27 13:58:12.075496+00:00.
[2018-01-27 13:58:42.988076] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2018-01-27 13:58:22.091496+00:00.
Traceback (most recent call last):
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1395, in _has_valid_type
    error()
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1390, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [2011-10-10 00:00:00+00:00] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raffaele/anaconda3/envs/py35/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.1.1+230.gfb735e76', 'console_scripts', 'zipline')()
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/__main__.py", line 98, in _
    return f(*args, **kwargs)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/__main__.py", line 251, in run
    environ=os.environ,
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 186, in _run
    overwrite_sim_params=False,
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/algorithm.py", line 721, in run
    for perf in self.get_generator():
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/gens/tradesimulation.py", line 225, in transform
    handle_benchmark(normalize_date(dt))
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/gens/tradesimulation.py", line 181, in handle_benchmark
    benchmark_source.get_value(date)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/zipline/sources/benchmark_source.py", line 75, in get_value
    return self._precalculated_series.loc[dt]
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1296, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1466, in _getitem_axis
    self._has_valid_type(key, axis)
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1403, in _has_valid_type
    error()
  File "/home/raffaele/anaconda3/envs/py35/lib/python3.5/site-packages/pandas/core/indexing.py", line 1390, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [2011-10-10 00:00:00+00:00] is not in the [index]'

**Comment by freddiev4** [comment]
Hi @raffam this is because with IEX you can only get up to 5 years worth of data for a benchmark. So you can go as far back as 2013. There's a more permanent fix that addresses this that is currently a work in progress.

**Comment by freddiev4** [comment]
Closing this should be fixed in the latest release of zipline. You can see the release notes [here](http://www.zipline.io/releases.html#release-1-2-0) Feel free to update to 1.2.0 with either:

```
pip install -U zipline
```

or

```
conda update zipline -c quantopian
```

If there are any problems, please open a new issue 🙂
