### ISSUE TITLE
Insufficient data to compute Pipeline

### ISSUE THREAD

**Issue by carsonpo** [quantopian/zipline#2153]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: MacOS 10.12 Sierra
* Python Version: 2.7.14
* How did you install Zipline: pip and conda

Now that you know a little about me, let me tell you about the issue I am
having:

```
Traceback (most recent call last):
  File "/Users/carson/mlTechnicalAnalysis/quant.py", line 255, in <module>
    extensions=['keras','h5py'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 398, in run_algorithm
    environ=environ,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/utils/run_algo.py", line 208, in _run
    overwrite_sim_params=False,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/algorithm.py", line 730, in run
    for perf in self.get_generator():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/algorithm.py", line 617, in get_generator
    return self._create_generator(self.sim_params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/algorithm.py", line 585, in _create_generator
    self.initialize(*self.initialize_args, **self.initialize_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/algorithm.py", line 449, in initialize
    self._initialize(self, *args, **kwargs)
  File "/Users/carson/mlTechnicalAnalysis/quant.py", line 160, in initialize
    timezone(pd.to_datetime('2012-01-18 20:0:0', utc=True)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/pipeline/engine.py", line 293, in run_pipeline
    root_mask = self._compute_root_mask(start_date, end_date, extra_rows)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zipline/pipeline/engine.py", line 372, in _compute_root_mask
    lookback_length=extra_rows,
NoFurtherDataError: 
Insufficient data to compute Pipeline:

lookback window started at 2012-01-03 00:00:00+00:00
earliest known date was 2012-01-03 00:00:00+00:00
1 extra rows of data were required

```

Before, I used `bundle_data.equity_daily_bar_reader` and set the two start times one day apart, and then it all ran smoothly. Now I need more granular time info so I need minutes, but it keeps failing because it says it needs one extra row.

The number of "extra rows" needed changes with the window length in the `AverageDollarVolume` part in my `make_pipeline` function, as shown below. The number in the error is always one less than whatever the window length is, or if the length is one, the error also shows one.

I've tried many, many different combos of start dates, like one day, one hour, one minute, one second, two of each of those, and flipping them forward or backward. None of this resolves the issue.

For more info, here's my make_pipeline function.

```
def make_pipeline(context):
    pipe = Pipeline()
    base_universe = AllPresent
    dollar_volume = AverageDollarVolume(window_length=1)
    high_dollar_volume = dollar_volume.percentile_between(98, 100)
    
    close_day_before_yeseterday = ValueDaybeforeYesterday(inputs = [USEquityPricing.close])
    volume_day_before_yeseterday = ValueDaybeforeYesterday(inputs = [USEquityPricing.volume])

    pipe.add(close_day_before_yeseterday, "close_day_before_yeseterday")
    
    return_change_mean = ChangeAverage(inputs = [USEquityPricing.close], window_length = 5)
    volume_change_mean = ChangeAverage(inputs = [USEquityPricing.volume], window_length = 5)
    
    
    my_screen = (high_dollar_volume)  #& (return_change_mean < 0)
    pipe.set_screen(my_screen)
    return pipe
```

and here's my Simple Pipeline Engine and run_pipeline

```
def initialize(context):
    
    cal = bundle_data.equity_minute_bar_reader.trading_calendar.all_sessions
    cal2 = cal[(cal >= "2012-01-03") & (cal <= '2012-01-18')]
    print(cal2)

    spe = SimplePipelineEngine(get_loader=choose_loader,
                               calendar=cal2,
                               asset_finder=bundle_data.asset_finder)

  
    context.output = spe.run_pipeline(make_pipeline(context),
                                     pd.to_datetime('2012-01-03 00:00:00', utc=True),
                                     timezone(pd.to_datetime('2012-01-18 20:0:0', utc=True)))
```

Thanks so much for your help!!
Sincerely,
`$ whoami`

**Comment by freddiev4** [comment]
Going to close this issue as we chatted via email.

There were a couple issues here:
- Using `SimplePipelineEngine` is not what you want to do here; you can use `attach_pipeline` and `pipeline_output` like the [Momentum Example](https://github.com/quantopian/zipline/blob/master/zipline/examples/momentum_pipeline.py)
- Once that issue was fixed, there were spelling mistakes that resulted in an `KeyError`coming from pandas
- Then the last thing was that there is no minutely data in the default `quandl` bundle; so one would need to get their own minutely data source, ingest that, and then use it in their Pipeline

Closing this.
