### ISSUE TITLE
No module named 'zipline'

### ISSUE THREAD

**Issue by bconstructive** [quantopian/zipline#2170]
Dear Zipline Maintainers,

# Environment

* Operating System: (Windows 7`)
* Python Version: 3.5.5 (in Anaconda/env_zipline folder).  3.6.4 in Anaconda folder.
* Installed Zipline using conda, as suggested on http://www.zipline.io/install.html#installing-with-conda

# Description of Issue

Hello.
When I attempt to "import zipline" or do something like 
from zipline.api import order, record, symbol 
in a notebook or script I receive: 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ab8bff6e5ffb> in <module>()
----> 1 import zipline

ModuleNotFoundError: No module named 'zipline'

Would you kindly help with solving this issue?

I really appreciate your help

Sincerely,
Bryan

**Comment by freddiev4** [comment]
Hi @bconstructive thanks for opening the issue. Can you post the output of running:

```
conda list
```

**Comment by bconstructive** [comment]
Thank you for getting back to me. I really appreciate the help.
Here is my output from conda list.


(base) C:\Users\Administrator>cd anaconda3

(base) C:\Users\Administrator\Anaconda3>conda list
# packages in environment at C:\Users\Administrator\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
_nb_ext_conf              0.4.0                    py36_1
alabaster                 0.7.10           py36hcd07829_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.14                   py36_0
anaconda-navigator        1.8.4                    py36_0
anaconda-project          0.8.2            py36hfad2e28_0
asn1crypto                0.24.0                   py36_0
astroid                   1.6.1                    py36_0
astropy                   2.0.3            py36hfa6e2cd_0
attrs                     17.4.0                   py36_0
awscli                    1.15.4                    <pip>
babel                     2.5.3                    py36_0
backports                 1.0              py36h81696a8_1
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2
bcolz                     1.2.1            py36h830ac7b_0    anaconda
beautifulsoup4            4.6.0            py36hd4cc5e8_1
bitarray                  0.8.1            py36hfa6e2cd_1
bkcharts                  0.2              py36h7e685f7_0
blaze                     0.11.3           py36h8a29ca5_0
bleach                    2.1.2                    py36_0
bokeh                     0.12.13          py36h047fa9f_0
boto                      2.48.0           py36h1a776d2_1
botocore                  1.10.4                    <pip>
bottleneck                1.2.1            py36hd119dfa_0
bzip2                     1.0.6                    vc14_3  [vc14]  anaconda
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py36_0
cffi                      1.11.4           py36hfa6e2cd_0
chardet                   3.0.4            py36h420ce6e_1
click                     6.7              py36hec8c647_0
cliff                     2.8.1                     <pip>
cloudpickle               0.5.2                    py36_1
clyent                    1.2.2            py36hb10d595_1
cmd2                      0.8.5                     <pip>
colorama                  0.3.7                     <pip>
colorama                  0.3.9            py36h029ae33_0
comtypes                  1.1.4                    py36_0
conda                     4.5.2                    py36_0
conda-build               3.4.1                    py36_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h065de53_0
configparser              3.5.0                     <pip>
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.1.4            py36he1d7878_0
cssselect                 1.0.3                     <pip>
cuda80                    1.0                  h205658b_0    peterjc123
curl                      7.55.1           vc14hdaba4a4_3  [vc14]  anaconda
cycler                    0.10.0           py36h009560c_0
cython                    0.27.3           py36h22f4c84_0
cytoolz                   0.9.0            py36hfa6e2cd_0
dask                      0.16.1                   py36_0
dask-core                 0.16.1                   py36_0
datashape                 0.5.4            py36h5770b85_0
decorator                 4.2.1                    py36_0
distributed               1.20.2                   py36_0
docrepr                   0.1.1                     <pip>
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3            py36hfd66bb0_2
environment-kernels       1.1.1                     <pip>
et_xmlfile                1.0.1            py36h3d2d736_0
fastcache                 1.0.2            py36hfa6e2cd_2
feather-format            0.4.0                     <pip>
filelock                  2.0.13           py36h20000bf_0
flask                     0.12.2           py36h98b5e8f_0
flask-cors                3.0.3            py36h8a3855d_0
freetype                  2.8              vc14h17c9bdf_0  [vc14]  anaconda
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py36h342a76c_0
glob2                     0.6              py36hdf76b57_0
graphviz                  0.8.2                     <pip>
greenlet                  0.4.12           py36ha00ad21_0
h5py                      2.7.1            py36he54a1c3_0
hdf5                      1.10.1           vc14hb361328_0  [vc14]  anaconda
heapdict                  1.0.0                    py36_2
html5lib                  1.0.1            py36h047fa9f_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      2.6              py36h148d497_1
imageio                   2.2.0            py36had6c2d2_0
imagesize                 0.7.1            py36he29f638_0
intel-openmp              2018.0.0             hd92c6cd_8
ipykernel                 4.8.2                    py36_0
ipython                   6.2.1            py36h9cf0123_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.1.1                    py36_0
isort                     4.2.15           py36h6198cc5_0
isoweek                   1.3.3                     <pip>
itsdangerous              0.24             py36hb6c5a24_1
jdcal                     1.3              py36h64a5255_0
jedi                      0.11.1                   py36_0
jinja2                    2.10             py36h292fed1_0
jmespath                  0.9.3                     <pip>
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0                    py36_4
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.5.0                     <pip>
jupyter-highlight-selected-word 0.2.0                     <pip>
jupyter-latex-envs        1.4.4                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.2                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.31.4                   py36_0
jupyterlab_launcher       0.10.2                   py36_0
kaggle-cli                0.12.13                   <pip>
lazy-object-proxy         1.3.1            py36hd1c21d2_0
libcurl                   7.58.0               h7602738_0
libiconv                  1.15             vc14h29686d3_5  [vc14]  anaconda
libpng                    1.6.32           vc14h5163883_3  [vc14]  anaconda
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]  anaconda
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]  anaconda
libxml2                   2.9.4            vc14h8fd0f11_5  [vc14]  anaconda
libxslt                   1.1.29           vc14hf85b8d4_5  [vc14]  anaconda
llvmlite                  0.21.0           py36he0b0552_0
locket                    0.2.0            py36hfed976d_1
lxml                      4.1.1            py36he0adb16_0    anaconda
lxml                      4.0.0                     <pip>
lzo                       2.10             vc14h0a64fa6_1  [vc14]  anaconda
markupsafe                1.0              py36h0e26971_1
matplotlib                2.1.2            py36h016c42a_0
mccabe                    0.6.1            py36hb41005a_1
MechanicalSoup            0.8.0                     <pip>
menuinst                  1.4.11           py36hfa6e2cd_0
mistune                   0.8.3                    py36_0
mizani                    0.4.6                     <pip>
mkl                       2018.0.2                      1
mkl-service               1.1.2            py36h57e144c_4
mpmath                    1.0.0            py36hacc8adf_2
msgpack-python            0.5.1            py36he980bc4_0
multipledispatch          0.4.9            py36he44c36e_0
navigator-updater         0.1.0            py36h8a7b86b_0
nb_anacondacloud          1.4.0                    py36_0
nb_conda                  2.2.0                    py36_0
nb_conda_kernels          2.1.0                    py36_0
nbconvert                 5.3.1            py36h8dc0fde_0
nbformat                  4.4.0            py36h3a5bc1b_0
nbpresent                 3.0.2                    py36_0
networkx                  2.1                      py36_0
nltk                      3.2.5            py36h76d52bb_0
nose                      1.3.7            py36h1c3779e_2
notebook                  5.4.1                    py36_0
numba                     0.36.2          np114py36h12cb543_0
numexpr                   2.6.4            py36h30784b8_0
numpy                     1.14.0           py36h4a99626_1
numpydoc                  0.7.0            py36ha25429e_0
odo                       0.5.1            py36h7560279_0
olefile                   0.45.1                   py36_0
opencv-python             3.4.0.12                  <pip>
openpyxl                  2.4.10                   py36_0
openssl                   1.0.2o               h8ea7d77_0
packaging                 16.8             py36ha0986f6_1
palettable                3.1.0                     <pip>
pandas                    0.22.0           py36h6538335_0
pandas-summary            0.0.41                    <pip>
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36h3ef6317_1
parso                     0.1.1            py36hae3edee_0
partd                     0.3.8            py36hc8e763b_0
path.py                   10.5             py36h2b94a8f_0
pathlib2                  2.3.0            py36h7bfb78b_0
patsy                     0.5.0                    py36_0
pbr                       4.0.2                     <pip>
PDPbox                    0.1                       <pip>
pep8                      1.7.1                    py36_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    4.2.1            py36hdb25ab2_0    anaconda
pip                       10.0.0                    <pip>
pip                       9.0.1            py36h226ae91_4
pkginfo                   1.4.1            py36hb0f9cfa_1
plotnine                  0.3.0                     <pip>
pluggy                    0.6.0            py36hc7daf1e_0
ply                       3.10             py36h1211beb_0
prettytable               0.7.2                     <pip>
progressbar2              3.34.3                    <pip>
prompt_toolkit            1.0.15           py36h60b8f86_0
psutil                    5.4.3            py36hfa6e2cd_0
py                        1.5.2            py36hbcfbabc_0
pyarrow                   0.9.0                     <pip>
pyasn1                    0.4.2                     <pip>
pycodestyle               2.3.1            py36h7cc55cd_0
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pycrypto                  2.6.1            py36hfa6e2cd_7
pycurl                    7.43.0.1         py36h74b6da3_0
pyflakes                  1.6.0            py36h0b975d6_0
pygments                  2.2.0            py36hb010967_0
pylint                    1.8.2                    py36_0
pyodbc                    4.0.22           py36h6538335_0
pyopenssl                 17.5.0           py36h5b7d817_0
pyparsing                 2.2.0            py36h785a196_1
pyperclip                 1.6.0                     <pip>
pyqt                      5.6.0            py36hb5ed885_5
pyreadline                2.1                       <pip>
pysocks                   1.6.7            py36h698d350_1
pytables                  3.4.2            py36h71138e3_2
pytest                    3.3.2                    py36_0
python                    3.6.4                h6538335_1
python-dateutil           2.6.1            py36h509ddcb_1
python-utils              2.3.0                     <pip>
pytorch                   0.3.1           py36_cuda80_cudnn6he774522_2    peterj
c123
pytorch-cpu               0.3.1           py36_cpuhe774522_2    peterjc123
pytorch_legacy            0.3.1           py36_cuda80_cudnn7he774522_2    peterj
c123
pytz                      2017.3           py36h1d3fa6b_0
pywavelets                0.5.2            py36hc649158_0
pywin32                   222              py36hfa6e2cd_0
pywinpty                  0.5              py36h6538335_1
pyyaml                    3.12             py36h1d1928f_1
pyzmq                     16.0.3           py36he714bf5_0
qt                        5.6.2           vc14h6f8c307_12  [vc14]  anaconda
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.3.1            py36hb8717c5_0
requests                  2.18.4           py36h4371aae_1
rope                      0.10.7           py36had63a69_0
rsa                       3.4.2                     <pip>
ruamel_yaml               0.15.35          py36hfa6e2cd_1
s3transfer                0.1.13                    <pip>
scikit-image              0.13.1           py36hfa6e2cd_1
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
seaborn                   0.8.1            py36h9b69545_0
send2trash                1.4.2                    py36_0
setuptools                38.4.0                   py36_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h9c25514_2
six                       1.11.0           py36h4db2310_1
sklearn-pandas            1.6.0                     <pip>
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         0.5.3            py36hbefa0ab_0
sortedcontainers          1.5.9                    py36_0
sphinx                    1.6.6                    py36_0
sphinxcontrib             1.0              py36hbbac3d2_1
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1
spyder                    3.2.8                    py36_0
sqlalchemy                1.2.1            py36hfa6e2cd_0
sqlite                    3.20.1           vc14h7ce8c62_1  [vc14]  anaconda
statsmodels               0.8.0            py36h6189b4c_0
stevedore                 1.28.0                    <pip>
sympy                     1.1.1            py36h96708e0_0
tblib                     1.3.2            py36h30f5020_0
terminado                 0.8.1                    py36_1
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.7            vc14hb68737d_1  [vc14]  anaconda
toolz                     0.9.0                    py36_0
torchtext                 0.2.3                     <pip>
tornado                   4.5.3                    py36_0
tqdm                      4.23.0                    <pip>
traitlets                 4.3.2            py36h096827d_0
typing                    3.6.2            py36hb035bda_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.22             py36h276f60a_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1            py36h67c50ae_1
werkzeug                  0.14.1                   py36_0
wheel                     0.30.0           py36h6c3ec14_1
widgetsnbextension        3.1.0                    py36_0
win_inet_pton             1.0.1            py36he67d7fd_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py36he5f5981_0
xlrd                      1.1.0            py36h1cb58dc_1
xlsxwriter                1.0.2            py36hf723b7d_0
xlwings                   0.11.5                   py36_0
xlwt                      1.3.0            py36h1a4751e_0
yaml                      0.1.7            vc14hb31d195_1  [vc14]  anaconda
zict                      0.1.3            py36h2d8e73e_0
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda

Thank you,
Bryan

**Comment by bconstructive** [comment]
Not sure if it matters, but my zipline is installed here.
C:\Users\Administrator\Anaconda3\envs\env_zipline
I followed the installation instructions and it wound up there.

**Comment by freddiev4** [comment]
Hmm.. I can't see your `zipline` installation in that list.

How about running: `conda list -n env_zipline`? This will list out all of the packages installed in your conda env called `env_zipline`.

Also, if you run `source activate env_zipline` and then run `python -c 'import zipline;print(zipline.__version__)'` from your Command Prompt, what do you get as output?

**Comment by bconstructive** [comment]
Hi. Here is the output from those instructions. Please note, it appears that using single quotes in the last request threw an error. So, I replaced them double quotes. If that's wrong please let me know and I'll retry.
Thank you


(base) C:\Users\Administrator>cd anaconda3

(base) C:\Users\Administrator\Anaconda3>conda list -n env_zipline
# packages in environment at C:\Users\Administrator\Anaconda3\envs\env_zipline:
#
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_0
backcall                  0.1.0                    py35_0
bcolz                     0.12.1              np111py35_0    Quantopian
bleach                    2.1.3                    py35_0
blosc                     1.14.3               he51fdeb_0
bottleneck                1.2.1            py35h8a3671c_0
bzip2                     1.0.6                hbe05fcf_4
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py35_0
cffi                      1.11.5           py35h945400d_0
chardet                   3.0.4            py35h177e1b7_1
click                     6.7              py35h10df73f_0
colorama                  0.3.9            py35h32a752f_0
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.2.2            py35hfa6e2cd_0
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.2           py35hfa6e2cd_0
decorator                 4.3.0                    py35_0
empyrical                 0.4.2                    py35_0    Quantopian
entrypoints               0.2.3            py35hb91ced9_2
hdf5                      1.10.1               h98b8871_1
html5lib                  1.0.1            py35h047fa9f_0
icc_rt                    2017.0.4             h97af966_0
idna                      2.6              py35h8dcb9ae_1
intel-openmp              2018.0.0                      8
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 4.8.2                    py35_0
ipython                   6.3.1                    py35_0
ipython_genutils          0.2.0            py35ha709e79_0
jedi                      0.12.0                   py35_1
jinja2                    2.10             py35hdf652bb_0
jsonschema                2.6.0            py35h27d56d3_0
jupyter_client            5.2.3                    py35_0
jupyter_core              4.4.0            py35h629ba7f_0
libsodium                 1.0.16               h9d3ae62_0
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7            py35ha146b58_0
markupsafe                1.0              py35hc253e08_1
mistune                   0.8.3            py35hfa6e2cd_1
mkl                       2018.0.2                      1
msys2-conda-epoch         20160418                      1
multipledispatch          0.5.0                    py35_0
nbconvert                 5.3.1            py35h98d6c46_0
nbformat                  4.4.0            py35h908c9d9_0
networkx                  1.11             py35h097edc8_0
notebook                  5.4.1                    py35_0
numexpr                   2.6.4            py35hb78e28a_0
numpy                     1.11.3           py35h4a99626_4
openssl                   1.0.2o               h8ea7d77_0
pandas                    0.18.1              np111py35_0
pandas-datareader         0.5.0                    py35_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py35h978f723_1
parso                     0.2.0                    py35_0
patsy                     0.5.0                    py35_0
pickleshare               0.7.4            py35h2f9f535_0
pip                       10.0.1                   py35_0
prompt_toolkit            1.0.15           py35h89c7cb4_0
pycparser                 2.18             py35h15a15da_1
pygments                  2.2.0            py35h24c0941_0
pyopenssl                 17.5.0           py35h75c5b16_0
pysocks                   1.6.8                    py35_0
pytables                  3.4.3            py35he6f6034_0
python                    3.5.5                h0c2934d_2
python-dateutil           2.7.2                    py35_0
pytz                      2018.4                   py35_0
pywinpty                  0.5.1                    py35_0
pyzmq                     17.0.0           py35hfa6e2cd_1
requests                  2.18.4           py35h54a615f_1
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     1.0.1            py35hce232c7_0
send2trash                1.5.0                    py35_0
setuptools                39.1.0                   py35_0
simplegeneric             0.8.1                    py35_2
six                       1.11.0           py35hc1da2df_1
snappy                    1.1.7                h777316e_3
sortedcontainers          1.5.10                   py35_0
sqlalchemy                1.2.7            py35ha85dd04_0
statsmodels               0.8.0            py35hfa6034c_0
terminado                 0.8.1                    py35_1
testpath                  0.3.1            py35h06cf69e_0
toolz                     0.9.0                    py35_0
tornado                   5.0.2                    py35_0
traitlets                 4.3.2            py35h09b975b_0
urllib3                   1.22             py35h8cc84eb_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py35h6e80d8a_0
webencodings              0.5.1            py35h5d527fb_1
wheel                     0.31.0                   py35_0
win_inet_pton             1.0.1            py35hbef1270_1
win_unicode_console       0.5              py35h56988b5_0
wincertstore              0.2              py35hfebbdb8_0
winpty                    0.4.3                         4
zeromq                    4.2.5                hc6251cf_0
zipline                   1.2.0               np111py35_0    Quantopian
zlib                      1.2.11               h8395fce_2

(base) C:\Users\Administrator\Anaconda3>



(base) C:\Users\Administrator>cd anaconda3

(base) C:\Users\Administrator\Anaconda3>conda activate env_zipline

(env_zipline) C:\Users\Administrator\Anaconda3>python -c 'import zipline;print(z
ipline.__version__)'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal

(env_zipline) C:\Users\Administrator\Anaconda3>python -c "import zipline;print(z
ipline.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'zipline'

(env_zipline) C:\Users\Administrator\Anaconda3>

**Comment by freddiev4** [comment]
OK. So it does look like `zipline` in installed in your conda env, which leads me to believe there is an issue with some environment variables (IIRC my memory of how Windows works with Anaconda installations).

Can you try, from your CP: 
- Running `echo $PATH` and post the output of anything that might say `Anaconda` or `Python`
- Running `python` and then followed by:
   ```
   import sys
   sys.executable
   sys.path
   ```

**Comment by bconstructive** [comment]
Using echo %path% I see these outputs that contain anaconda or python.

C:\Users\Administrator\Anaconda3;C:\Users\Administrator\Anaconda3\Library\mingw-
w64\bin;C:\Users\Administrator\Anaconda3\Library\usr\bin;C:\Users\Administrator\
Anaconda3\Library\bin;C:\Users\Administrator\Anaconda3\Scripts;C:\Users\Administ
rator\Anaconda3\bin
c:\Python27\;c:\Python27\Scripts\;C:\Program Files\gs\gs9.22\bin;C:\Progr
am Files\gs\gs9.22\lib;C:\Program Files\Git\cmd;C:\Users\Administrator\AppData\L
ocal\Programs\Python\Python36\Scripts\;C:\Users\Administrator\AppData\Local\Prog
rams\Python\Python36\

And by running python with those instructions this is what I get.

(base) C:\Users\Administrator>python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.
1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'C:\\Users\\Administrator\\Anaconda3\\python.exe'
>>> sys.path
['', 'C:\\Users\\Administrator\\Anaconda3\\python36.zip', 'C:\\Users\\Administra
tor\\Anaconda3\\DLLs', 'C:\\Users\\Administrator\\Anaconda3\\lib', 'C:\\Users\\A
dministrator\\Anaconda3', 'C:\\Users\\Administrator\\Anaconda3\\lib\\site-packag
es', 'C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\torchvision-0.1.8
-py3.6.egg', 'C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\win32', '
C:\\Users\\Administrator\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users
\\Administrator\\Anaconda3\\lib\\site-packages\\Pythonwin']
>>>

Thanks again.

Bryan

**Comment by bconstructive** [comment]
Hi swappro,
I'm the one who asked the original question on this tread. Will try to help
if possible.
I recently got zipline running on my Windows machine by following the
instructions here.
https://www.zipline.io/install.html#installing-with-conda
Are these the instructions you followed?
What version of Pyhton are you using in the zipline env? I believe zipline
is compatible with 2.7 and 3.5 as indicated in the instructions linked
above. I say that, because in your message above you appear to be using
python3.4?
If you can't find zipline installed in your zipline environment by CDind
into that folder and entering 'conda
 list', then perhaps you haven't activated the zipline env and installed
zipline yet. Maybe you created the environment, but still need install
zipline.
That would look like:

conda activate the_name_of_your_zipline_env

conda install -c Quantopian zipline

Give that a try and see if it works.
Let me know.

Bryan
