### ISSUE TITLE
Push new conda build for zipline

### ISSUE THREAD

**Issue by kastman** [quantopian/zipline#2186]
Hi all,

When doing a fresh `conda create -n zipline && conda install -c Quantopian zipline` to create a new conda envirnoment and install the most recent zipline (`1.2.0`) into it, it seems that python-datareader 0.6 is still being installed (despite being pointed out in the gitter chat and fixed). Although it does look like this has been fixed in `etc/requirements.txt` and presumably the upstream conda bundle, I suspect that [introspecting the build number from git in `conda/zipline/meta.yaml`](https://github.com/quantopian/zipline/blob/99d65351e2ca763e5b7ea7372f8157a97c79b1a0/conda/zipline/meta.yaml#L8
) is failing to bump the build correctly, causing the older conda package to be installed, currently for me `np111py35_0`. 
This manifests in an odd package / version mismatch when trying to run the cli:

```
(zipline) $ zipline -h
Traceback (most recent call last):
  File "/Users/kastman/miniconda/envs/zipline/bin/zipline", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/kastman/miniconda/envs/zipline/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/Users/kastman/miniconda/envs/zipline/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/Users/kastman/miniconda/envs/zipline/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/kastman/miniconda/envs/zipline/lib/python3.5/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/kastman/miniconda/envs/zipline/lib/python3.5/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/kastman/miniconda/envs/zipline/lib/python3.5/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lxml' distribution was not found and is required by pandas-datareader
```
I suspect all you have to do is bump the build and push to binstar / the quantopian conda channel again (or maybe even just push again already if that was missed) but I just wanted to point out the install is currently breaking. Thanks for your work on open-sourcing this useful tool,

**Comment by freddiev4** [comment]
I think you should be able to conda install the latest version (1.3.0) without seeing this error

**Comment by kastman** [comment]
Hi @freddiev4  - just tried this again and still have version `0.6.0` of `pandas-datareader` getting installed, which gives exactly the same error as above. Downgrading with `conda install pandas-datareader==0.2.1` after install does successfully work.
