### ISSUE TITLE
Legitimate missing data for custom bundles

### ISSUE THREAD

**Issue by veeenu** [quantopian/zipline#2195]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 7)
* Python Version: 3.5.5 Anaconda
* Python Bitness: 64
* How did you install Zipline: Conda
* Python packages:
```# Name                    Version                   Build  Channel
_nb_ext_conf              0.4.0                    py35_1
alembic                   0.7.7                    py35_0    quantopian
anaconda-client           1.6.14                   py35_0
asn1crypto                0.24.0                   py35_0
astroid                   1.6.3                    py35_0
backcall                  0.1.0                    py35_0
bcolz                     0.12.1              np111py35_0    quantopian
bleach                    2.1.3                    py35_0
blosc                     1.14.3               he51fdeb_0
bottleneck                1.2.1            py35h8a3671c_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py35_0
cffi                      1.11.5           py35h945400d_0
chardet                   3.0.4            py35h177e1b7_1
click                     6.7              py35h10df73f_0
clyent                    1.2.2            py35h3cd9751_1
colorama                  0.3.9            py35h32a752f_0
contextlib2               0.5.5            py35h0a97e54_0
cryptography              2.2.2            py35hfa6e2cd_0
cyordereddict             0.2.2                    py35_0    quantopian
cython                    0.28.2           py35hfa6e2cd_0
decorator                 4.3.0                    py35_0
empyrical                 0.4.2                    py35_0    quantopian
entrypoints               0.2.3            py35hb91ced9_2
hdf5                      1.10.2               hac2f561_1
html5lib                  1.0.1            py35h047fa9f_0
icc_rt                    2017.0.4             h97af966_0
idna                      2.6              py35h8dcb9ae_1
intel-openmp              2018.0.0                      8
intervaltree              2.1.0                    py35_0    quantopian
ipykernel                 4.8.2                    py35_0
ipython                   6.4.0                    py35_0
ipython_genutils          0.2.0            py35ha709e79_0
ipywidgets                7.2.1                    py35_0
isort                     4.3.4                    py35_0
jedi                      0.12.0                   py35_1
jinja2                    2.10             py35hdf652bb_0
jsonschema                2.6.0            py35h27d56d3_0
jupyter_client            5.2.3                    py35_0
jupyter_core              4.4.0            py35h629ba7f_0
lazy-object-proxy         1.3.1            py35he996729_0
libsodium                 1.0.16               h9d3ae62_0
logbook                   0.12.5                   py35_0    quantopian
lru-dict                  1.1.4                    py35_0    quantopian
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7            py35ha146b58_0
markupsafe                1.0              py35hc253e08_1
mccabe                    0.6.1            py35hcf31250_1
mistune                   0.8.3            py35hfa6e2cd_1
mkl                       2018.0.2                      1
msys2-conda-epoch         20160418                      1
multipledispatch          0.5.0                    py35_0
nb_anacondacloud          1.4.0                    py35_0
nb_conda                  2.2.0                    py35_0
nb_conda_kernels          2.1.0                    py35_0
nbconvert                 5.3.1            py35h98d6c46_0
nbformat                  4.4.0            py35h908c9d9_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11             py35h097edc8_0
notebook                  5.5.0                    py35_0
numexpr                   2.6.5            py35hcd2f87e_0
numpy                     1.11.3           py35h4a99626_4
openssl                   1.0.2o               h8ea7d77_0
pandas                    0.18.1              np111py35_0
pandas-datareader         0.5.0                    py35_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py35h978f723_1
parso                     0.2.0                    py35_0
patsy                     0.5.0                    py35_0
pickleshare               0.7.4            py35h2f9f535_0
pip                       10.0.1                   py35_0
prompt_toolkit            1.0.15           py35h89c7cb4_0
pycparser                 2.18             py35h15a15da_1
pygments                  2.2.0            py35h24c0941_0
pylint                    1.8.4                    py35_0
pyopenssl                 18.0.0                   py35_0
pysocks                   1.6.8                    py35_0
pytables                  3.4.3            py35he6f6034_1
python                    3.5.5                h0c2934d_2
python-dateutil           2.7.3                    py35_0
pytz                      2018.4                   py35_0
pywinpty                  0.5.1                    py35_0
pyyaml                    3.12             py35h4bf9689_1
pyzmq                     17.0.0           py35hfa6e2cd_1
requests                  2.18.4           py35h54a615f_1
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     1.1.0            py35h672f292_0
send2trash                1.5.0                    py35_0
setuptools                39.1.0                   py35_0
simplegeneric             0.8.1                    py35_2
six                       1.11.0           py35hc1da2df_1
snappy                    1.1.7                h777316e_3
sortedcontainers          1.5.10                   py35_0
sqlalchemy                1.2.7            py35ha85dd04_0
statsmodels               0.9.0            py35h452e1ab_0
terminado                 0.8.1                    py35_1
testpath                  0.3.1            py35h06cf69e_0
toolz                     0.9.0                    py35_0
tornado                   5.0.2                    py35_0
tqdm                      4.23.4                    <pip>
traitlets                 4.3.2            py35h09b975b_0
urllib3                   1.22             py35h8cc84eb_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py35h6e80d8a_0
webencodings              0.5.1            py35h5d527fb_1
wheel                     0.31.1                   py35_0
widgetsnbextension        3.2.1                    py35_0
win_inet_pton             1.0.1            py35hbef1270_1
win_unicode_console       0.5              py35h56988b5_0
wincertstore              0.2              py35hfebbdb8_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py35h54666f7_0
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                hc6251cf_0
zipline                   1.2.0               np111py35_0    quantopian
zlib                      1.2.11               h8395fce_2
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I am building a bundle out of data I have on an in-house web service. This data (from the SPX) contains legitimate gaps for a number of stocks which weren't traded on a number of dates. I would expect Zipline to import the data and fill the gaps (either with NaNs or filling methods)
* What happened instead?
When I run
`zipline ingest -b mybundle` I receive this error:
```
AssertionError: Got 1238 rows for daily bars table with first day=2012-05-01, last day=2017-04-03, expected 1239 rows.
Missing sessions: [Timestamp('2016-04-13 00:00:00+0000', tz='UTC')]
Extra sessions: []
```
and the process halts. The assertion is correct, but the data (missing that session) is also correct. I see it should also be handled properly as of this pull request: https://github.com/quantopian/zipline/pull/1778

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

This is the ingest function I built:
```
  # "API" and "assets" are defined globally
  def ingest(environ, asset_db_writer, minute_bar_writer, daily_bar_writer, adjustment_writer, calendar, start_session, end_session, cache, show_progress, output_dir):
    
    symbols = sorted([a['ticker'] for a in assets])
    dtype = [('start_date', 'datetime64[ns]'),
              ('end_date', 'datetime64[ns]'),
              ('auto_close_date', 'datetime64[ns]'),
              ('symbol', 'object')]
    metadata = pd.DataFrame(np.empty(len(symbols), dtype=dtype))

    def write_fn():
      for idx, asset in enumerate(assets):
        aid, tkr = asset['id'], asset['ticker']
        print(tkr)
        # Replace the following line with, say, a simple pd.read_csv() of a timeseries with legit session gaps, as API() connects to my service and can't be used to reproduce
        ts = requests.get(API('asset/{:s}/prices/eod'.format(aid))).json()
        df = pd.DataFrame(ts).set_index('time')[['open', 'high', 'low', 'close', 'volume']]

        start_date = pd.to_datetime(df.index[0])
        end_date = pd.to_datetime(df.index[-1])
        metadata.iloc[idx] = start_date, end_date, end_date + pd.Timedelta(days=1), tkr
        yield idx, df
    
    daily_bar_writer.write(write_fn(), show_progress=True)
    asset_db_writer.write(equities=metadata)
```
and this is the `register()` call:
```
register(
  'mybundle',
  ingest,
  calendar_name='NYSE'
)
```

## What steps have you taken to resolve this already?

I tried looking into Zipline's source code and through the issues/pull requests to find out whether I made a mistake in my implementation but couldn't find anything. Thanks for your help, let me know if you need further information.

Sincerely,
Andrea Venuta

**Comment by yankees714** [comment]
Hi @veeenu - apologies for the confusion. I looked into this, and the description in #1778 is misleading. Looks like we may have started with a different intention, but in the change we actually merged, the daily bar writer expects no gaps in the data (i.e. they won't be filled).

If you expect gaps, you probably just want to reindex against the expected trading sessions to fill with nans. You should be able to do something like:
```python
from zipline.utils.calendars import get_calendar

# Ensure the df is indexed by UTC timestamps
df = df.set_index(df.index.to_datetime().tz_localize('UTC'))

# Get all expected trading sessions in this range and reindex.
sessions = get_calendar('NYSE').sessions_in_range(start_date, end_date)
df = df.reindex(sessions)
```

**Comment by veeenu** [comment]
No problem! I will try reindexing the dataframe. I suggest adding this bit of information to the documentation as I believe time series with gaps are a frequent use case, at least in the context of custom bundles.

Thanks for your patience, and keep up the great work! :)

**Comment by veeenu** [comment]
After fixing the above, I incurred in another issue which I can't solve. It seems now that the data is correctly ingested, but I get an error at the time of executing the algorithm. This is my new ingest function:

```
  def ingest(environ, asset_db_writer, minute_bar_writer, daily_bar_writer, adjustment_writer, calendar, start_session, end_session, cache, show_progress, output_dir):
    
    differences = dict()
    symbols = sorted([a['ticker'] for a in assets])
    dtype = [('start_date', 'datetime64[ns]'),
              ('end_date', 'datetime64[ns]'),
              ('auto_close_date', 'datetime64[ns]'),
              ('symbol', 'object')]
    metadata = pd.DataFrame(np.empty(len(symbols), dtype=dtype))

    def write_fn():
      for idx, asset in enumerate(assets):
        aid, tkr = asset['id'], asset['ticker']
        ts = requests.get(API('asset/{:s}/prices/eod'.format(aid))).json()
        df = pd.DataFrame(ts).set_index('time')[['open', 'high', 'low', 'close', 'volume']]
        df.index = pd.to_datetime(df.index).tz_localize('UTC')

        start_date = df.index[0]
        end_date = df.index[-1]

        metadata.iloc[idx] = start_date.tz_convert(None), end_date.tz_convert(None), (end_date + pd.Timedelta(days=1)).tz_convert(None), tkr

        sess = calendar.sessions_in_range(start_date, end_date)
        dif = sess.difference(df.index)

        if len(dif) > 0:
          differences[tkr] = dif

        df = df.reindex(sess)

        yield idx, df

    daily_bar_writer.write(write_fn(), show_progress=True)
    asset_db_writer.write(equities=metadata)
    adjustment_writer.write(
      dividends=pd.DataFrame(columns=['sid', 'amount', 'ex_date', 'record_date', 'declared_date', 'pay_date']),
      splits=pd.DataFrame(columns=['sid', 'ratio', 'effective_date']))
    metadata['exchange'] = 'REINDEER'
    for k, v in differences.items():
      print(k, ' -> ', v) # list gaps
```
I then wrote a dummy algorithm, which works as intended with Quandl data:
```
from zipline.api import order, record, symbol

def initialize(context):
    print(context)

def handle_data(context, data):
    print(data)
```
But, as soon as I switch to my bundle, I get:
```
$ zipline run -b spx-reindeer -f algo.py -s 2018-01-01 -e 2018-02-01
[2018-05-30 08:51:18.524235] WARNING: Loader: Refusing to download new benchmark data because a download succeeded at 2018-05-30 07:59:42.414161+00:00.
[2018-05-30 08:51:18.549750] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2018-05-30 07:59:47.815400+00:00.
Traceback (most recent call last):
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline==1.2.0', 'console_scripts', 'zipline')()
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\__main__.py", line 98, in _
    return f(*args, **kwargs)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\__main__.py", line 259, in run
    environ=os.environ,
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\utils\run_algo.py", line 208, in _run
    overwrite_sim_params=False,
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\algorithm.py", line 642, in run
    self.trading_environment.asset_finder.sids
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\assets\assets.py", line 494, in retrieve_all
    update_hits(self.retrieve_equities(type_to_assets.pop('equity', ())))
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\assets\assets.py", line 528, in retrieve_equities
    return self._retrieve_assets(sids, self.equities, Equity)
  File "C:\Users\avenuta\AppData\Local\Continuum\Anaconda3\envs\zipline\lib\site-packages\zipline\assets\assets.py", line 681, in _retrieve_assets
    asset = asset_type(**filter_kwargs(row))
  File "zipline\assets\_assets.pyx", line 59, in zipline.assets._assets.Asset.__init__ (zipline/assets\_assets.c:1857)
TypeError: __init__() takes at least 2 positional arguments (1 given)
```
I'm not sure how to debug this situation as it looks pretty deep in the code, and related to the way the bundle is constructed. I also tried to add empty adjustment dataframes but at this point I can find no significant difference in the calls between my ingest function and the `csvdir` bundle (which I used as a guideline for my function). Do you have any suggestions?

Thanks!

**Comment by yankees714** [comment]
It looks like you're setting `metadata['exchange']` _after_ passing `metadata` into `asset_db_writer.write()`, so my guess is that the data being written is missing an exchange column. I'd try setting that beforehand.

For the initial report, sounds like the only issue is some details missing in the documentation, so I'm going to update to title of this reflect that. Feel free to open another issue if you run into anything else!

**Comment by fricative** [comment]
@yankees714 the clarification is quite helpful. However, in cases when a stock is listed very recently and we want to create a custom data bundle starting from a very early date e.g. 2000-1-1, the first several thousand rows in this stock's dataframe are going to be empty. I wonder what is the recommended way to deal with huge gap here? thanks in advance

**Comment by cemal95** [comment]
How would you solve for extra sessions? I have a similar problem, but iI have 2 errors. 1 one missing date, and the other shows extra sessions. How can I can ingest data and ignoring these extra sessions? and ingest such that it takes all the available data?
