### ISSUE TITLE
QuickStart Example FAIL

### ISSUE THREAD

**Issue by domesote** [quantopian/zipline#2205]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10

* Python Version: Python 3.5.5 :: Anaconda, Inc.

* Python Bitness: 64

* How did you install Zipline: 
   (1) conda create -n zipline python=3.5
   (2) activate zipline
   (3) conda install -c Quantopian zipline

* Python packages: `$ pip freeze` or `$ conda list`
```
   	# packages in environment at D:\program\Anaconda3\envs\zipline:
	#
	# Name                    Version                   Build  Channel
	alembic                   0.7.7                    py35_0    Quantopian
	asn1crypto                0.24.0                   py35_0  
	bcolz                     0.12.1              np111py35_0    Quantopian
	blosc                     1.14.3               he51fdeb_0  
	bottleneck                1.2.1            py35h8a3671c_0  
	bzip2                     1.0.6                hfa6e2cd_5  
	ca-certificates           2018.03.07                    0  
	certifi                   2018.4.16                py35_0  
	cffi                      1.11.5           py35h945400d_0  
	chardet                   3.0.4            py35h177e1b7_1  
	click                     6.7              py35h10df73f_0  
	contextlib2               0.5.5            py35h0a97e54_0  
	cryptography              2.2.2            py35hfa6e2cd_0  
	cyordereddict             0.2.2                    py35_0    Quantopian
	cython                    0.28.3           py35hfa6e2cd_0  
	decorator                 4.3.0                    py35_0  
	empyrical                 0.4.2                    py35_0    Quantopian
	hdf5                      1.10.2               hac2f561_1  
	icc_rt                    2017.0.4             h97af966_0  
	idna                      2.6              py35h8dcb9ae_1  
	intel-openmp              2018.0.3                      0  
	intervaltree              2.1.0                    py35_0    Quantopian
	logbook                   0.12.5                   py35_0    Quantopian
	lru-dict                  1.1.4                    py35_0    Quantopian
	lzo                       2.10                 h6df0209_2  
	mako                      1.0.7            py35ha146b58_0  
	markupsafe                1.0              py35hc253e08_1  
	mkl                       2018.0.3                      1  
	multipledispatch          0.5.0                    py35_0  
	networkx                  1.11             py35h097edc8_0  
	numexpr                   2.6.5            py35hcd2f87e_0  
	numpy                     1.11.3           py35h4a99626_4  
	openssl                   1.0.2o               h8ea7d77_0  
	pandas                    0.18.1              np111py35_0  
	pandas-datareader         0.5.0                    py35_0  
	patsy                     0.5.0                    py35_0  
	pip                       10.0.1                   py35_0  
	pycparser                 2.18             py35h15a15da_1  
	pyopenssl                 18.0.0                   py35_0  
	pysocks                   1.6.8                    py35_0  
	pytables                  3.4.3            py35he6f6034_1  
	python                    3.5.5                h0c2934d_2  
	python-dateutil           2.7.3                    py35_0  
	pytz                      2018.4                   py35_0  
	requests                  2.18.4           py35h54a615f_1  
	requests-file             1.4.3                    py35_0  
	requests-ftp              0.3.1                    py35_0  
	scipy                     1.1.0            py35h672f292_0  
	setuptools                39.2.0                   py35_0  
	six                       1.11.0           py35hc1da2df_1  
	snappy                    1.1.7                h777316e_3  
	sortedcontainers          2.0.3                    py35_0  
	sqlalchemy                1.2.8            py35hfa6e2cd_0  
	statsmodels               0.9.0            py35h452e1ab_0  
	toolz                     0.9.0                    py35_0  
	urllib3                   1.22             py35h8cc84eb_0  
	vc                        14                   h0510ff6_3  
	vs2015_runtime            14.0.25123                    3  
	wheel                     0.31.1                   py35_0  
	win_inet_pton             1.0.1            py35hbef1270_1  
	wincertstore              0.2              py35hfebbdb8_0  
	zipline                   1.2.0               np111py35_0    Quantopian
	zlib                      1.2.11               h8395fce_2  
```
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
   => pickle file can be read
* What happened instead?
  =>  begin_err_msg
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "pcikle_read.py", line 4, in <module>
	perf = pd.read_pickle('dma.pickle') # read in perf DataFrame
File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\io\pickle.py", line 180, in read_pickle
	return try_read(path, encoding='latin1')
File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\io\pickle.py", line 175, in try_read
	lambda f: pc.load(f, encoding=encoding, compat=True))
File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\io\pickle.py", line 149, in read_wrapper
	return func(f)
File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\io\pickle.py", line 175, in <lambda>
	lambda f: pc.load(f, encoding=encoding, compat=True))
File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\compat\pickle_compat.py", line 212, in load
	return up.load()
File "D:\program\Anaconda3\envs\zipline\lib\pickle.py", line 1043, in load
	dispatch[key[0]](self)
File "D:\program\Anaconda3\envs\zipline\lib\pickle.py", line 1351, in load_stack_global
	self.append(self.find_class(module, name))
File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\compat\pickle_compat.py", line 135, in find_class
	return super(Unpickler, self).find_class(module, name)
File "D:\program\Anaconda3\envs\zipline\lib\pickle.py", line 1392, in find_class
	__import__(module, level=0)
File "D:\program\Anaconda3\envs\zipline\lib\site-packages\zipline\__init__.py", line 21, in <module>
	from . import finance
File "D:\program\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\__init__.py", line 16, in <module>
	from . import execution, trading
File "D:\program\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\trading.py", line 19, in <module>
	from pandas.tslib import normalize_date
ImportError: cannot import name 'normalize_date'
```
<= end_error_msg

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. set QUANDL_API_KEY="my key"
2. zipline ingest -b quandl
3. zipline run -f dual_moving_average.py --start 2014-1-1 --end 2018-1-1 -o dma.pickle
4. write a simple python file
    ```
    import pandas as pd
    perf = pd.read_pickle('dma.pickle') # read in perf DataFrame
    print(perf.head())
    ```

## What steps have you taken to resolve this already?
NO!!!

Sincerely,
Lenny

**Comment by freddiev4** [comment]
Hi @domesote thanks for opening this issue.

My guess here is that the `pandas` package you're using, and the one you should be using that's in your `conda env`, are not matching up. In other words, you need to be using:

```
import pandas as pd
perf = pd.read_pickle('dma.pickle') # read in perf DataFrame
print(perf.head())
```

While still in your conda env, which you seem to have called `zipline`.

---------------------
`File "C:\Users\Lenny\AppData\Roaming\Python\Python35\site-packages\pandas\io\pickle.py"`
^^ your `pandas` package in your default conda installation

`File "D:\program\Anaconda3\envs\zipline\lib\site-packages\zipline\finance\trading.py",`
^^ Zipline in your conda env.

Can you run `conda list` and provide the output?

**Comment by freddiev4** [comment]
Going to close this as no follow up from OP; feel free to reopen if you still have issues 🙂
