### ISSUE TITLE
zipline does not register custom bundle

### ISSUE THREAD

**Issue by jraviotta** [quantopian/zipline#2230]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

```
Operating System: 
Linux eb0652966f82 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux

Python Version: 
3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]

Python Bitness: 
64
How did you install Zipline: 
Docker container

Python packages: 
# packages in environment at /opt/conda/envs/zipline:
#
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    quantopian
asn1crypto                0.24.0                   py35_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcolz                     0.12.1              np111py35_0    quantopian
blas                      1.0                         mkl
blosc                     1.14.3               hdbcaa40_0
bottleneck                1.2.1            py35he1b16f1_0
bzip2                     1.0.6                h14c3975_5
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py35_0    conda-forge
cffi                      1.11.5           py35h9745a5d_0
chardet                   3.0.4            py35hb6e9ddf_1
click                     6.7              py35h353a69f_0
contextlib2               0.5.5            py35h6690dba_0
cryptography              2.2.2            py35h14c3975_0
cycler                    0.10.0           py35hc4d5149_0
cyordereddict             0.2.2                    py35_0    quantopian
cython                    0.28.3           py35h14c3975_0
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                    py35_0
empyrical                 0.4.3                    py35_0    quantopian
expat                     2.2.5                         0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.55.0                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
hdf5                      1.10.2               hba1933b_1
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py35_0    conda-forge
intel-openmp              2018.0.3                      0
intervaltree              2.1.0                    py35_0    quantopian
ipykernel                 4.8.2                    py35_0    conda-forge
ipython                   6.4.0                    py35_0    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
jedi                      0.12.0                   py35_0    conda-forge
jpeg                      9b                            2    conda-forge
jupyter_client            5.2.3                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1            py35hcb1117a_0
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran               3.0.0                         1
libgfortran-ng            7.2.0                hdf63c60_3
libiconv                  1.15                 h470a237_1    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                         0    conda-forge
logbook                   0.12.5                   py35_0    quantopian
lru-dict                  1.1.4                    py35_0    quantopian
lzo                       2.10                 h49e0be7_2
mako                      1.0.7            py35h69899ea_0
markupsafe                1.0              py35h4f4fcf6_1
matplotlib                2.2.2            py35h0e671d2_0
mkl                       2018.0.3                      1
multipledispatch          0.5.0                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  1.11             py35hf333c83_0
numexpr                   2.6.5            py35h7bf3b9c_0
numpy                     1.11.3           py35h3dfced4_4
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o                        0    conda-forge
pandas                    0.18.1              np111py35_0    conda-forge
pandas-datareader         0.5.0                    py35_0    conda-forge
parso                     0.2.1                      py_0    conda-forge
patsy                     0.5.0                    py35_0    conda-forge
pcre                      8.41                          1    conda-forge
pexpect                   4.6.0                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
pip                       10.0.1                   py35_0
prompt_toolkit            1.0.15                   py35_0    conda-forge
ptyprocess                0.6.0                    py35_0    conda-forge
pycparser                 2.18             py35h61b3040_1
pygments                  2.2.0                    py35_0    conda-forge
pyopenssl                 18.0.0                   py35_0    conda-forge
pyparsing                 2.2.0            py35h041ed72_1
pyqt                      5.6.0            py35h0e41ada_5
pysocks                   1.6.8                    py35_0
pytables                  3.4.4            py35h02b9ad4_0
python                    3.5.4               h56e0582_23
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyzmq                     17.0.0                   py35_4    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.19.1                   py35_0    conda-forge
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0    conda-forge
scipy                     1.1.0            py35hfc37229_0
setuptools                39.2.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18.1           py35h9eaea60_2
six                       1.11.0           py35h423b573_1
snappy                    1.1.7                hbae5bb6_3
sortedcontainers          1.4.4                    py35_0    quantopian
sqlalchemy                1.2.8            py35h14c3975_0
sqlite                    3.20.1                        2    conda-forge
statsmodels               0.9.0            py35h3010b51_0
ta-lib                    0.4.9               np111py35_0    quantopian
tk                        8.6.7                         0    conda-forge
toolz                     0.9.0                    py35_0
tornado                   5.0.2                    py35_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
urllib3                   1.23                     py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wheel                     0.31.1                   py35_0
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.5                         1    conda-forge
zipline                   1.2.0               np111py35_0    quantopian
zlib                      1.2.11               h470a237_3    conda-forge

Python 3.6.5 :: Anaconda, Inc.
```

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I have created an ingest function modeled on the `quandl.py` function and have registered the custom ingest function in `extension.py`. Both are located in `$ZIPLINE_ROOT` which is in a custom location.

When I run `zipline ingest -b bter` i get `UnknownBundle: No bundle registered with the name 'bter'` Unfortunately the documentation and references to creating a custom ingest function on Google are sparse.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

```
%pwd
/opt/projects/zipline-notebooks/zipline
```
```
%ls $ZIPLINE_ROOT
bter.py  data/  extension.py  nomics.py  quandl-sample.py
```
```
%cat $ZIPLINE_ROOT/extension.py
import pandas as pd

from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities
from zipline.data.bundles.bter import test


register(
    'bter',
    test(),
)
```
```
%cat $ZIPLINE_ROOT/bter.py
"""
Module for building a complete daily dataset from Quandl's BTER dataset.
https://www.quandl.com/data/BTER-BTER
"""
from io import BytesIO
import tarfile
from zipfile import ZipFile

from click import progressbar
from logbook import Logger
import pandas as pd
import requests
from six.moves.urllib.parse import urlencode
from six import iteritems

from zipline.utils.calendars import register_calendar_alias
from zipline.utils.deprecate import deprecated
from . import core as bundles
import numpy as np

log = Logger(__name__)

ONE_MEGABYTE = 1024 * 1024
QUANDL_DATA_URL = (
    'https://www.quandl.com/api/v3/datatables/BTER/PRICES.csv?'
)

def test():
    print('test')
    
def format_metadata_url(api_key):
    """ Build the query URL for Quandl Prices metadata.
    """
    query_params = [('api_key', api_key), ('qopts.export', 'true')]

    return (
        QUANDL_DATA_URL + urlencode(query_params)
    )


def load_data_table(file,
                    index_col,
                    show_progress=False):
    """ Load data table from zip file provided by Quandl.
    """
    with ZipFile(file) as zip_file:
        file_names = zip_file.namelist()
        assert len(file_names) == 1, "Expected a single file from Quandl."
        prices = file_names.pop()
        with zip_file.open(prices) as table_file:
            if show_progress:
                log.info('Parsing raw data.')
            data_table = pd.read_csv(
                table_file,
                parse_dates=['date'],
                index_col=index_col,
                usecols=[
                    'ticker',
                    'date',
                    'open',
                    'high',
                    'low',
                    'close',
                    'volume',
                    'ex-dividend',
                    'split_ratio',
                ],
            )

    data_table.rename(
        columns={
            'ticker': 'symbol',
            'ex-dividend': 'ex_dividend',
        },
        inplace=True,
        copy=False,
    )
    return data_table


def fetch_data_table(api_key,
                     show_progress,
                     retries):
    """ Fetch Prices data table from Quandl
    """
    for _ in range(retries):
        try:
            if show_progress:
                log.info('Downloading metadata.')

            metadata = pd.read_csv(
                format_metadata_url(api_key)
            )
            # Extract link from metadata and download zip file.
            table_url = metadata.loc[0, 'file.link']
            if show_progress:
                raw_file = download_with_progress(
                    table_url,
                    chunk_size=ONE_MEGABYTE,
                    label="Downloading Prices table from Quandl"
                )
            else:
                raw_file = download_without_progress(table_url)

            return load_data_table(
                file=raw_file,
                index_col=None,
                show_progress=show_progress,
            )

        except Exception:
            log.exception("Exception raised reading Quandl data. Retrying.")

    else:
        raise ValueError(
            "Failed to download Quandl data after %d attempts." % (retries)
        )


def gen_asset_metadata(data, show_progress):
    if show_progress:
        log.info('Generating asset metadata.')

    data = data.groupby(
        by='symbol'
    ).agg(
        {'date': [np.min, np.max]}
    )
    data.reset_index(inplace=True)
    data['start_date'] = data.date.amin
    data['end_date'] = data.date.amax
    del data['date']
    data.columns = data.columns.get_level_values(0)

    data['exchange'] = 'QUANDL'
    data['auto_close_date'] = data['end_date'].values + pd.Timedelta(days=1)
    return data


# def parse_splits(data, show_progress):
#     if show_progress:
#         log.info('Parsing split data.')

#     data['split_ratio'] = 1.0 / data.split_ratio
#     data.rename(
#         columns={
#             'split_ratio': 'ratio',
#             'date': 'effective_date',
#         },
#         inplace=True,
#         copy=False,
#     )
#     return data


# def parse_dividends(data, show_progress):
#     if show_progress:
#         log.info('Parsing dividend data.')

#     data['record_date'] = data['declared_date'] = data['pay_date'] = pd.NaT
#     data.rename(
#         columns={
#             'ex_dividend': 'amount',
#             'date': 'ex_date',
#         },
#         inplace=True,
#         copy=False,
#     )
#     return data


def parse_pricing_and_vol(data,
                          sessions,
                          symbol_map):
    for asset_id, symbol in iteritems(symbol_map):
        asset_data = data.xs(
            symbol,
            level=1
        ).reindex(
            sessions.tz_localize(None)
        ).fillna(0.0)
        yield asset_id, asset_data


@bundles.register('bter')
def quandl_bundle(environ,
                  asset_db_writer,
                  minute_bar_writer,
                  daily_bar_writer,
                  adjustment_writer,
                  calendar,
                  start_session,
                  end_session,
                  cache,
                  show_progress,
                  output_dir):
    """
    quandl_bundle builds a daily dataset using Quandl's BTER Prices dataset.

    For more information on Quandl's API and how to obtain an API key,
    please visit https://docs.quandl.com/docs#section-authentication
    """
    api_key = environ.get('QUANDL_API_KEY')
    if api_key is None:
        raise ValueError(
            "Please set your QUANDL_API_KEY environment variable and retry."
        )

    raw_data = fetch_data_table(
        api_key,
        show_progress,
        environ.get('QUANDL_DOWNLOAD_ATTEMPTS', 5)
    )
    asset_metadata = gen_asset_metadata(
        raw_data[['symbol', 'date']],
        show_progress
    )
    asset_db_writer.write(asset_metadata)

    symbol_map = asset_metadata.symbol
    sessions = calendar.sessions_in_range(start_session, end_session)

    raw_data.set_index(['date', 'symbol'], inplace=True)
    daily_bar_writer.write(
        parse_pricing_and_vol(
            raw_data,
            sessions,
            symbol_map
        ),
        show_progress=show_progress
    )

    raw_data.reset_index(inplace=True)
    raw_data['symbol'] = raw_data['symbol'].astype('category')
    raw_data['sid'] = raw_data.symbol.cat.codes
    # adjustment_writer.write(
    #     splits=parse_splits(
    #         raw_data[[
    #             'sid',
    #             'date',
    #             'split_ratio',
    #         ]].loc[raw_data.split_ratio != 1],
    #         show_progress=show_progress
    #     ),
    #     dividends=parse_dividends(
    #         raw_data[[
    #             'sid',
    #             'date',
    #             'ex_dividend',
    #         ]].loc[raw_data.ex_dividend != 0],
    #         show_progress=show_progress
    #     )
    # )


def download_with_progress(url, chunk_size, **progress_kwargs):
    """
    Download streaming data from a URL, printing progress information to the
    terminal.

    Parameters
    ----------
    url : str
        A URL that can be understood by ``requests.get``.
    chunk_size : int
        Number of bytes to read at a time from requests.
    **progress_kwargs
        Forwarded to click.progressbar.

    Returns
    -------
    data : BytesIO
        A BytesIO containing the downloaded data.
    """
    resp = requests.get(url, stream=True)
    resp.raise_for_status()

    total_size = int(resp.headers['content-length'])
    data = BytesIO()
    with progressbar(length=total_size, **progress_kwargs) as pbar:
        for chunk in resp.iter_content(chunk_size=chunk_size):
            data.write(chunk)
            pbar.update(len(chunk))

    data.seek(0)
    return data


def download_without_progress(url):
    """
    Download data from a URL, returning a BytesIO containing the loaded data.

    Parameters
    ----------
    url : str
        A URL that can be understood by ``requests.get``.

    Returns
    -------
    data : BytesIO
        A BytesIO containing the downloaded data.
    """
    resp = requests.get(url)
    resp.raise_for_status()
    return BytesIO(resp.content)

register_calendar_alias("BTER", "TFS")

```
```
from zipline.data import bundles;bundles.ingest("bter")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/envs/zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py in ingest(name, environ, timestamp, assets_versions, show_progress)
    359         try:
--> 360             bundle = bundles[name]
    361         except KeyError:

KeyError: 'bter'

During handling of the above exception, another exception occurred:

UnknownBundle                             Traceback (most recent call last)
<ipython-input-74-949c941a12f6> in <module>()
     23 print('```')
     24 print('bundles.ingest("bter")')
---> 25 bundles.ingest("bter")
     26 print('```')

/opt/conda/envs/zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py in ingest(name, environ, timestamp, assets_versions, show_progress)
    360             bundle = bundles[name]
    361         except KeyError:
--> 362             raise UnknownBundle(name)
    363 
    364         calendar = get_calendar(bundle.calendar_name)

UnknownBundle: No bundle registered with the name 'bter'
```
Any suggestions would be appreciated. Thanks!

**Comment by freddiev4** [comment]
Hi @jraviotta your `bter.py` file is in `~/.zipline/bter.py`, but in your extension file, you're trying to import bter with:

```
from zipline.data.bundles.bter import test

register(
    'bter',
    test(),
)
```

Have you moved your `bter.py` file into `zipline/data/bundles/bter`?

**Comment by jraviotta** [comment]
Thanks for the suggestion, but that didn't solve it. Though it may not make a difference, note that I have set `$ZIPLINE_ROOT=/opt/projects/zipline-notebooks/zipline` so that I can keep all user-generated data and custom code in a bind-mounted docker volume outside of the auto-generated container assets.
```
(zipline) root@2c554ef5596c:/opt/projects/zipline-notebooks# ls /opt/conda/envs/zipline/lib/python3.5/site-packages/zipline/data/bundles/
__init__.py  bter.py  csvdir.py     quandl.py
__pycache__  core.py  extension.py
```
```
(zipline) root@2c554ef5596c:/opt/projects/zipline-notebooks# python
Python 3.5.4 |Anaconda, Inc.| (default, Nov  9 2017, 00:39:12)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zipline.data import bundles

>>> bundles.ingest('bter')
Traceback (most recent call last):
  File "/opt/conda/envs/zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 360, in ingest
    bundle = bundles[name]
KeyError: 'bter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 362, in ingest
    raise UnknownBundle(name)
zipline.data.bundles.core.UnknownBundle: No bundle registered with the name 'bter'
```
Also, I would expect that a custom ingest function should be accessible in the $ZIPLINE_ROOT dir. Moving or linking it in the zipline library makes portability difficult. All custom code should be located in an external directory that can be managed under source control especially in a docker container set-up.

Any other suggestions?

**Comment by jraviotta** [comment]
Can you point me to instructions to get an ingest function working please?

I have followed the directions [here](https://stackoverflow.com/questions/38466000/zipline-using-pandas-datareader-to-feed-in-google-finance-dataframe-for-non-us) but did not have success.

Any help would be appreciated.

**Comment by freddiev4** [comment]
Hi @jraviotta those instructions on StackOverflow are definitely outdated so I would not rely on those.

To your previous comment, I agree that moving / linking your code into the zipline library is not the right thing to do (was more of a curiosity comment on my end). You should be able to do this from `~/.zipline/extension.py`, or wherever your `extension.py` file lives.

I took a deeper look into your bundle code and there are some other issues. Quick comment first: I wouldn't recommend taking the existing `quandl` bundle code and editing it to remove functions you don't care about or add things in, e.g. the prices URL. I'd recommend using it as a guide but not a piece of code to edit.

Now on to the actual functionality:

**Bundle Registering:**
First, in your `extension.py` file, you're calling `register('bter', test()` which actually overrides the `bter` bundle. The decorator call `@bundles.register('bter')` already takes care of the bundle registration for you, where you have your `quandl_bundle` function. Also `test()` doesn't do anything so that wouldn't be the correct function to pass either way.

**Metadata Formatting:**
Second, it looks like the way that the metadata URL is formatted doesn't work for the dataset you're trying to download. The function below:

```
def format_metadata_url(api_key):
  """ Build the query URL for Quandl Prices metadata.
  """
  query_params = [('api_key', api_key), ('qopts.export', 'true')]
  return (
      QUANDL_DATA_URL + urlencode(query_params)
  )
```

Returns a URL of the following format: 
`https://www.quandl.com/api/v3/datatables/BTER/PRICES.csv?api_key=<yourapikey>&qopts.export=true`

According to the [Quandl BTER Usage Docs](https://www.quandl.com/data/BTER-BTER/usage/quickstart/api), the URL does not use the `/datatables/` path, but uses `/datasets/`, and does not have a file called `PRICES.csv`. So before trying to make a bundle from a third-party data provider, you should double check their usage docs to make sure you're hitting the correct endpoint.

Changing `QUANDL_DATA_URL` to `https://www.quandl.com/api/v3/datasets/BTER/BTMETH?` will give you the formatting you need, replacing `BTMETH` with whatever exchange rates you want, e.g. LRC/CNY would be `LRCCNY`. Note that the data format comes back as JSON and not as a csv file, so you would need to edit at line 166 in the gist I've posted [here](https://gist.github.com/freddiev4/32298c0c3a6265f8ad15aaecd7d5652a).

**Quandl Datasets:**
The reason why I mentioned above that you should not be editing the Quandl bundle code we already have in Zipline, is that it looks like Quandl's data formats are not the same between their datasets, which is very common in general for any dataset. So it looks like you have some more work to do here in regards to getting the data from Quandl in a proper format so that you can ingest it into Zipline. Also, not sure if you care about this, but the BTER dataset is deprecated.


**Question:**
Just curious to know how you want to treat this dataset; i.e. do you want to treat the exchange rate as the price of a security? Seems to me like you're trying to do something Forex-like.

**Comment by jraviotta** [comment]
@freddiev4 Thanks so much for the thorough analysis and suggestions. As you noted, the supplied code was pretty ugly. I was just trying to get my head wrapped around registering a custom ingest function that can be picked up by zipline. It was just an attempt to get a proof of life from an alternative data source.

My ultimate goal is to ingest cryptocurrency exchange data and to use zipline's already established financial processing routines. I noted that Quantopian is not planning to support crypto anytime soon so it seemed like I would have to do the hard work of generating a database myself. 

Fortunately, I did find exactly what I was looking for in this project: https://enigma.co/catalyst/. It is built on top of zipline and seems to be mirroring the Quantopian model for crypto. The project is still in alpha and only offers limited granularity in time series buckets, but it's miles beyond my juvenile efforts. I plan to work with that for now.

Again, thanks for your attention to my question.

**Comment by freddiev4** [comment]
@jraviotta Sure no problem. I'm glad you found a project to work with. I'm going to close this issue then as it seems to be resolved.
