### ISSUE TITLE
zipline.run_algorithm error vs command line 

### ISSUE THREAD

**Issue by alex-anski** [quantopian/zipline#2319]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 64
* Python Version: `$ Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:05:27) `
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'` = 64
* How did you install Zipline: conda
* Python packages: `$ pip freeze` or `$ conda list`
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py35_0  
alabaster                 0.7.11                   py35_0  
alembic                   0.7.7                    py35_0    quantopian
anaconda-client           1.7.2                    py35_0  
anaconda-navigator        1.9.2                    py35_0  
anaconda-project          0.8.2                    py35_0  
appdirs                   1.4.3            py35h28b3542_0  
asn1crypto                0.24.0                   py35_0  
astroid                   2.0.4                    py35_0  
astropy                   3.0.4            py35hfa6e2cd_0  
atomicwrites              1.2.1                    py35_0  
attrs                     18.2.0           py35h28b3542_0  
automat                   0.7.0                    py35_0  
babel                     2.6.0                    py35_0  
backcall                  0.1.0                    py35_0  
backports                 1.0                      py35_1  
backports.shutil_get_terminal_size 1.0.0                    py35_2  
bcolz                     0.12.1              np114py35_0    quantopian
beautifulsoup4            4.6.3                    py35_0  
bitarray                  0.8.3            py35hfa6e2cd_0  
bkcharts                  0.2              py35h4704c85_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py35_0  
bleach                    2.1.4                    py35_0  
blosc                     1.14.3               he51fdeb_0  
bokeh                     0.13.0                   py35_0  
boto                      2.49.0                   py35_0  
bottleneck                1.2.1            py35h452e1ab_1  
bzip2                     1.0.6                hfa6e2cd_5  
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.8.24                py35_1    anaconda
cffi                      1.11.5           py35h74b6da3_1  
chardet                   3.0.4                    py35_1  
click                     6.7              py35h10df73f_0  
cloudpickle               0.5.5                    py35_0  
clyent                    1.2.2                    py35_1  
colorama                  0.3.9            py35h32a752f_0  
comtypes                  1.1.7                    py35_0  
conda                     4.5.11                   py35_0  
conda-build               3.15.1                   py35_0  
conda-env                 2.6.0                h36134e3_1  
conda-verify              3.1.0                    py35_0  
console_shortcut          0.1.1                h6bb2dd7_3  
constantly                15.1.0           py35h28b3542_0  
contextlib2               0.5.5            py35h0a97e54_0  
cryptography              2.3.1            py35h74b6da3_0  
curl                      7.60.0               h7602738_0  
cvxopt                    1.2.0            py35h685f9cb_0  
cycler                    0.10.0           py35hcc71164_0  
cyordereddict             0.2.2                    py35_0    quantopian
cython                    0.28.5           py35h6538335_0  
cytoolz                   0.9.0.1          py35hfa6e2cd_1  
dask                      0.19.2                   py35_0  
dask-core                 0.19.2                   py35_0  
datashape                 0.5.4                    py35_1  
decorator                 4.3.0                    py35_0  
defusedxml                0.5.0                    py35_1  
distributed               1.23.2                   py35_0  
docutils                  0.14             py35h8ccb97f_0  
empyrical                 0.5.0                    py35_0    quantopian
entrypoints               0.2.3                    py35_2  
et_xmlfile                1.0.1            py35h2c13def_0  
fastcache                 1.0.2            py35hfa6e2cd_2  
filelock                  3.0.8                    py35_0  
flask                     1.0.2                    py35_1  
flask-cors                3.0.6                    py35_0  
freetype                  2.8                  h51f8f2c_1  
future                    0.16.0                   py35_2  
get_terminal_size         1.0.0                h38e98db_0  
glob2                     0.6                      py35_0  
glpk                      4.65                 hdc00fd2_2  
greenlet                  0.4.15           py35hfa6e2cd_0  
gsl                       2.4                  hfa6e2cd_4  
h5py                      2.8.0            py35h3bdd7fb_2  
hdf5                      1.10.2               hac2f561_1  
heapdict                  1.0.0                    py35_2  
html5lib                  1.0.1                    py35_0  
hyperlink                 18.0.0                   py35_0  
icc_rt                    2017.0.4             h97af966_0  
icu                       58.2                 ha66f8fd_1  
idna                      2.7                      py35_0  
imageio                   2.4.1                    py35_0  
imagesize                 1.1.0                    py35_0  
incremental               17.5.0                   py35_0  
inflection                0.3.1                    py35_1  
intel-openmp              2018.0.0                      8  
intervaltree              2.1.0                    py35_0    quantopian
ipykernel                 4.10.0                   py35_0  
ipython                   6.5.0                    py35_0  
ipython_genutils          0.2.0            py35ha709e79_0  
ipywidgets                7.4.1                    py35_0  
isort                     4.3.4                    py35_0  
itsdangerous              0.24                     py35_1  
jdcal                     1.4                      py35_0  
jedi                      0.12.1                   py35_0  
jinja2                    2.10                     py35_0  
jpeg                      9b                   hb83a4c4_2  
jsonschema                2.6.0            py35h27d56d3_0  
jupyter                   1.0.0                    py35_7  
jupyter_client            5.2.3                    py35_0  
jupyter_console           5.2.0                    py35_1  
jupyter_core              4.4.0                    py35_0  
jupyterlab                0.34.9                   py35_0  
jupyterlab_launcher       0.13.1                   py35_0  
keyring                   13.2.1                   py35_0  
kiwisolver                1.0.1            py35h6538335_0  
lazy-object-proxy         1.3.1            py35hfa6e2cd_2  
libcurl                   7.60.0               hc4dcbb0_0  
libiconv                  1.15                 h1df5818_7  
libpng                    1.6.34               h79bbb47_0  
libsodium                 1.0.16               h9d3ae62_0  
libssh2                   1.8.0                hd619d38_4  
libtiff                   4.0.9                hb8ad9f9_1  
libxml2                   2.9.8                hadb2253_1  
libxslt                   1.1.32               hf6f1972_0  
llvmlite                  0.24.0           py35h6538335_0  
locket                    0.2.0            py35h0dfcdd0_1  
logbook                   0.12.5                   py35_0    quantopian
lru-dict                  1.1.4                    py35_0    quantopian
lxml                      4.2.5            py35hef2cd61_0  
lzo                       2.10                 h6df0209_2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
mako                      1.0.7                    py35_0  
markupsafe                1.0              py35hfa6e2cd_1  
matplotlib                2.2.2            py35h153e9ff_1  
mccabe                    0.6.1                    py35_1  
menuinst                  1.4.14           py35hfa6e2cd_0  
mistune                   0.8.3            py35hfa6e2cd_1  
mkl                       2019.0                      118  
mkl-service               1.1.2            py35hb217b18_5  
mkl_fft                   1.0.6            py35hdbbee80_0  
mkl_random                1.0.1            py35h77b88f5_1  
more-itertools            4.3.0                    py35_0  
mpmath                    1.0.0                    py35_2  
msgpack-python            0.5.6            py35he980bc4_1  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.6.0                    py35_0  
navigator-updater         0.2.1                    py35_0  
nbconvert                 5.4.0                    py35_1  
nbformat                  4.4.0            py35h908c9d9_0  
networkx                  1.11                     py35_1  
nltk                      3.3.0                    py35_0  
nose                      1.3.7                    py35_2  
notebook                  5.6.0                    py35_0  
numba                     0.39.0           py35h830ac7b_0  
numexpr                   2.6.1               np114py35_0    quantopian
numpy                     1.14.6           py35hc27ee41_4  
numpy-base                1.14.6           py35h8128ebf_4  
numpydoc                  0.8.0                    py35_0  
odo                       0.5.1            py35hc850252_0  
olefile                   0.46                     py35_0  
openpyxl                  2.5.6                    py35_0  
openssl                   1.0.2p               hfa6e2cd_0    anaconda
packaging                 17.1                     py35_0  
pandas                    0.22.0           py35h6538335_0  
pandas-datareader         0.6.0                    py35_0    anaconda
pandoc                    1.19.2.1             hb2460c7_1  
pandocfilters             1.4.2                    py35_1  
parso                     0.3.1                    py35_0  
partd                     0.3.8            py35h894d1e4_0  
path.py                   11.1.0                   py35_0  
pathlib2                  2.3.2                    py35_0  
patsy                     0.5.0                    py35_0  
pep8                      1.7.1                    py35_0  
pickleshare               0.7.4            py35h2f9f535_0  
pillow                    5.1.0            py35h0738816_0  
pip                       10.0.1                   py35_0  
pkginfo                   1.4.2                    py35_1  
pluggy                    0.7.1            py35h28b3542_0  
ply                       3.11                     py35_0  
prometheus_client         0.3.1            py35h28b3542_0  
prompt_toolkit            1.0.15           py35h89c7cb4_0  
psutil                    5.4.7            py35hfa6e2cd_0  
py                        1.6.0                    py35_0  
pyasn1                    0.4.4            py35h28b3542_0  
pyasn1-modules            0.2.2                    py35_0  
pycodestyle               2.4.0                    py35_0  
pycosat                   0.6.3            py35hfa6e2cd_0  
pycparser                 2.18                     py35_1  
pycrypto                  2.6.1            py35hfa6e2cd_9  
pycurl                    7.43.0.2         py35h74b6da3_0  
pyflakes                  2.0.0                    py35_0  
pygments                  2.2.0            py35h24c0941_0  
pylint                    2.1.1                    py35_0  
pyodbc                    4.0.24           py35h6538335_0  
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.2.0                    py35_1  
pyqt                      5.9.2            py35h6538335_2  
pysocks                   1.6.8                    py35_0  
pytables                  3.4.4            py35he6f6034_0  
pytest                    3.8.1                    py35_0  
pytest-arraydiff          0.2              py35h39e3cac_0  
pytest-astropy            0.4.0                    py35_0  
pytest-doctestplus        0.1.3                    py35_0  
pytest-openfiles          0.3.0                    py35_0  
pytest-remotedata         0.3.0                    py35_0  
python                    3.5.6                he025d50_0  
python-dateutil           2.7.3                    py35_0  
pytz                      2018.5                   py35_0  
pywavelets                1.0.0            py35h452e1ab_0  
pywin32                   223              py35hfa6e2cd_1  
pywinpty                  0.5.4                    py35_0  
pyyaml                    3.13             py35hfa6e2cd_0  
pyzmq                     17.1.2           py35hfa6e2cd_0  
qt                        5.9.6            vc14h1e9a669_2  
qtawesome                 0.4.4            py35h639d0ff_0  
qtconsole                 4.4.1                    py35_0  
qtpy                      1.5.0                    py35_0  
quandl                    3.4.2                    py35_0  
requests                  2.19.1                   py35_0  
requests-file             1.4.3                    py35_0  
requests-ftp              0.3.1                    py35_0  
rope                      0.11.0                   py35_0  
ruamel_yaml               0.15.46          py35hfa6e2cd_0  
scikit-image              0.14.0           py35h6538335_1  
scikit-learn              0.20.0           py35heebcf9a_1  
scipy                     1.1.0            py35hc28095f_0  
seaborn                   0.9.0                    py35_0  
send2trash                1.5.0                    py35_0  
service_identity          17.0.0           py35h28b3542_0  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
singledispatch            3.4.0.3          py35h33f66b4_0  
sip                       4.19.8           py35h6538335_0  
six                       1.11.0                   py35_1  
snappy                    1.1.7                h777316e_3  
snowballstemmer           1.2.1            py35h4c55bfa_0  
sortedcollections         0.6.1                    py35_0  
sortedcontainers          1.4.4                    py35_0    quantopian
sphinx                    1.7.9                    py35_0  
sphinxcontrib             1.0                      py35_1  
sphinxcontrib-websupport  1.1.0                    py35_1  
spyder                    3.3.1                    py35_1  
spyder-kernels            0.2.6                    py35_0  
sqlalchemy                1.2.11           py35hfa6e2cd_0  
sqlite                    3.25.2               hfa6e2cd_0  
statsmodels               0.9.0            py35h452e1ab_0  
sympy                     1.2                      py35_0  
tblib                     1.3.2            py35hd2cf7e1_0  
terminado                 0.8.1                    py35_1  
testpath                  0.3.1            py35h06cf69e_0  
tk                        8.6.7                hcb92d03_3  
toolz                     0.9.0                    py35_0  
tornado                   5.1              py35hfa6e2cd_0  
tqdm                      4.26.0           py35h28b3542_0  
trading-calendars         1.0.1                    py35_0    quantopian
traitlets                 4.3.2            py35h09b975b_0  
twisted                   18.7.0           py35hfa6e2cd_1  
typed-ast                 1.1.0            py35hfa6e2cd_0  
typing                    3.6.6                    py35_0  
unicodecsv                0.14.1           py35h0d88516_0  
urllib3                   1.23                     py35_0  
vc                        14.1                 h21ff451_3    anaconda
vs2015_runtime            15.5.2                        3    anaconda
wcwidth                   0.1.7            py35h6e80d8a_0  
webencodings              0.5.1                    py35_1  
werkzeug                  0.14.1                   py35_0  
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.4.1                    py35_0  
win_inet_pton             1.0.1                    py35_1  
win_unicode_console       0.5              py35h56988b5_0  
wincertstore              0.2              py35hfebbdb8_0  
winpty                    0.4.3                         4  
wrapt                     1.10.11          py35hfa6e2cd_2  
xlrd                      1.1.0                    py35_1  
xlsxwriter                1.1.0                    py35_0  
xlwings                   0.11.8                   py35_0  
xlwt                      1.3.0            py35hd04410a_0  
yaml                      0.1.7                hc54c509_2  
zeromq                    4.2.5                hc6251cf_0  
zict                      0.1.3                    py35_0  
zipline                   1.3.0               np114py35_0    quantopian
zlib                      1.2.11               h8395fce_2  
zope                      1.0                      py35_1  
zope.interface            4.5.0            py35hfa6e2cd_0  

</details>

# Description of Issue

I try to run example code 

```
from zipline.api import order, record, symbol
from zipline.utils.calendars import TradingCalendar

import pandas as pd
import matplotlib.pyplot as plt    

def initialize(context):
    pass


def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data.current(symbol('AAPL'), 'price'))
    
```

if I run it from command line 

zipline run --algofile tutorial.py --start 2015-1-1 --end 2018-1-1 -o dma.pickle 

it works as expected

if I run it as 

```
perf = zipline.run_algorithm(start = '2015-1-1', 
                      end = '2018-1-1',
                      initialize = 'initialize',
                      capital_base = 100000
                      )
```

I  get 

```
perf = zipline.run_algorithm(start = '2015-1-1', 
                      end = '2018-1-1',
                      initialize = 'initialize',
                      capital_base = 100000
                      )
Traceback (most recent call last):

  File "<ipython-input-4-f8832636aef2>", line 4, in <module>
    capital_base = 100000

  File "C:\Users\user\Anaconda3\lib\site-packages\zipline\utils\run_algo.py", line 430, in run_algorithm
    blotter=blotter,

  File "C:\Users\user\Anaconda3\lib\site-packages\zipline\utils\run_algo.py", line 214, in _run
    trading_calendar=trading_calendar,

  File "C:\Users\user\Anaconda3\lib\site-packages\zipline\utils\factory.py", line 62, in create_simulation_parameters
    trading_calendar=trading_calendar,

  File "C:\Users\user\Anaconda3\lib\site-packages\zipline\finance\trading.py", line 141, in __init__
    assert type(start_session) == pd.Timestamp

AssertionError

```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. create tutorial.py w code above
2. run from command line
3. do the same w zipline.run_algorithm

## What steps have you taken to resolve this already?

I tried to reinstall the package, reload data bundles

Thank you!

**Comment by alex-anski** [comment]
Sorry, my fault
