### ISSUE TITLE
can't import the samples

### ISSUE THREAD

**Issue by johnwatson11218** [quantopian/zipline#2375]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

macbook pro, using conda ( python=3.4 ). Can't do the simple examples from the docs

(zipline) Johns-MacBook-Pro:zipline johnwatson$ conda install -c Quantopian zipline
Fetching package metadata ...............
Solving package specifications: python
.

# All requested packages already installed.
# packages in environment at /anaconda/envs/zipline:
#
zipline                   1.0.2                np19py34_0    Quantopian
(zipline) Johns-MacBook-Pro:zipline johnwatson$ python
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from zipline.examples import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda/envs/zipline/lib/python3.4/site-packages/zipline/examples/__init__.py", line 17, in <module>
    mod = import_module('.' + modname, package=__name__)
  File "/anaconda/envs/zipline/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/anaconda/envs/zipline/lib/python3.4/site-packages/zipline/examples/dual_ema_talib.py", line 29, in <module>
    from talib import EMA
ImportError: No module named 'talib'
>>>

**Comment by richafrank** [comment]
Hi @johnwatson11218 , ta-lib is an optional dependency of zipline that's not encoded in our conda packages at all. Given that, `conda install ta-lib -c quantopian` should solve your immediate problem.

**Comment by willianpaixao** [comment]
@richafrank doing a quick search in Zipline's documentation, I couldn't find this information. Would be good to mention that in the ingesting page, isn't?

**Comment by richafrank** [comment]
Yea, it's [mentioned](https://github.com/quantopian/zipline/blob/a7a6fd2f33c0d318e167a32aa352d0d4ab0ecb41/docs/source/development-guidelines.rst#style-guide--running-tests) only in running tests locally, but would probably be good to mention elsewhere. Which parts of the docs were you using?

**Comment by willianpaixao** [comment]
@richafrank I was in the main docs and beginners' tutorial. Since @johnwatson11218 was running the examples, might be worth to write a small section on how and when running the examples, mentioning the TA-lib.
