### ISSUE TITLE
ingest ValueError: Boolean array expected, not float64

### ISSUE THREAD

**Issue by dickmao** [quantopian/zipline#2390]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Ubuntu 16.04
* Python Version: python 2.7.12
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages: 
alembic==1.0.5
bcolz==0.12.1
click==6.7
contextlib2==0.5.5
cyordereddict==1.0.0
Cython==0.29.1
cytoolz==0.8.2
decorator==4.3.0
empyrical==0.5.0
intervaltree==2.1.0
Logbook==1.4.1
lru-dict==1.1.6
Mako==1.0.7
MarkupSafe==1.0
msgpack-numpy==0.4.1
multipledispatch==0.6.0
networkx==1.11
numexpr==2.6.2
numpy==1.15.3
pandas==0.20.3
pandas-datareader==0.7.0
patsy==0.4.1
python-dateutil==2.6.1
pytz==2018.3
requests==2.18.4
requests-file==1.4.3
scipy==0.19.1
six==1.11.0
sortedcontainers==2.1.0
statsmodels==0.6.1
tables==3.4.4
toolz==0.9.0
trading-calendars==1.6.1

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen? No ValueError
* What happened instead? 
```
Downloading WIKI Prices table from Quandl  [####################################]  100%             
[2018-12-13 17:24:33.353637] INFO: zipline.data.bundles.quandl: Parsing raw data.
[2018-12-13 17:25:04.295182] INFO: zipline.data.bundles.quandl: Generating asset metadata.
Merging daily equity files:  [------------------------------------]
Traceback (most recent call last):
  File "/home/dick/.local/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "/home/dick/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dick/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dick/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dick/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dick/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/__main__.py", line 348, in ingest
    show_progress,
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/bundles/quandl.py", line 227, in quandl_bundle
    show_progress=show_progress
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 257, in write
    return self._write_internal(it, assets)
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 319, in _write_internal
    for asset_id, table in iterator:
  File "/home/dick/.local/lib/python2.7/site-packages/click/_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 249, in <genexpr>
    for sid, df in data
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 414, in to_ctable
    # we already have a ctable so do nothing
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 417, in to_ctable
    winsorise_uint32(raw_data, invalid_data_behavior, 'volume', *OHLC)
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 121, in winsorise_uint32
    
  File "/home/dick/.local/lib/python2.7/site-packages/zipline/data/us_equity_pricing.py", line 163, in winsorise_uint32
    df[mask] = 0
  File "/home/dick/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2328, in __setitem__
    self._setitem_frame(key, value)
  File "/home/dick/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 2366, in _setitem_frame
    self._where(-key, value, inplace=True)
  File "/home/dick/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 5098, in _where
    raise ValueError(msg.format(dtype=dt))
ValueError: Boolean array expected for the condition, not float64
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. QUANDL_API_KEY=\<your token\> zipline ingest
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by sbenthall** [comment]
I had this problem, and fixed it by switching to pandas==0.18.1

https://github.com/quantopian/zipline/issues/1870

**Comment by dickmao** [comment]
Thanks.  Apart from this abortive issue, I've since departed quantopian as their libraries cannot be local.  Closing.

**Comment by zoakes** [comment]
Hey guys, I can't even get the zipline bundles command to run in terminal.  What am I missing here? I can't get zipline alone to run
