### ISSUE TITLE
Can't run algorithm on custom future bundle

### ISSUE THREAD

**Issue by dancju** [quantopian/zipline#2405]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Linux dan-thinkpad 4.20.1-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 9 20:25:43 UTC 2019 x86_64 GNU/Linux
* Python Version: Python 3.4.9
* Python Bitness: 64
* How did you install Zipline: pip
* Python packages:
(part)
```
numpy==1.16.0
pandas==0.22.0
zipline==1.3.0
```

</details>

Now that you know a little about me, let me tell you about the issue I am having:

# Description of Issue

I created a custom bundle for BitMEX, the crypto-currency derivative exchange.

https://github.com/nerdDan/zipline-bitmex

The ingestion stage goes fine. But running an algorithm doesn't success. Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Install my package and ingest the bundle according to the README.
2. Create this minimum algorithm script.
```python
from zipline.api import (
    future_symbol,
    order,
)

def initialize(context):
    pass

def handle_data(context, data):
    order(future_symbol('XBTUSD'), 1)
```
3. Run the above script with command `zipline run -f tests/main.py -b bitmex -s 2019-1-1 -e 2019-1-2 --trading-calendar bitmex --data-frequency minute`.

This is the trace stack I got:

```
Traceback (most recent call last):
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/bin/zipline", line 11, in <module>
    sys.exit(main())
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/__main__.py", line 107, in _
    return f(*args, **kwargs)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/__main__.py", line 276, in run
    blotter=blotter,
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/utils/run_algo.py", line 229, in _run
    overwrite_sim_params=False,
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/algorithm.py", line 756, in run
    for perf in self.get_generator():
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/gens/tradesimulation.py", line 206, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/gens/tradesimulation.py", line 120, in every_bar
    blotter.get_transactions(current_data)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/finance/blotter/simulation_blotter.py", line 345, in get_transactions
    slippage.simulate(bar_data, asset, asset_orders):
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/finance/slippage.py", line 121, in simulate
    volume = data.current(asset, "volume")
  File "zipline/_protocol.pyx", line 121, in zipline._protocol.check_parameters.__call__.assert_keywords_and_call
  File "zipline/_protocol.pyx", line 332, in zipline._protocol.BarData.current
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/data/data_portal.py", line 524, in get_spot_value
    data_frequency,
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/data/data_portal.py", line 473, in _get_single_asset_value
    return self._get_minute_spot_value(asset, field, dt)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/data/data_portal.py", line 696, in _get_minute_spot_value
    return reader.get_value(asset.sid, dt, column)
  File "/home/dan/.local/share/virtualenvs/zipline-bitmex-2Y_l-Ngf/lib/python3.4/site-packages/zipline/data/dispatch_bar_reader.py", line 96, in get_value
    r = self._readers[type(asset)]
KeyError: <class 'zipline.assets._assets.Future'>
```

Sincerely,
dan

**Comment by bjschnei** [comment]
This fixes it, but it is probably a hack since it was never accepted.  Not sure why, or what the "right" fix really is.

https://github.com/quantopian/zipline/pull/1429/commits/7ec3d9c71e8fe76478d15b088878f82c71d8c1da

**Comment by nerddan** [comment]
> This fixes it, but it is probably a hack since it was never accepted. Not sure why, or what the "right" fix really is.
> 
> [7ec3d9c](https://github.com/quantopian/zipline/commit/7ec3d9c71e8fe76478d15b088878f82c71d8c1da)

Is this commit packed into pypi package?

**Comment by stocktrader8888** [comment]
Sadly, nobody seems to be creating any new releases for Zipline even though there have been hundreds of commits since version 1.3.0 was released on July 17, 2018.
