### ISSUE TITLE
Failed to install in python3

### ISSUE THREAD

**Issue by xttjsn** [quantopian/zipline#2413]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Linux localhost.localdomain 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: `Python 3.7.0`
* Python Bitness: `64`
* How did you install Zipline: (`pip`)
* Python packages: `Cython==0.29.3
numpy==1.16.1
pandas==0.24.0
pymongo==3.7.2
python-dateutil==2.7.5
pytz==2018.9
six==1.12.0
tornado==5.1.1
websockets==7.0`

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
I expect pip to successfully install zipline
* What happened instead?
After 1-2 minutes of numpy compilation, it failed.
Here's the log
```
      compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inump
y/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inum
py/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umat
h -Inumpy/core/src/npysort -I/usr/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/pr
ivate -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/s
rc/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/c
ore/src/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c'                           
      gcc: numpy/random/mtrand/mtrand.c
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
      numpy/random/mtrand/mtrand.c:44374:13: error: too many arguments to function ‘(PyObject * (*)
(PyObject *, PyObject * const*, Py_ssize_t))meth’                                                 
           return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
      numpy/random/mtrand/mtrand.c:44793:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
      numpy/random/mtrand/mtrand.c:44794:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           *value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
      numpy/random/mtrand/mtrand.c:44795:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           *tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionReset’:
      numpy/random/mtrand/mtrand.c:44802:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44803:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44804:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44805:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tstate->exc_type = type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44806:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tstate->exc_value = value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44807:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tstate->exc_traceback = tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__GetException’:
      numpy/random/mtrand/mtrand.c:44862:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44863:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44864:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44865:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tstate->exc_type = local_type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44866:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tstate->exc_value = local_value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44867:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tstate->exc_traceback = local_tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx_PyCFunction_FastCall’:
      numpy/random/mtrand/mtrand.c:44374:13: error: too many arguments to function ‘(PyObject * (*)
(PyObject *, PyObject * const*, Py_ssize_t))meth’                                                 
           return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
      numpy/random/mtrand/mtrand.c:44793:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
      numpy/random/mtrand/mtrand.c:44794:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           *value = tstate->exc_value;
                            ^~~~~~~~~
                            curexc_value
      numpy/random/mtrand/mtrand.c:44795:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           *tb = tstate->exc_traceback;
                         ^~~~~~~~~~~~~
                         curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionReset’:
      numpy/random/mtrand/mtrand.c:44802:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44803:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44804:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44805:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tstate->exc_type = type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44806:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tstate->exc_value = value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44807:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tstate->exc_traceback = tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__GetException’:
      numpy/random/mtrand/mtrand.c:44862:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tmp_type = tstate->exc_type;
                              ^~~~~~~~
                              curexc_type
      numpy/random/mtrand/mtrand.c:44863:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tmp_value = tstate->exc_value;
                               ^~~~~~~~~
                               curexc_value
      numpy/random/mtrand/mtrand.c:44864:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tmp_tb = tstate->exc_traceback;
                            ^~~~~~~~~~~~~
                            curexc_traceback
      numpy/random/mtrand/mtrand.c:44865:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_type’; did you mean ‘curexc_type’?                                                   
           tstate->exc_type = local_type;
                   ^~~~~~~~
                   curexc_type
      numpy/random/mtrand/mtrand.c:44866:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_value’; did you mean ‘curexc_value’?                                                 
           tstate->exc_value = local_value;
                   ^~~~~~~~~
                   curexc_value
      numpy/random/mtrand/mtrand.c:44867:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no membe
r named ‘exc_traceback’; did you mean ‘curexc_traceback’?                                         
           tstate->exc_traceback = local_tb;
                   ^~~~~~~~~~~~~
                   curexc_traceback
      error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=
1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERT
IONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-
hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwin
d-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -W
error=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protec
tor-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm
/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protectio
n -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -flto -fuse-linker-plugin -ffat-lto-objects -flto-par
tition=none -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core
/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/cor
e/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inu
mpy/core/src/npysort -I/usr/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/private 
-Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/pri
vate -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/sr
c/private -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c numpy/random/mtrand/mtrand.c -o bu
ild/temp.linux-x86_64-3.7/numpy/random/mtrand/mtrand.o -MMD -MF build/temp.linux-x86_64-3.7/numpy/r
andom/mtrand/mtrand.o.d" failed with exit status 1                                                
      Running setup.py install for numpy: finished with status 'error'
  Cleaning up...
    Removing source in /tmp/pip-install-cfk0h6uf/numpy
  Cleaned build tracker '/tmp/pip-req-tracker-neszqcro'
  Command "/home/xttjsn/.py3/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-inst
all-cfk0h6uf/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\
n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-35dh2me
6/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-r7oiy8br/overl
ay --compile --install-headers /home/xttjsn/.py3/include/site/python3.7/numpy" failed with error co
de 1 in /tmp/pip-install-cfk0h6uf/numpy/                                                          
  Exception information:
  Traceback (most recent call last):
    File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 17
6, in main                                                                                        
      status = self.run(options, args)
    File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 39
3, in run                                                                                         
      use_user_site=options.use_user_site,
    File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in
 install_given_reqs                                                                               
      **kwargs
    File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 951
, in install                                                                                      
      spinner=spinner,
    File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in 
call_subprocess                                                                                   
      % (command_desc, proc.returncode, cwd))
  pip._internal.exceptions.InstallationError: Command "/home/xttjsn/.py3/bin/python3 -u -c "import 
setuptools, tokenize;__file__='/tmp/pip-install-cfk0h6uf/numpy/setup.py';f=getattr(tokenize, 'open'
, open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'
))" install --record /tmp/pip-record-35dh2me6/install-record.txt --single-version-externally-manage
d --prefix /tmp/pip-build-env-r7oiy8br/overlay --compile --install-headers /home/xttjsn/.py3/includ
e/site/python3.7/numpy" failed with error code 1 in /tmp/pip-install-cfk0h6uf/numpy/              
error
Cleaning up...
  Removing source in /tmp/pip-install-ctbuo8y3/zipline
  Removing source in /tmp/pip-install-ctbuo8y3/Logbook
  Removing source in /tmp/pip-install-ctbuo8y3/pandas
Removed pandas<=0.22,>=0.18.1 from https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aed
ebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz#sha256=44a94091dd71f05922eec661638e
c1a35f26d573c119aa2fad964f10a2880e6c (from zipline) from build tracker '/tmp/pip-req-tracker-neszqc
ro'                                                                                               
Removed build tracker '/tmp/pip-req-tracker-neszqcro'
Command "/home/xttjsn/.py3/bin/python3 /home/xttjsn/.py3/lib/python3.7/site-packages/pip install --
ignore-installed --no-user --prefix /tmp/pip-build-env-r7oiy8br/overlay --no-warn-script-location -
v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools Cython "nu
mpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; python_version=='3.6'" "numpy==1.13.1; python_ve
rsion>='3.7'"" failed with error code 1 in None                                                   
Exception information:
Traceback (most recent call last):
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 176,
 in main                                                                                          
    status = self.run(options, args)
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315,
 in run                                                                                           
    resolver.resolve(requirement_set)
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resol
ve                                                                                                
    self._resolve_one(requirement_set, req)
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _reso
lve_one                                                                                           
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_
abstract_dist_for                                                                                 
    self.require_hashes
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 34
9, in prepare_linked_requirement                                                                  
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 12
5, in prep_for_dist                                                                               
    "Installing build dependencies"
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/build_env.py", line 195, in ins
tall_requirements                                                                                 
    call_subprocess(args, show_stdout=False, spinner=spinner)
  File "/home/xttjsn/.py3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in ca
ll_subprocess                                                                                     
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/xttjsn/.py3/bin/python3 /home/xttjsn/.py
3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-
r7oiy8br/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://py
pi.org/simple -- wheel setuptools Cython "numpy==1.9.3; python_version=='3.5'" "numpy==1.12.1; pyth
on_version=='3.6'" "numpy==1.13.1; python_version>='3.7'"" failed with error code 1 in None 
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. $ pip install zipline
2.
3.
...

## What steps have you taken to resolve this already?
None
...

# Anything else?

...

Sincerely,
`xttjsn`

**Comment by freddiev4** [comment]
Hi @xttjsn your Python version is 3.7, but Zipline only has support for Python 2.7 and 3.5. Can you try installing in a Python 3.5 virtualenv or conda env?

Also make sure you have the necessary [dependencies](http://www.zipline.io/install.html#gnu-linux)

**Comment by xttjsn** [comment]
Thanks!

**Comment by linuxokey** [comment]
pls support py3.7 :)

**Comment by ssanderson** [comment]
I've opened an issue to track the desire for newer Python version support here: https://github.com/quantopian/zipline/issues/2616.
