### ISSUE TITLE
AttributeError: module 'pywatchman' has no attribute 'client'

### ISSUE THREAD

**Issue by Mgaya123** [quantopian/zipline#2425]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 10
* Python Version: 3.6.8
* Python Bitness: 32
* How did you install Zipline: pip
* Python packages: 

colorama   0.3.7
django     2.2a1
pip        19.0.2
pytz       2018.9
setuptools 40.8.0
sh         1.12.0
sqlparse   0.2.4
watchman   0.0.8
wheel      0.33.0

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
  Am testing an app by running python manage.py runserver
* What happened instead?
  I get an error written as "AttributeError: module 'pywatchman' has no attribute 'client'"

full error message
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\commands\runserver.py", line 95, in handle
    self.run(**options)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\core\management\commands\runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\utils\autoreload.py", line 581, in run_with_reloader
    WatchmanReloader.check_availability()
  File "C:\Users\J0FREY\lib\site-packages\django-2.2a1-py3.6.egg\django\utils\autoreload.py", line 530, in check_availability
    client = pywatchman.client(timeout=0.01)
AttributeError: module 'pywatchman' has no attribute 'client'

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?
1. I have tried to install pywatchman package by typing "pip install pywatchman", got error message written " error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads"
2. I have installed microsoft visual C++ but still got the same error
...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by richafrank** [comment]
Hi @Mgaya123 , I notice you don't have zipline installed, and the traceback doesn't mention zipline. Based on the traceback, this looks like maybe an issue between django and pywatchman, so I'm going to close this zipline issue. If you think otherwise, feel free to re-open and explain. Thanks!
