### ISSUE TITLE
Ingest data error: The 'lxml' distribution not found

### ISSUE THREAD

**Issue by timtobey** [quantopian/zipline#2427]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: Windows 
* Python Version: `$ 3.5
* How did you install Zipline: Conda
* Python packages: 
Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_3    conda-forge
bcolz                     0.12.1              np114py35_0    Quantopian
blas                      1.0                         mkl
blosc                     1.15.1            h6538335_1002    conda-forge
bottleneck                1.2.1            py35hc8d92b1_1    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
cffi                      1.11.5           py35hfa6e2cd_1    conda-forge
chardet                   3.0.4                    py35_3    conda-forge
click                     7.0                        py_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.3.1            py35h74b6da3_0    conda-forge
cryptography-vectors      2.3.1                    py35_0    conda-forge
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h6538335_0    conda-forge
decorator                 4.3.2                      py_0    conda-forge
empyrical                 0.5.0                    py35_0    Quantopian
hdf5                      1.10.2               he51fdeb_2    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.7                      py35_2    conda-forge
intel-openmp              2019.1                      144
intervaltree              2.1.0                    py35_0    Quantopian
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
mako                      1.0.7                      py_1    conda-forge
markupsafe                1.0              py35hfa6e2cd_1    conda-forge
mkl                       2018.0.3                      1
mkl_fft                   1.0.9                    py35_0    conda-forge
mkl_random                1.0.1                    py35_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
networkx                  1.11                     py35_0    conda-forge
numexpr                   2.6.1               np114py35_0    Quantopian
numpy                     1.14.6           py35hc27ee41_4
numpy-base                1.14.6           py35h8128ebf_4
openssl                   1.0.2p            hfa6e2cd_1002    conda-forge
pandas                    0.22.0                   py35_1    conda-forge
pandas-datareader         0.6.0                    py35_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pip                       18.0                  py35_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                   py35_0    conda-forge
pysocks                   1.6.8                    py35_2    conda-forge
pytables                  3.4.4            py35h7e76658_1    conda-forge
python                    3.5.5                he025d50_2    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
requests                  2.20.1                   py35_0    Quantopian
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0    conda-forge
scipy                     1.1.0            py35hc28095f_0
setuptools                40.4.3                   py35_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
sortedcontainers          1.4.4                    py35_0    Quantopian
sqlalchemy                1.2.12           py35hfa6e2cd_0    conda-forge
statsmodels               0.9.0                    py35_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
trading-calendars         1.6.1                    py35_0    Quantopian
urllib3                   1.23                     py35_1    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.32.0                py35_1000    conda-forge
win_inet_pton             1.0.1                    py35_2    conda-forge
wincertstore              0.2                   py35_1002    conda-forge
zipline                   1.3.0               np114py35_0    Quantopian
zlib                      1.2.11            h2fa13f4_1004    conda-forge

#Now that you know a little about me, let me tell you about the issue I am
having:
Cannot ingest data;
* What did you expect to happen? Data Ingestion
* What happened instead?
The following error:
(my_zip_env) C:\Users\tim>zipline ingest -b quandl
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\Scripts\zipline-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\lib\site-packages\pkg_resources\__init__.py", line 3112, in <module>
    @_call_aside
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\lib\site-packages\pkg_resources\__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\lib\site-packages\pkg_resources\__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\lib\site-packages\pkg_resources\__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\lib\site-packages\pkg_resources\__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\ProgramData\Anaconda3\envs\my_zip_env\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'lxml' distribution was not found and is required by pandas-datareader
Here is how you can reproduce this issue on your machine:

## Reproduction Steps
<details>
1. Conda Install Zipline
2.  set QUANDL_API_KEY= <My Quandl key>
3. zipline ingest -b quandl

Sincerely,
Tim

**Comment by Swalloow** [comment]
Have you tried installing lxml? (`pip install lxml`)
