### ISSUE TITLE
Cannot run test_csvdir.py

### ISSUE THREAD

**Issue by pannefr** [quantopian/zipline#2466]

**Comment by pannefr** [comment]
When I run the file I get this output:

| AAPL: sid 0
 | IBM: sid 1
 | KO: sid 2
 | MSFT: sid 3
C:\Users\pannefr\AppData\Local\Continuum\anaconda3\envs\zipline_py35\lib\site-packages\zipline\data\us_equity_pricing.py:931: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not issubdtype(actual, expected):
Traceback (most recent call last):
  File "C:/Users/pannefr/AppData/Local/Continuum/anaconda3/envs/zipline_py35/Lib/site-packages/tests/data/bundles/test_csvdir.py", line 133, in <module>
    t.test_bundle()
  File "C:/Users/pannefr/AppData/Local/Continuum/anaconda3/envs/zipline_py35/Lib/site-packages/tests/data/bundles/test_csvdir.py", line 125, in test_bundle
    adjs_for_cols = bundle.adjustment_reader.load_pricing_adjustments(
AttributeError: 'SQLiteAdjustmentReader' object has no attribute 'load_pricing_adjustments'

Process finished with exit code 1

I am able to "fix it" by changing on line 125:
adjs_for_cols = bundle.adjustment_reader.load_pricing_adjustments(

by

adjs_for_cols = bundle.adjustment_reader.load_adjustments(
