### ISSUE TITLE
Anaconda install of zipline fails with Conda v4.7.x

### ISSUE THREAD

**Issue by RichardDale** [quantopian/zipline#2514]
Environment: Windows 10 64 bit, Anaconda 2017.09, Conda package in base updated to v4.7.10

Even after creating a pristine Python 3.5 environment created within Anaconda, then opening that up environment, trying to install using:
conda install zipline -c quantopian
fails with a few screenfuls of dependencies showing as conflicting.

There is a workaround:
conda config --set allow_conda_downgrades true
conda install conda=4.6.11

Conda v4.7 tracks explicit version dependencies a lot more precisely, plus also has some additional changes with regards to shims.

**Comment by fritzybloch** [comment]
This workaround in not working for me.  conda refuses to downgrade.  Is there anything else I can try?

**Comment by Uncolonized** [comment]
This worked for me. Thank you.

**Comment by bbeale** [comment]
Having this same issue running Ubuntu 19.04.

**Comment by JonathanBarringer** [comment]
Running into issues with the workaround also. trying to install conda=4.6.11, Specifications found to be incompatible with existing python installation in environment.

created a clean python 3.5 environment. Running windows. current version conda 4.7.11

Any ideas on what to try?

**Comment by rogerjbos** [comment]
I don't have the link handy, but you have to downgrade to conda 4.6.11 and
then it will install.  However I got it to install, but I can't run any
backrests.  Zipline is very tricky to get working.

**Comment by oski89** [comment]
Having the same issue. Tried the workaround (downgrading conda to 4.6.11) but had this error:

```
The following packages will be DOWNGRADED:

  anaconda                                   2018.12-py37_0 --> custom-py37_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.
```
Any ideas?

**Comment by JonathanBarringer** [comment]
I haven't seen zipline working with py37, try py35.

I ended up successfully installing without downgrading conda to 4.6.11 on my windows 10 using anaconda in a py35 environment. 

After creating new py35 environment with anaconda navigator, these steps:

$ conda install pandas=0.18.1
$ conda install -c Quantopian zipline=1.03
$ conda install pandas-datareader=0.21

For some reason I had to downgrade pandas-datareader to 0.21

**Comment by StarenseN** [comment]
> This workaround in not working for me. conda refuses to downgrade. Is there anything else I can try?

I had same issue with Windows CMD console.

But I found how to downgrade by launching "anaconda powershell prompt" (in admin mode). From there with the same commands: 

conda config --set allow_conda_downgrades true
conda install conda=4.6.11

Everything went smoothly and conda install was downgraded. Followed by zipline installation.

**Comment by alexgand** [comment]
Can't downgrade conda on windows, even on adm console. Error:

Solving environment: failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
  - pip -> python[version='>=3.7,<3.8.0a0']

**Comment by lalopey** [comment]
> i

Are you trying to downgrade outside of your base environment? I switched to base and had no problems.

**Comment by lalopey** [comment]
> Can't downgrade conda on windows, even on adm console. Error:
> 
> Solving environment: failed
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> * pip -> python[version='>=3.7,<3.8.0a0']
> 
> I have a base env with python 3.7, and a "zip" env activated with python 3.5

Have you tried downgrading on your base environment?

**Comment by alexgand** [comment]
> 
> 
> > Can't downgrade conda on windows, even on adm console. Error:
> > Solving environment: failed
> > UnsatisfiableError: The following specifications were found to be incompatible with each other:
> > 
> > * pip -> python[version='>=3.7,<3.8.0a0']
> > 
> > I have a base env with python 3.7, and a "zip" env activated with python 3.5
> 
> Have you tried downgrading on your base environment?

That was the problem, I was downgrading in the "zip" env. On base env it worked, thanks!

**Comment by emhayman** [comment]
I had a working copy of Python 3.5 with Zipline for the past couple months.  Unfortunately, I had upgraded a module and the environment was no longer fully functional for doing my zipline backtest tearsheats.  As such, I removed and tried to re-install Python and Zipline.  I have tried for the past two days and cannot get a working environment anymore.  I have tried the ideas posted in Andrea's post on Quantopian at https://www.quantopian.com/posts/new-book-on-quantopian-slash-zipline-backtesting-and-modeling along with the ideas above.  

In following the instructions in this thread, I did the following:
1) uninstall all prior copies of python, anaconda
2) install latest version of anaconda/python (2019-10 / 3.7)
3) (base) conda create -n env_zipline python=3.5
4) (base) conda config --set allow_conda_downgrades true
5) (base) conda install conda=4.6.11
6) (env_zipline) conda install pandas=0.18.1
7) (env_zipline) conda install -c Quantopian zipline=1.03

During the conda zipline install, the "package" is downgrading my Python to version 2.7.1!  :(
Has the Quantopian package changed?
Any ideas or suggestions?

**Comment by hiuky1** [comment]
I got the following error: 
-----
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - conda=4.6.11 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==9.2=0
  - feature:|@/win-64::__cuda==9.2=0

Your installed CUDA driver is: 9.2
-----

Any help would be great. thanks!

**Comment by EMCP** [comment]
getting an error on `conda install -c quantopian zipline`

```
conda install -c Quantopian zipline --verbose
Collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/Quantopian/osx-64/current_repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                          
Traceback (most recent call last):
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 696, in _add_specs
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True
           

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 308, in install
    raise e
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
    should_retry_solve=(repodata_fn != repodata_fns[-1]),
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 694, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "/Users/emcp/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 351, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - zipline -> python[version='2.7.*|3.4.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.4,<3.5.0a0|3.3.*']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```
