### ISSUE TITLE
Error ingesting default bundle

### ISSUE THREAD

**Issue by cmcavoy** [quantopian/zipline#2519]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: OSX 10.14.6
* Python Version: Python 3.5.4 :: Continuum Analytics, Inc.
* Python Bitness: 64
* How did you install Zipline: conda
* Python packages: 

```
alembic                   0.7.7                    py35_0    Quantopian
bcolz                     0.12.1          np111py35ha35bb93_0    Quantopian
blas                      1.0                         mkl
bottleneck                1.2.1               np111py35_0
certifi                   2016.2.28                py35_0
click                     6.7                      py35_0
contextlib2               0.5.5                    py35_0
cyordereddict             0.2.2            py35hecbb3fb_0    Quantopian
cython                    0.26                     py35_0
decorator                 4.1.2                    py35_0
empyrical                 0.5.0                    py35_0    Quantopian
hdf5                      1.8.17                        2
intervaltree              2.1.0            py35h0acdb32_0    Quantopian
logbook                   0.12.5           py35h7b3d7f6_0    Quantopian
lru-dict                  1.1.4            py35hdf719cb_0    Quantopian
mako                      1.0.6                    py35_0
markupsafe                1.0                      py35_0
mkl                       2017.0.3                      0
multipledispatch          0.4.9                    py35_0
networkx                  1.11                     py35_0
numexpr                   2.6.2               np111py35_0
numpy                     1.11.3                   py35_0
openssl                   1.0.2l                        0
pandas                    0.20.1              np111py35_0
pandas-datareader         0.5.0                    py35_0
patsy                     0.4.1                    py35_0
pip                       9.0.1                    py35_1
pytables                  3.3.0               np111py35_0
python                    3.5.4                         0
python-dateutil           2.6.1                    py35_0
pytz                      2017.2                   py35_0
readline                  6.2                           2
requests                  2.14.2                   py35_0
requests-file             1.4.1                    py35_0
requests-ftp              0.3.1                    py35_0
scipy                     0.19.0              np111py35_0
setuptools                36.4.0                   py35_1
six                       1.10.0                   py35_0
sortedcontainers          1.5.7                    py35_0
sqlalchemy                1.1.13                   py35_0
sqlite                    3.13.0                        0
statsmodels               0.8.0               np111py35_0
tk                        8.5.18                        0
toolz                     0.8.2                    py35_0
trading-calendars         1.5.1                    py35_0    Quantopian
wheel                     0.29.0                   py35_0
xz                        5.2.3                         0
zipline                   1.3.0               np111py35_0    Quantopian
zlib                      1.2.11                        0
```

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
Error ingesting default quandl bundle. Cut and paste of error,

```
[2019-08-08 20:03:12.482232] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
Downloading WIKI Prices table from Quandl  [####################################]  100%
[2019-08-08 20:03:35.798543] INFO: zipline.data.bundles.quandl: Parsing raw data.
[2019-08-08 20:05:26.555347] INFO: zipline.data.bundles.quandl: Generating asset metadata.
Merging daily equity files:  [------------------------------------]
Traceback (most recent call last):
  File "/Users/m_563107/anaconda/envs/env_zipline/bin/zipline", line 11, in <module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/__main__.py", line 348, in ingest
    show_progress,
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/bundles/quandl.py", line 227, in quandl_bundle
    show_progress=show_progress
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 257, in write
    return self._write_internal(it, assets)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 319, in _write_internal
    for asset_id, table in iterator:
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/click/_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 249, in <genexpr>
    for sid, df in data
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 414, in to_ctable
    # we already have a ctable so do nothing
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 417, in to_ctable
    winsorise_uint32(raw_data, invalid_data_behavior, 'volume', *OHLC)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 121, in winsorise_uint32

  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/zipline/data/us_equity_pricing.py", line 163, in winsorise_uint32
    df[mask] = 0
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/pandas/core/frame.py", line 2426, in __setitem__
    self._setitem_frame(key, value)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/pandas/core/frame.py", line 2464, in _setitem_frame
    self._where(-key, value, inplace=True)
  File "/Users/m_563107/anaconda/envs/env_zipline/lib/python3.5/site-packages/pandas/core/generic.py", line 4953, in _where
    raise ValueError(msg.format(dtype=dt))
ValueError: Boolean array expected for the condition, not float64
```
* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
Chris
![bitmoji](https://render.bitstrips.com/v2/cpanel/2f5d439d-f034-4816-9b09-3e1b32ec86ed-a49e93f3-bb3f-47d0-8ebf-b28a3358afca-v1.png?transparent=1&palette=1&width=246)

**Comment by cmcavoy** [comment]
This is a dupe of https://github.com/quantopian/zipline/issues/2390

After I downgraded to Pandas 0.18.1, the ingest worked fine.
