### ISSUE TITLE
buyapple.py backtest not running on CLI or from notebook

### ISSUE THREAD

**Issue by rogerjbos** [quantopian/zipline#2524]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: 3.5
* Python Bitness: 64
* How did you install Zipline: conda
* Python packages: `$ pip freeze` or `$ conda list`

alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_0  
backcall                  0.1.0                    py35_0  
bcolz                     0.12.1              np114py35_0    Quantopian
blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/free
bleach                    2.1.4                    py35_0  
blosc                     1.16.3               h7bd577a_0  
bottleneck                1.2.1            py35h452e1ab_1  
bzip2                     1.0.8                he774522_0  
ca-certificates           2019.5.15                     1  
certifi                   2018.8.24                py35_1  
cffi                      1.11.5           py35h74b6da3_1  
chardet                   3.0.4                    py35_1  
click                     6.7              py35h10df73f_0  
colorama                  0.3.9            py35h32a752f_0  
contextlib2               0.5.5            py35h0a97e54_0  
cryptography              2.3.1            py35h74b6da3_0  
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h6538335_0  
decorator                 4.4.0                      py_0  
defusedxml                0.6.0                      py_0  
empyrical                 0.5.0                    py35_0    Quantopian
entrypoints               0.2.3                    py35_2  
hdf5                      1.10.2               hac2f561_1  
html5lib                  1.0.1                    py35_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
idna                      2.7                      py35_0  
intel-openmp              2019.4                      245  
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 4.10.0                   py35_0  
ipython                   6.5.0                    py35_0  
ipython_genutils          0.2.0            py35ha709e79_0  
ipywidgets                7.4.1                    py35_0  
jedi                      0.12.1                   py35_0  
jinja2                    2.10                     py35_0  
jpeg                      9b                   hb83a4c4_2  
jsonschema                2.6.0            py35h27d56d3_0  
jupyter                   1.0.0                    py35_7  
jupyter_client            5.3.1                      py_0  
jupyter_console           5.2.0                    py35_1  
jupyter_core              4.5.0                      py_0  
libiconv                  1.15                 h1df5818_7  
libpng                    1.6.37               h2a8f88b_0  
libsodium                 1.0.16               h9d3ae62_0  
libxml2                   2.9.9                h464c3ec_0  
libxslt                   1.1.33               h579f668_0  
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lxml                      4.2.5            py35hef2cd61_0  
lz4-c                     1.8.1.2              h2fa13f4_0  
lzo                       2.10                 h6df0209_2  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gmp                 6.1.0                         2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
mako                      1.0.10                     py_0  
markupsafe                1.0              py35hfa6e2cd_1  
mistune                   0.8.3            py35hfa6e2cd_1  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6            py35hdbbee80_0  
mkl_random                1.0.1            py35h77b88f5_1  
msys2-conda-epoch         20160418                      1  
multipledispatch          0.6.0                    py35_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0            py35h908c9d9_0  
networkx                  1.11                     py35_1  
notebook                  5.6.0                    py35_0  
numexpr                   2.6.1               np114py35_0    Quantopian
numpy                     1.14.6           py35hc27ee41_4  
numpy-base                1.14.6           py35h8128ebf_4  
openssl                   1.0.2s               he774522_0  
pandas                    0.22.0           py35h6538335_0  
pandas-datareader         0.6.0                    py35_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py35_1  
parso                     0.5.1                      py_0  
patsy                     0.5.0                    py35_0  
pickleshare               0.7.4            py35h2f9f535_0  
pip                       10.0.1                   py35_0  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            1.0.15           py35h89c7cb4_0  
pycparser                 2.19                     py35_0  
pygments                  2.4.2                      py_0  
pyopenssl                 18.0.0                   py35_0  
pyqt                      5.9.2            py35h6538335_2  
pysocks                   1.6.8                    py35_0  
pytables                  3.4.4            py35he6f6034_0  
python                    3.5.6                he025d50_0  
python-dateutil           2.7.3                    py35_0  
pytz                      2019.2                     py_0  
pywinpty                  0.5.4                    py35_0  
pyzmq                     17.1.2           py35hfa6e2cd_0  
qt                        5.9.6            vc14h1e9a669_2  
qtconsole                 4.5.4                      py_0  
requests                  2.20.1                   py35_0    Quantopian
requests-file             1.4.3                    py35_0  
requests-ftp              0.3.1                    py35_0    https://repo.anaconda.com/pkgs/free
scipy                     1.1.0            py35hc28095f_0  
send2trash                1.5.0                    py35_0  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
sip                       4.19.8           py35h6538335_0  
six                       1.11.0                   py35_1  
snappy                    1.1.7                h777316e_3  
sortedcontainers          1.4.4                    py35_0    Quantopian
sqlalchemy                1.2.11           py35hfa6e2cd_0  
sqlite                    3.29.0               he774522_0  
statsmodels               0.9.0            py35h452e1ab_0  
ta-lib                    0.4.9               np114py35_0    quantopian
terminado                 0.8.1                    py35_1  
testpath                  0.3.1            py35h06cf69e_0  
toolz                     0.10.0                     py_0  
tornado                   5.1.1            py35hfa6e2cd_0  
trading-calendars         1.8.1                    py35_0    Quantopian
traitlets                 4.3.2            py35h09b975b_0  
urllib3                   1.23                     py35_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
wcwidth                   0.1.7            py35h6e80d8a_0  
webencodings              0.5.1                    py35_1  
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.4.1                    py35_0  
win_inet_pton             1.0.1                    py35_1  
win_unicode_console       0.5              py35h56988b5_0  
wincertstore              0.2              py35hfebbdb8_0  
winpty                    0.4.3                         4  
wrapt                     1.10.11          py35hfa6e2cd_2  
xz                        5.2.4                h2fa13f4_4  
zeromq                    4.2.5                he025d50_1  
zipline                   1.3.0               np114py35_0    Quantopian
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

Cannot run the buyapple.py example from [this tutorial](https://www.zipline.io/beginner-tutorial.html) from the CLI or from a notebook.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

CLI command:

zipline run -f C:\Users\bosr\.conda\envs\py35\Lib\site-packages\zipline\examples\buyapple.py --start 2016-1-1 --end 2018-1-1

gives the following errors:

[2019-08-26 19:48:01.637630] INFO: Loader: Cache at C:\Users\bosr/.zipline\data\
SPY_benchmark.csv does not have data from 2016-01-04 00:00:00+00:00 to 2017-12-2
9 00:00:00+00:00.

[2019-08-26 19:48:01.637630] INFO: Loader: Downloading benchmark data for 'SPY'
from 2015-12-31 00:00:00+00:00 to 2017-12-29 00:00:00+00:00
Traceback (most recent call last):
  File "C:\Users\bosr\.conda\envs\py35\Scripts\zipline-script.py", line 11, in <
module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\click\core.py", line 72
2, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\click\core.py", line 69
7, in main
    rv = self.invoke(ctx)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\click\core.py", line 10
66, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\click\core.py", line 89
5, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\click\core.py", line 53
5, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\__main__.py", l
ine 107, in _
    return f(*args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\click\decorators.py", l
ine 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\__main__.py", l
ine 276, in run
    blotter=blotter,
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\utils\run_algo.
py", line 159, in _run
    trading_days=trading_calendar.schedule[start:end].index,
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\finance\trading
.py", line 103, in __init__
    self.bm_symbol,
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\data\loader.py"
, line 149, in load_market_data
    environ,
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\data\loader.py"
, line 216, in ensure_benchmark_data
    data = get_benchmark_returns(symbol)
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\zipline\data\benchmarks
.py", line 35, in get_benchmark_returns
    data = r.json()
  File "C:\Users\bosr\.conda\envs\py35\lib\site-packages\requests\models.py", li
ne 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\bosr\.conda\envs\py35\lib\json\__init__.py", line 319, in loads

    return _default_decoder.decode(s)
  File "C:\Users\bosr\.conda\envs\py35\lib\json\decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\bosr\.conda\envs\py35\lib\json\decoder.py", line 357, in raw_de
code
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(py35) C:\Users\bosr>

From within jupyter notebook (using VS Code) I get a problem with %%zipline

import zipline

%load_ext zipline...
The zipline extension is already loaded. To reload it, use:  %reload_ext zipline

%%zipline --start 2016-01-01 --end 2018-01-01 -example.pickle...
UsageError: %%zipline is a cell magic, but the cell body is empty. Did you mean the line magic %zipline (single %)?

## What steps have you taken to resolve this already?

I had a hard time installing zipline until I figured out it only works with python 3.5 and conda 4.6.11, so I wrote a quick tutorial for myself outlining the steps:

Zipline needs a python 3.5 environment (not 3.6 or 3.7)
```
conda create -n py35 python=3.5
activate py35
```

Conda 4.7+ won't work because it is too strict with conflicts, so downgrade to Conda to 4.6.11
```
conda config --set allow_conda_downgrades true
conda install conda=4.6.11
conda --version # Should say 4.6.11
```

Now you can finally install zipline and it should work
```
conda install -c Quantopian zipline
```

Set up your quandl key
```
set QUANDL_API_KEY=your_key_here
```

Download demo data
```
zipline ingest -b quandl
```

Install jupyter modules
```
conda install jupyter # while in the py35 environment
```

Install talib module
```
conda install ta-lib -c quantopian 
```

Sincerely,
rogerjbos

**Comment by rogerjbos** [comment]
All,
I tried to install zipline in a py27 virtual environment and it went fine, set my quandl api key, ingested the quandl bundle, but the buyapple.py example still gives errors.  It says that the SPY_benchmark.csv does not have data from .... When I go to that folder, there is no file called SPY_benchmark.csv.  Should there be?  Can anyone post what the command line output of buyapply.py should be?

Thanks in advance!

(py27) C:\Users\bosr\.conda\envs\py27\Lib\site-packages\zipline\examples>zipline
 run -f buyapple.py --start 2016-1-1 --end 2018-1-1 -o buyapple_out.pickle
[2019-08-29 20:12:34.590000] INFO: Loader: Cache at C:\Users\bosr/.zipline\data\
SPY_benchmark.csv does not have data from 2016-01-04 00:00:00+00:00 to 2017-12-2
9 00:00:00+00:00.

[2019-08-29 20:12:34.591000] INFO: Loader: Downloading benchmark data for 'SPY'
from 2015-12-31 00:00:00+00:00 to 2017-12-29 00:00:00+00:00
Traceback (most recent call last):
  File "C:\Users\bosr\.conda\envs\py27\Scripts\zipline-script.py", line 11, in <
module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\click\core.py", line 76
4, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\click\core.py", line 71
7, in main
    rv = self.invoke(ctx)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\click\core.py", line 11
37, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\click\core.py", line 95
6, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\click\core.py", line 55
5, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\__main__.py", l
ine 107, in _
    return f(*args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\click\decorators.py", l
ine 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\__main__.py", l
ine 276, in run
    blotter=blotter,
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\utils\run_algo.
py", line 159, in _run
    trading_days=trading_calendar.schedule[start:end].index,
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\finance\trading
.py", line 103, in __init__
    self.bm_symbol,
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\data\loader.py"
, line 149, in load_market_data
    environ,
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\data\loader.py"
, line 216, in ensure_benchmark_data
    data = get_benchmark_returns(symbol)
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\zipline\data\benchmarks
.py", line 35, in get_benchmark_returns
    data = r.json()
  File "C:\Users\bosr\.conda\envs\py27\lib\site-packages\requests\models.py", li
ne 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\bosr\.conda\envs\py27\lib\json\__init__.py", line 339, in loads

    return _default_decoder.decode(s)
  File "C:\Users\bosr\.conda\envs\py27\lib\json\decoder.py", line 364, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\bosr\.conda\envs\py27\lib\json\decoder.py", line 382, in raw_de
code
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

(py27) C:\Users\bosr\.conda\envs\py27\Lib\site-packages\zipline\examples>
