### ISSUE TITLE
Most basic examples don't work in local zipline installation

### ISSUE THREAD

**Issue by richdevboston** [quantopian/zipline#2533]
Dear Zipline Maintainers,

Zipline local installs and shows various modules and methods at the zipline.module command line in Jupyter.  However, zipline.examples is missing

My environment:
# Python 3.5, Pandas 0.22, zipline (latest 1.3.0)
* Operating System: (Windows 10 64-bit)
* Python 64-bit
`conda` installation
* Python packages: `$ pip freeze` or `$ conda list`

>> conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\quant_trader:
#
# Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    quantopian
alphalens                 0.3.6                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcolz                     0.12.1              np111py35_0    quantopian
blas                      1.0                         mkl
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.17.0               h6538335_1    conda-forge
bottleneck                1.2.1            py35h452e1ab_1    conda-forge
bzip2                     1.0.8                hfa6e2cd_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
click                     7.0                        py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
contextlib2               0.5.5                      py_2    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cyordereddict             0.2.2                    py35_0    quantopian
cython                    0.28.5           py35h6538335_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
empyrical                 0.5.0                    py35_0    quantopian
entrypoints               0.2.3                    py35_2    conda-forge
freetype                  2.6.3                    vc14_1    conda-forge
h5py                      2.8.0            py35hb24199d_2    conda-forge
hdf5                      1.10.2               he51fdeb_2    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
intel-openmp              2019.4                      245
intervaltree              2.1.0                    py35_0    quantopian
ipykernel                 5.1.0              pyh24bf2e0_0    conda-forge
ipython                   7.0.1            py35h39e3cac_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.12.1                   py35_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
joblib                    0.13.2                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                2.6.0                    py35_2    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py35_0    conda-forge
jupyter_latex_envs        1.4.4                    py35_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py35_0    conda-forge
libgpuarray               0.7.6             hfa6e2cd_1003    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libxml2                   2.9.9                h9ce36c8_5    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
logbook                   0.12.5                   py35_0    quantopian
lru-dict                  1.1.4                    py35_0    quantopian
lxml                      4.2.5            py35heafd4d3_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.0              py35hfa6e2cd_1    conda-forge
matplotlib                2.0.0b4             np111py35_0    conda-forge
mistune                   0.8.3            py35hfa6e2cd_2    conda-forge
mkl                       2018.0.3                      1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                      py_0    conda-forge
nbconvert                 5.6.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  1.11                     py35_0    conda-forge
notebook                  5.7.0                    py35_0    conda-forge
numexpr                   2.6.6                    py35_0    conda-forge
numpy                     1.11.3           py35h4a99626_4
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pandas                    0.22.0                   py35_1    conda-forge
pandas-datareader         0.6.0                    py35_0    conda-forge
pandas-profiling          1.4.2                      py_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pickleshare               0.7.5                    py35_0    conda-forge
pip                       18.0                  py35_1001    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
pyfolio                   0.8.0                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pygpu                     0.7.6                    py35_0    conda-forge
pymc3                     3.5                      py35_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py35h6538335_2
pyreadline                2.1                   py35_1000    conda-forge
pytables                  3.4.4            py35h7e76658_1    conda-forge
python                    3.5.5                he025d50_2    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pywinpty                  0.5.4                    py35_2    conda-forge
pyyaml                    3.13             py35hfa6e2cd_1    conda-forge
pyzmq                     17.0.0                   py35_3    conda-forge
qgrid                     1.1.1                    py35_1    conda-forge
qt                        5.9.7                h506e8af_3    conda-forge
requests                  2.13.0                   py35_0    conda-forge
requests-file             1.4.3                    py35_0
requests-ftp              0.3.1                    py35_0    conda-forge
scikit-learn              0.20.0           py35heebcf9a_1
scipy                     1.1.0            py35hc28095f_0
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.19.8          py35h6538335_1000    conda-forge
six                       1.11.0                   py35_1    conda-forge
sortedcontainers          1.4.4                    py35_0    quantopian
sqlalchemy                1.2.12           py35hfa6e2cd_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_1    conda-forge
statsmodels               0.9.0                    py35_0    conda-forge
terminado                 0.8.1                    py35_1    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
theano                    1.0.3                    py35_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   5.1.1            py35hfa6e2cd_0    conda-forge
tqdm                      4.35.0                     py_0    conda-forge
trading-calendars         1.8.1                    py35_0    quantopian
traitlets                 4.3.2                    py35_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.32.0                py35_1000    conda-forge
widgetsnbextension        3.4.2                    py35_0    conda-forge
win_unicode_console       0.5                      py35_0    conda-forge
wincertstore              0.2                   py35_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zipline                   1.3.0               np111py35_0    Quantopian
zlib                      1.2.11            h2fa13f4_1005    conda-forge
</details>

Now that you know a little about me, let me tell you about the issue I am having:

ZIPLINE IS NOT WORKING FROM THE COMMAND LINE, AND EXAMPLES DON'T WORK IN JUPYTER NOTEBOOK.  I created a fresh virtual environment for local zipline and other Q tools.  Step 1 in the Zipline Beginner Tutorial throws errors.  

# Description of Issue

from zipline.examples import buyapple
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-50-2ab9218fdf43> in <module>
----> 1 from zipline.examples import buyapple

C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\zipline\examples\__init__.py in <module>
     14         continue
     15     modname = f[:-len('.py')]
---> 16     mod = import_module('.' + modname, package=__name__)
     17     EXAMPLE_MODULES[modname] = mod
     18     globals()[modname] = mod

C:\ProgramData\Anaconda3\envs\quant_trader\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\zipline\examples\dual_ema_talib.py in <module>
     28 from zipline.finance import commission, slippage
     29 # Import exponential moving average from talib wrapper
---> 30 from talib import EMA
     31 
     32 

ImportError: No module named 'talib'
#############################################################
The following command throws errors !!   
I cannot load my Quandl key because zipline won't run from the command line.  

$ QUANDL_API_KEY=<my_ key> zipline ingest 

#############################################################

The command below gives the error messages below. 

>> zipline

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\quant_trader\Scripts\zipline-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\pkg_resources\__init__.py", line 3112, in <module>
    @_call_aside
  File "C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\pkg_resources\__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\pkg_resources\__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\pkg_resources\__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\pkg_resources\__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\ProgramData\Anaconda3\envs\quant_trader\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wrapt' distribution was not found and is required by pandas-datareader
=================================================

* What did you expect to happen?
        Install zipline, pyfolio, alphalens locally and the examples work !!!!!!!!!!!!!!

* What happened instead?

A 1/2 day lost trying to workaround the incomplete documentation and examples for zipline local.  Quantopian has been around a long time.  

## What steps have you taken to resolve this already?

Scoured the internet and Quantopian web site for answers to getting ta-lib working so that I can get local zipline examples work.   Tried creating a separate virtual environment and installing the dependencies two different times.  Tried doing a separate build of ta-lib; that didn't work.  Tried downloading and installing ta-lib wheel file; that didn't work.  
...

# Anything else?
Overall a pretty frustrating day with Quantopian offline tools.  This zipline installation needs to "just work" like most other major Python package installations.  Take care of the dependencies in zipline installers guys! 
...

Sincerely,

**Comment by rogerjbos** [comment]
I've noticed this too.  I have opened two issues on this, but no one has ever responded.  I don't know if zipline is still being maintained or not???  The problem seems to be (in my case) downloading the benchmark data from the IEX website.  I don't think it works anymore.  If we knew what the data needed to look like, we can create our own data set.

**Comment by richdevboston** [comment]
The local Zipline version does not appear to be maintained, and is now an
afterthought or low priority for Quantopian.  I consider the zipline
installation package is incomplete because it requires TA-Lib, which is not
included in the zipline installation package.  I looked around and tried
several different kits for TA-Lib and none of them install correctly using
conda from the command line from conda-forge or Anaconda repos.  TA-Lib is
not packaged with Anaconda and this is a barrier to adoption offline
zipline.  Zipline needs to include the correct version of TA-Lib.

Too bad because I'd like to work with it.  My first requirement for any
"open source" package is that it installs locally, not in a captive,
proprietary online platform. Without being dependent on other poorly
maintained or packages unavailable in the target language, in this case
Python.

There are other Python-based backtesting tools.  I'll come back to zipline
another time.

**Comment by rogerjbos** [comment]
Thanks for the update.

**Comment by peterhbromley** [comment]
Hey @richdevboston and @rogerjbos, an update for the status of this bug is given in https://github.com/quantopian/zipline/issues/2652.  Let us know in that thread if you have any more issues running the examples.
