### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: 

### ISSUE THREAD

**Issue by alexanderkaplevatsky** [quantopian/zipline#2551]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System: (Windows Version 10`)
* Python Version: 3.5
* How did you install Zipline: conda

I get the errors below trying to ingest futures data:

(untitled1) C:\Users\kaple\PycharmProjects\untitled1>zipline ingest -b random_futures_data
Loading data...: 100%|###################################################################################################################################################################################################################| 228/228 [00:28<00:00,  7.97it/s]
Traceback (most recent call last):
  File "C:\Users\kaple\Anaconda3\envs\untitled1\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\zipline\__main__.py", line 348, in ingest
    show_progress,
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\zipline\data\bundles\core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\zipline\data\bundles\random_futures_data.py", line 85, in random_futures_data_me
    asset_db_writer.write(futures=metadata, root_symbols=root_symbols)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\zipline\assets\asset_writer.py", line 500, in write
    chunk_size,
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\zipline\assets\asset_writer.py", line 562, in _write_assets
    self._write_df_to_table(tbl, assets, txn, chunk_size)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\zipline\assets\asset_writer.py", line 529, in _write_df_to_table
    chunksize=chunk_size,
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\pandas\core\generic.py", line 1534, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\pandas\io\sql.py", line 473, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\pandas\io\sql.py", line 1512, in to_sql
    table.insert(chunksize)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\pandas\io\sql.py", line 670, in insert
    self._execute_insert(conn, keys, chunk_iter)
  File "C:\Users\kaple\Anaconda3\envs\untitled1\lib\site-packages\pandas\io\sql.py", line 1299, in _execute_insert
    conn.executemany(self.insert_statement(), data_list)
sqlite3.IntegrityError: UNIQUE constraint failed: futures_contracts.symbol

I am attaching the data file, my meta file and python bundle file
[random_futures_data.zip](https://github.com/quantopian/zipline/files/3674585/random_futures_data.zip)
. 
I tried to debug and in a debugger if I do INSERT or REPLACE my insert statement works, but it still fails on the next ingest.

Thanks for your help.

[CLG2000.zip](https://github.com/quantopian/zipline/files/3674576/CLG2000.zip)
[meta.zip](https://github.com/quantopian/zipline/files/3674581/meta.zip)

**Comment by alexanderkaplevatsky** [comment]
Resolved, incorrect data files
