### ISSUE TITLE
zipline ingest error: KeyError: Timestamp('2015-12-24 13:00:00+0000', tz='UTC')

### ISSUE THREAD

**Issue by SpurgeTech** [quantopian/zipline#2557]
I am currently using zipline in a python 3.5 virtual env. 

My is all symbols in the s&p 500 from 2008-present. 

The column names are labeled- ['date', 'open', 'high', 'low', 'close', 'volume']

The time range is from 9:30:00 - 16:00:00

The ingest function starts to run and here is the stack trace I get:

Traceback (most recent call last):
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 421, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 440, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2015-12-24 13:00:00+0000', tz='UTC')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/devon/.pyenv/versions/3.5.5/bin/zipline", line 10, in <module>
    sys.exit(main())
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/__main__.py", line 348, in ingest
    show_progress,
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/data/bundles/csvdir.py", line 94, in ingest
    self.csvdir)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/data/bundles/csvdir.py", line 156, in csvdir_bundle
    show_progress=show_progress)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/data/minute_bars.py", line 697, in write
    write_sid(*e, invalid_data_behavior=invalid_data_behavior)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/data/minute_bars.py", line 730, in write_sid
    self._write_cols(sid, dts, cols, invalid_data_behavior)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/zipline/data/minute_bars.py", line 810, in _write_cols
    latest_min_count = all_minutes.get_loc(last_minute_to_write)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pandas/core/indexes/datetimes.py", line 1426, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/Users/devon/.pyenv/versions/3.5.5/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 421, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 440, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2015-12-24 13:00:00+0000', tz='UTC')

**Comment by yongyct** [comment]
Similar issue resolved with some configurations:
https://github.com/quantopian/zipline/issues/2366

**Comment by taliarhodes** [comment]
This does seem directly related to issue 2366. Will close as duplicate and will address existing and further challenges in that issue.
