### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'open'

### ISSUE THREAD

**Issue by CapitalZe** [quantopian/zipline#2591]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

Ubuntu 16.04 running via VMWare on Macbook Pro.
I run all my script through Jupyter NB.

# Description of Issue
After sourcing and formatting minute data for a custom data bundle I can initiate the ingest process.

The process shorts and throws back the following error:

`AttributeError: 'DataFrame' object has no attribute 'open'
`

* What did you expect to happen?

I expected the minute data to be ingested successfully for back-testing

* What happened instead?

After much trial and error I found a decent source of minute data for some select stocks I wish to work with and followed the OHLCV protocol as directed by the documentation.

DataFrame declares there is no attribute 'open', although I know this to not be true based on three factors:

1. I personally formatted and inspected the csv before attempted ingestion
2. Using Pandas I print  the data.columns
3. Using Pandas I print the data itself

An example of each of the three;

1. 

date | open | high | low | close | volume
-- | -- | -- | -- | -- | --
26.01.2017 14:30:00.000 | 111.73 | 112.38 | 111.73 | 112.04 | 1975491.9707
26.01.2017 14:40:00.000 | 112.05 | 112.13 | 111.7 | 111.93 | 2051321.9833
26.01.2017 14:50:00.000 | 111.947 | 112.23 | 111.6 | 112.23 | 2373047.0091
26.01.2017 15:00:00.000 | 112.24 | 112.24 | 111.88 | 112.06 | 1883206.0472

2.` Index(['date', 'open', 'high', 'low', 'close', 'volume'], dtype='object')`

3.

date | open | high | low | close | volume
-- | -- | -- | -- | -- | --
26.01.2017 14:30:00.000 | 111.730 | 112.380 | 111.730 | 112.040 | 1.975492e+06
26.01.2017 14:40:00.000 | 112.050 | 112.130 | 111.700 | 111.930 | 2.051322e+06
26.01.2017 14:50:00.000 | 111.947 | 112.230 | 111.600 | 112.230 | 2.373047e+06
26.01.2017 15:00:00.000 | 112.240 | 112.240 | 111.880 | 112.060 | 1.883206e+06
26.01.2017 15:10:00.000 | 112.060 | 112.240 | 112.030 | 112.240 | 1.973660e+06

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Place ticker csv's in /home/XXX/.zipline/data/custom-csvdir-bundle/minute/
2. In Jupyter` !CSVDIR=./csvdir/ zipline ingest -b custom-csvdir-bundle`

The output is:

```
 | JNJ: sid 0
Loading custom pricing data:   [#######-----------------------------]   20%  00:08:19 | LLY: sid 1

Traceback (most recent call last):
  File "/homeXXX/voinv/bin/zipline", line 10, in <module>
    sys.exit(main())
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/__main__.py", line 348, in ingest
    show_progress,
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/data/bundles/core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/data/bundles/csvdir.py", line 94, in ingest
    self.csvdir)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/data/bundles/csvdir.py", line 156, in csvdir_bundle
    show_progress=show_progress)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 697, in write
    write_sid(*e, invalid_data_behavior=invalid_data_behavior)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 721, in write_sid
    'open': df.open.values,
  File "/home/XXX/voinv/lib/python3.6/site-packages/pandas/core/generic.py", line 2970, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'open'

```
...

## What steps have you taken to resolve this already?

I've scoured the documentation and other informative sources with no luck.

As we can see, the objects are in fact attributed, yet this error still persists.

I thank you in advance.

**Comment by colinalexander** [comment]
The error is here on line 721:

`File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/data/minute_bars.py", line 721, in write_sid
    'open': df.open.values,`

The code should be `df['open'].values`, not `df.open.values`.

**Comment by CapitalZe** [comment]
If anyone else faces this problem, a potential way to resolve it is:

in minute_bars.py you must change the following from:

` def write_sid(self, sid, df, invalid_data_behavior='warn'):
        """
        Write the OHLCV data for the given sid.
        If there is no bcolz ctable yet created for the sid, create it.
        If the length of the bcolz ctable is not exactly to the date before
        the first day provided, fill the ctable with 0s up to that date.
        Parameters
        ----------
        sid : int
            The asset identifer for the data being written.
        df : pd.DataFrame
            DataFrame of market data with the following characteristics.
            columns : ('open', 'high', 'low', 'close', 'volume')
                open : float64
                high : float64
                low  : float64
                close : float64
                volume : float64|int64
            index : DatetimeIndex of market minutes.
        """
        cols = {
            'open': df.open.values,
            'high': df.high.values,
            'low': df.low.values,
            'close': df.close.values,
            'volume': df.volume.values,
        }
        dts = df.index.values
        # Call internal method, since DataFrame has already ensured matching
        # index and value lengths.
        self._write_cols(sid, dts, cols, invalid_data_behavior)

       `
lines >708 to 730<
to:

` def write_cols(self, sid, dts, cols, invalid_data_behavior='warn'):
        """
        Write the OHLCV data for the given sid.
        If there is no bcolz ctable yet created for the sid, create it.
        If the length of the bcolz ctable is not exactly to the date before
        the first day provided, fill the ctable with 0s up to that date.

        Parameters
        ----------
        sid : int
            The asset identifier for the data being written.
        dts : datetime64 array
            The dts corresponding to values in cols.
        cols : dict of str -> np.array
            dict of market data with the following characteristics.
            keys are ('open', 'high', 'low', 'close', 'volume')
            open : float64
            high : float64
            low  : float64
            close : float64
            volume : float64|int64
        """
        if not all(len(dts) == len(cols[name]) for name in self.COL_NAMES):
            raise BcolzMinuteWriterColumnMismatch(
                "Length of dts={0} should match cols: {1}".format(
                    len(dts),
                    " ".join("{0}={1}".format(name, len(cols[name]))
                             for name in self.COL_NAMES)))
        self._write_cols(sid, dts, cols, invalid_data_behavior)

    def _write_cols(self, sid, dts, cols, invalid_data_behavior):
        """
        Internal method for `write_cols` and `write`.

        Parameters
        ----------
        sid : int
            The asset identifier for the data being written.
        dts : datetime64 array
            The dts corresponding to values in cols.
        cols : dict of str -> np.array
            dict of market data with the following characteristics.
            keys are ('open', 'high', 'low', 'close', 'volume')
            open : float64
            high : float64
            low  : float64
            close : float64
            volume : float64|int64
        """`

lines >708 to 730<

**Comment by RichardDale** [comment]
@CapitalZe  No need to close the issue until it's resolved in Main.  I'm not entirely sure your patch addresses is correct - you just appear to have commented out some code.

**Comment by CapitalZe** [comment]
Ok, I'll reopen.

I uncommented out the snippet above too, which was commented out.

It works for me at least:

```
Loading custom pricing data:   [#######-----------------------------]   20%  00:00:10 | LLY: sid 1
Loading custom pricing data:   [##############----------------------]   40%  00:00:07 | MCK: sid 2
Loading custom pricing data:   [#####################---------------]   60%  00:00:32 | MRK: sid 3
Loading custom pricing data:   [############################--------]   80%  00:00:28 | PFE: sid 4
Loading custom pricing data:   [####################################]  100%          
Merging minute equity files:  [####################################]   
```

There were some indentation and formatting errors in the lines above it that I emended as well.

Hopefully this helps someone else.

**Comment by netshade** [comment]
I encountered this error, and it was because the CSV files had no columns ( `date,open,high,low,close,volume` )
