### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by cuisong327** [quantopian/zipline#2599]
I am trying to install zipline on Python 3.5.0 (on Win10). When I run 'import zipline', I have this error - ImportError: cannot import name 'Type'. I have tried to pip install typing and typing-extension, and also pip install tornado==5.1.1. I still have the same issue. Could someone please help? Thanks a lot.

**Comment by taliarhodes** [comment]
Sorry for the delay, but would you be able to provide the full traceback you receive?

Also, can you verify you are using Conda to install Zipline?

**Comment by serllv** [comment]
I have the same issue:

Traceback (most recent call last):
  File "C:\Users\Aaron's\Desktop\Research\tmm_core.py", line 6, in <module>
    import scipy as sp
  File "C:\Users\Aaron's\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\Aaron's\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\Aaron's\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\Aaron's\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\Aaron's\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\Aaron's\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'
No matter what I do, I can't make this code work.

**Comment by taliarhodes** [comment]
So for @cuisong327 and maybe you @serllv (but I can't see what version of Python 3.5 you're using) I believe this issue is actually due to an incompatibility with your version of Python 3.5 and the version of newer version of Scipy required here. See similar issue here: https://github.com/tornadoweb/tornado/issues/2623

The Type class in this error wasn't added until Python 3.5.2. 

I'll be closing this issue for now as I don't believe it's specific to Zipline here.
