### ISSUE TITLE
zipline.errors.SymbolNotFound: Symbol 'MRK' was not found.

### ISSUE THREAD

**Issue by CapitalZe** [quantopian/zipline#2633]
Symbol not found when using custom-csvdir-bundle.

I am using minutely data and can ingest it with the cusomt-csvir-bundle.

All the requisite files are generated, sqlite etc in .zipline/data.

The output I am getting is:

`Traceback (most recent call last):
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/assets/assets.py", line 699, in _lookup_symbol_strict
    share_class_symbol,
KeyError: ('AAPL', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXX/voinv/bin/zipline", line 10, in <module>
    sys.exit(main())
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/__main__.py", line 107, in _
    return f(*args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/__main__.py", line 276, in run
    blotter=blotter,
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/utils/run_algo.py", line 229, in _run
    overwrite_sim_params=False,
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algorithm.py", line 756, in run
    for perf in self.get_generator():
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algorithm.py", line 629, in get_generator
    return self._create_generator(self.sim_params)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algorithm.py", line 589, in _create_generator
    self.initialize(*self.initialize_args, **self.initialize_kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algorithm.py", line 451, in initialize
    self._initialize(self, *args, **kwargs)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algo5.py", line 12, in initialize
    algo.sids = [algo.symbol(symbol) for symbol in algo.stocks]
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algo5.py", line 12, in <listcomp>
    algo.sids = [algo.symbol(symbol) for symbol in algo.stocks]
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algorithm.py", line 1215, in symbol
    """Lookup an Equity by its ticker symbol.
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/algorithm.py", line 1245, in symbol
    as_of_date=_lookup_date,
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/assets/assets.py", line 834, in lookup_symbol
    return self._lookup_symbol_strict(symbol, as_of_date)
  File "/home/XXX/voinv/lib/python3.6/site-packages/zipline/assets/assets.py", line 704, in _lookup_symbol_strict
    raise SymbolNotFound(symbol=symbol)
zipline.errors.SymbolNotFound: Symbol 'MRK' was not found.

`
My data is three years of historical minute data for MRK. OHCLV protocol.

I've run the same test with AAPL and still the same error.

Anyone have a clue?

Has anyone got minute data to work yet? I've been trying for months, I've seen no evidence yet anyone has. If someone has, please let me know, so I know I'm not working in vain.

Cheers!

**Comment by samatix** [comment]
@CapitalZe , can you please share a sample csv file similar to what you are pushing to zipline?

**Comment by michaeljames0001** [comment]
I'm having the same error. The error points to assets.py

**Comment by dirk-fr** [comment]
Can you check if MRK is contained in algo.stocks twice? 
The error happens in this line:
algo.sids = [algo.symbol(symbol) for symbol in algo.stocks]

I've had the same issue before - and wrote it off to a fault on my end, but it seems to be more common...

Dirk
