### ISSUE TITLE
KeyError: Equity(0 [SBER]) with custom bundle from csv

### ISSUE THREAD

**Issue by sislate** [quantopian/zipline#2661]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

<details>

* Operating System:(Windows 8.1
* Python Version: Python 3.5.6 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Zipline: pip install zipline in virtualenv on conda
* Python packages: 
`$ pip freeze` 
alembic==0.7.7
asn1crypto==0.24.0
attrs==19.3.0
backcall==0.1.0
bcolz==0.12.1
bleach==3.1.0
Bottleneck==1.2.1
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
Click==7.0
colorama==0.4.3
contextlib2==0.6.0.post1
cryptography==2.3.1
cycler==0.10.0
cyordereddict==0.2.2
Cython==0.28.5
decorator==4.4.1
defusedxml==0.6.0
empyrical==0.5.0
entrypoints==0.3
h5py==2.10.0
idna==2.7
importlib-metadata==1.5.0
intervaltree==2.1.0
ipykernel==5.1.4
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
iso3166==1.0.1
iso4217==1.6.20180829
jedi==0.16.0
Jinja2==2.11.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.3
kiwisolver==1.1.0
Logbook==0.12.5
lru-dict==1.1.4
lxml==4.2.5
Mako==1.1.1
MarkupSafe==1.0
matplotlib==3.0.3
mistune==0.8.4
mpl-finance==0.10.0
multipledispatch==0.6.0
nbconvert==5.6.1
nbformat==5.0.4
networkx==1.11
notebook==6.0.3
numexpr==2.7.1
numpy==1.14.2
pandas==0.22.0
pandas-datareader==0.8.1
pandocfilters==1.4.2
parso==0.6.1
patsy==0.5.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==2.0.10
pycparser==2.19
Pygments==2.5.2
pyOpenSSL==18.0.0
pyparsing==2.4.6
pyrsistent==0.15.7
PySocks==1.6.8
python-dateutil==2.8.1
python-interface==1.5.3
pytz==2019.3
pywin32==227
pywinpty==0.5.7
pyzmq==18.1.1
qtconsole==4.6.0
requests==2.20.1
requests-file==1.4.3
scipy==1.1.0
Send2Trash==1.5.0
six==1.11.0
sortedcontainers==1.4.4
SQLAlchemy==1.2.11
statsmodels==0.9.0
tables==3.4.4
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.3
trading-calendars==1.11.1
traitlets==4.3.3
urllib3==1.23
v==0.0.0
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
zipline==1.3.0
zipp==1.2.0

`$ conda list`
packages in environment at C:\Users\dm\Anaconda3\envs\env_zipliine:

Name                    Version                   Build  Channel
alembic                   0.7.7                    py35_0    Quantopian
asn1crypto                0.24.0                   py35_0  
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
bcolz                     0.12.1              np114py35_0    Quantopian
blas                      1.0                         mkl  
bleach                    3.1.0                    pypi_0    pypi
blosc                     1.16.3               h7bd577a_0  
bottleneck                1.2.1            py35h452e1ab_1  
bzip2                     1.0.8                he774522_0  
ca-certificates           2020.1.1                      0  
certifi                   2018.8.24                py35_1  
cffi                      1.11.5           py35h74b6da3_1  
chardet                   3.0.4                    py35_1  
click                     7.0                        py_0  
colorama                  0.4.3                    pypi_0    pypi
contextlib2               0.6.0.post1                py_0  
cryptography              2.3.1            py35h74b6da3_0  
cycler                    0.10.0                   pypi_0    pypi
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h6538335_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                    pypi_0    pypi
empyrical                 0.5.0                    py35_0    Quantopian
entrypoints               0.3                      pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.10.2               hac2f561_1  
icc_rt                    2019.0.0             h0cc432a_1  
idna                      2.7                      py35_0  
importlib-metadata        1.5.0                    pypi_0    pypi
intel-openmp              2019.4                      245  
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 5.1.4                    pypi_0    pypi
ipython                   7.9.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
iso3166                   1.0.1                    pypi_0    pypi
iso4217                   1.6.20180829             pypi_0    pypi
jedi                      0.16.0                   pypi_0    pypi
jinja2                    2.11.1                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            5.3.4                    pypi_0    pypi
jupyter-console           6.1.0                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libiconv                  1.15                 h1df5818_7  
libxml2                   2.9.9                h464c3ec_0  
libxslt                   1.1.33               h579f668_0  
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lxml                      4.2.5            py35hef2cd61_0  
lz4-c                     1.8.1.2              h2fa13f4_0  
lzo                       2.10                 h6df0209_2  
mako                      1.1.1                      py_0  
markupsafe                1.0              py35hfa6e2cd_1  
matplotlib                3.0.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2018.0.3                      1  
mpl-finance               0.10.0                   pypi_0    pypi
multipledispatch          0.6.0                    py35_0  
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.4                    pypi_0    pypi
networkx                  1.11                     py35_1  
notebook                  6.0.3                    pypi_0    pypi
numexpr                   2.6.1                    pypi_0    pypi
numpy                     1.14.2           py35h5c71026_0  
openssl                   1.0.2u               he774522_0  
pandas                    0.22.0           py35h6538335_0  
pandas-datareader         0.8.1                      py_0  
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.6.1                    pypi_0    pypi
patsy                     0.5.0                    py35_0  
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.0.2                   pypi_0    pypi
prometheus-client         0.7.1                    pypi_0    pypi
prompt-toolkit            2.0.10                   pypi_0    pypi
pycparser                 2.19                     py35_0  
pygments                  2.5.2                    pypi_0    pypi
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.4.6                    pypi_0    pypi
pyrsistent                0.15.7                   pypi_0    pypi
pysocks                   1.6.8                    py35_0  
pytables                  3.4.4            py35he6f6034_0  
python                    3.5.6                he025d50_0  
python-dateutil           2.8.1                      py_0  
python-interface          1.5.3                    pypi_0    pypi
pytz                      2019.3                     py_0  
pywin32                   227                      pypi_0    pypi
pywinpty                  0.5.7                    pypi_0    pypi
pyzmq                     18.1.1                   pypi_0    pypi
qtconsole                 4.6.0                    pypi_0    pypi
requests                  2.20.1                   py35_0    Quantopian
requests-file             1.4.3                    py35_0  
scipy                     1.1.0            py35hc28095f_0  
send2trash                1.5.0                    pypi_0    pypi
setuptools                45.2.0                   pypi_0    pypi
six                       1.11.0                   py35_1  
snappy                    1.1.7                h777316e_3  
sortedcontainers          1.4.4                    py35_0    Quantopian
sqlalchemy                1.2.11           py35hfa6e2cd_0  
statsmodels               0.9.0            py35h452e1ab_0  
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
toolz                     0.10.0                     py_0  
tornado                   6.0.3                    pypi_0    pypi
trading-calendars         1.11.1                   py35_0    Quantopian
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.23                     py35_0  
v                         0.0.0                    pypi_0    pypi
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.16.27012          hf0eaf9b_1  
wcwidth                   0.1.8                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
win-unicode-console       0.5                      pypi_0    pypi
win_inet_pton             1.0.1                    py35_1  
wincertstore              0.2              py35hfebbdb8_0  
xz                        5.2.4                h2fa13f4_4  
zipline                   0+unknown                pypi_0    pypi
zipp                      1.2.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

</details>

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I have the error `KeyError: Equity(0 [SBER])`

```
(env_zipliine) C:\Users\dm\Downloads>zipline run --bundle sber --algofile test.p
y --start 2010-1-1 --end 2010-2-1
[2020-02-26 12:03:50.922133] WARNING: Loader: Refusing to download new benchmark
 data because a download succeeded at 2020-02-26 11:43:03.333968+00:00.
c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\empyrical\stats.py:790
: RuntimeWarning: invalid value encountered in true_divide
  np.divide(average_annual_return, annualized_downside_risk, out=out)
c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\empyrical\stats.py:704
: RuntimeWarning: invalid value encountered in true_divide
  out=out,
Traceback (most recent call last):
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\runpy.py", line 193, in _run
_module_as_main
    "__main__", mod_spec)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\runpy.py", line 85, in _run_
code
    exec(code, run_globals)
  File "C:\Users\dm\Anaconda3\envs\env_zipliine\Scripts\zipline.exe\__main__.py"
, line 7, in <module>
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\click\core.py"
, line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\click\core.py"
, line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\click\core.py"
, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\click\core.py"
, line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\click\core.py"
, line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\__main
__.py", line 107, in _
    return f(*args, **kwargs)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\click\decorato
rs.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\__main
__.py", line 276, in run
    blotter=blotter,
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\utils\
run_algo.py", line 229, in _run
    overwrite_sim_params=False,
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\algori
thm.py", line 756, in run
    for perf in self.get_generator():
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\gens\t
radesimulation.py", line 206, in transform
    for capital_change_packet in every_bar(dt):
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\gens\t
radesimulation.py", line 120, in every_bar
    blotter.get_transactions(current_data)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\financ
e\blotter\simulation_blotter.py", line 345, in get_transactions
    slippage.simulate(bar_data, asset, asset_orders):
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\financ
e\slippage.py", line 121, in simulate
    volume = data.current(asset, "volume")
  File "zipline/_protocol.pyx", line 121, in zipline._protocol.check_parameters.
__call__.assert_keywords_and_call
    return func(*args, **kwargs)
  File "zipline/_protocol.pyx", line 332, in zipline._protocol.BarData.current
    return self.data_portal.get_spot_value(
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\d
ata_portal.py", line 524, in get_spot_value
    data_frequency,
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\d
ata_portal.py", line 461, in _get_single_asset_value
    asset, field, session_label,
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\d
ata_portal.py", line 748, in _get_daily_spot_value
    return reader.get_value(asset, dt, column)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\d
ispatch_bar_reader.py", line 97, in get_value
    return r.get_value(asset, dt, field)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\r
esample.py", line 707, in get_value
    return self._reader.get_value(sid, dt, field)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\u
s_equity_pricing.py", line 742, in get_value
    ix = self.sid_day_index(sid, dt)
  File "c:\users\dm\anaconda3\envs\env_zipliine\lib\site-packages\zipline\data\u
s_equity_pricing.py", line 710, in sid_day_index
    offset = day_loc - self._calendar_offsets[sid]
KeyError: Equity(0 [SBER])
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. get csv https://drive.google.com/open?id=14rdXq2oFoaphoEQZAtugJ4OzmdKuX049 This is minute data. Filename SBER.csv Symbol SBER from Moscow Exchange (BTW Where does the symbol name come from? From the file name?)

2. set some code to file  `extensions.py` like in [docs](https://www.zipline.io/bundles.html#ingesting-data-from-csv-files)
```
import pandas as pd
from zipline.data.bundles import register
from zipline.data.bundles.csvdir import csvdir_equities

start_session = pd.Timestamp('2010-01-11', tz='utc')
end_session = pd.Timestamp('2014-12-30', tz='utc')

register(
    'sber',
    csvdir_equities(
        ['minute'],
        'c:\\Users\\dm\\Google Диск\\IP\\trading\\data\\zipline',
    ),
    calendar_name='XMOS', # Moscow Exchange from https://github.com/quantopian/trading_calendars
    start_session=start_session,
    end_session=end_session
)
```
3. set  some code to file `benchmarks.py` and `loader.py` like in [this comment](https://github.com/quantopian/zipline/issues/2480#issuecomment-502890521) in #2480

First, replace `benchmarks.py` with
```
 import pandas as pd
 import requests
 from trading_calendars import get_calendar

def get_benchmark_returns(symbol, first_date, last_date):
    cal = get_calendar('XMOS')
    
    dates = cal.sessions_in_range(first_date, last_date)

    data = pd.DataFrame(0.0, index=dates, columns=['close'])
    data = data['close']

    return data.sort_index().iloc[1:]
```

Then in `loader.py` replace
`data = get_benchmark_returns(symbol)`
with
`data = get_benchmark_returns(symbol, first_date, last_date)`

4. Create file `test.py`

```
import zipline
from zipline.api import order, record, symbol

def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('SBER'), 10)
    record(SBER=data.current(symbol('SBER'), 'price'))
```
5. Run zipline `zipline run --bundle sber --algofile test.py --start 2010-1-1 --end 2010-2-1`

And then get this error. 

What does it mean? I have not found a solution.

Sincerely,
`$ whoami`

**Comment by learqt** [comment]
I have the same issue !

**Comment by Nickgulikh** [comment]
Same here!
@sislate Did you get to resolve the problem?
@richafrank Could you let us know if any ways to resolve this?
Thanks!

**Comment by Nickgulikh** [comment]
I am quite sure it's related to the 'minute' setting...
I tried ingesting custom daily data and all worked fine...

**Comment by Nickgulikh** [comment]
Issue resolved. need to add '--data-frequency minute' in the run line.
