### ISSUE TITLE
Error in using trading_calendar in run_algorithm

### ISSUE THREAD

**Issue by kazemimehdi** [quantopian/zipline#2684]
Dear Zipline Maintainers,

I have tried to define a **custom daily bundle** using csv and **custom calendar**. I succeeded to ingest the bundle with the custom calendar. But in the run_algorithm function, when I try to use custom calendar I get the following error:

```
AssertionError: All readers must share target trading_calendar. Reader=<zipline.data.minute_bars.BcolzMinuteBarReader object at 0x000002301496A320> for type=<class 'zipline.assets._assets.Equity'> uses calendar=<trading_calendars.exchange_calendar_irtse.IRTSEExchangeCalendar object at 0x000002301496A2B0> which does not match the desired shared calendar=<trading_calendars.exchange_calendar_irtse.IRTSEExchangeCalendar object at 0x000002300E4F8898> 
```

In more detail:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Code/backtestProject/firstzipline.py", line 65, in <module>
    bundle='tse_bundle')
  File "C:\Program_Files\anaconda3\envs\backtestProject\lib\site-packages\zipline\utils\run_algo.py", line 430, in run_algorithm
    blotter=blotter,
  File "C:\Program_Files\anaconda3\envs\backtestProject\lib\site-packages\zipline\utils\run_algo.py", line 169, in _run
    adjustment_reader=bundle_data.adjustment_reader,
  File "C:\Program_Files\anaconda3\envs\backtestProject\lib\site-packages\zipline\data\data_portal.py", line 247, in __init__
    self._last_available_minute,
  File "C:\Program_Files\anaconda3\envs\backtestProject\lib\site-packages\zipline\data\dispatch_bar_reader.py", line 59, in __init__
    r, t, r.trading_calendar, trading_calendar)
AssertionError: All readers must share target trading_calendar. Reader=<zipline.data.minute_bars.BcolzMinuteBarReader object at 0x000002301496A320> for type=<class 'zipline.assets._assets.Equity'> uses calendar=<trading_calendars.exchange_calendar_irtse.IRTSEExchangeCalendar object at 0x000002301496A2B0> which does not match the desired shared calendar=<trading_calendars.exchange_calendar_irtse.IRTSEExchangeCalendar object at 0x000002300E4F8898> 
```

My Code:
```
from zipline import run_algorithm
from zipline.api import order_target_percent, symbol
from trading_calendars.exchange_calendar_irtse import IRTSEExchangeCalendar as tse_calendar
from datetime import datetime
import pytz
import matplotlib.pyplot as plt


def initialize(context):
    context.stock = symbol('AKH')
    context.index_average_window = 50


def handle_data(context, data):
    equities_hist = data.history(context.stock, "high", context.index_average_window, "1d")
    if equities_hist[-1] > equities_hist.mean():
        stock_weight = 1.0
    else:
        stock_weight = 0.0
    order_target_percent(context.stock, stock_weight)


def analyze(context, perf):
    fig = plt.figure(figsize=(12, 8))

    # First chart
    ax = fig.add_subplot(311)
    ax.set_title('Strategy Results')
    ax.semilogy(perf['portfolio_value'], linestyle='-', label='Equity Curve', linewidth=3.0)
    ax.legend()
    ax.grid(False)

    # Second chart
    ax = fig.add_subplot(312)
    ax.plot(perf['gross_leverage'], label='Exposure', linestyle='-', linewidth=1.0)
    ax.legend()
    ax.grid(True)

    # Third chart
    ax = fig.add_subplot(313)
    ax.plot(perf['returns'], label='Returns', linestyle='-.', linewidth=1.0)
    ax.legend()
    ax.grid(True)

    plt.savefig('d:/backtest.png', dpi=100)
    plt.show()


start_date = datetime(2018, 8, 25, tzinfo=pytz.UTC)
end_date = datetime(2020, 3, 20, tzinfo=pytz.UTC)

results = run_algorithm(
    start=start_date,
    end=end_date,
    trading_calendar=tse_calendar(),
    initialize=initialize,
    analyze=analyze,
    handle_data=handle_data,
    capital_base=1000,
    data_frequency='daily',
    bundle='tse_bundle')
```

it also maybe help that I share the custom calendar code:

```
from datetime import time
from itertools import chain

import pandas as pd
from pandas.tseries.holiday import Holiday
from pytz import timezone

from .common_holidays import european_labour_day
from .trading_calendar import HolidayCalendar, TradingCalendar


class IRTSEExchangeCalendar(TradingCalendar):

    name = 'IRTSE'

    tz = timezone('Asia/Tehran')

    open_times = (
        (None, time(9, 00)),
    )

    close_times = (
        (None, time(12, 30)),
    )

    @property
    def weekmask(self):
        return '1110011'
    
    @property
    def regular_holidays(self):
        return HolidayCalendar([
        ])
    
    holidays = pd.to_datetime([
        '2018-03-21',
        '2018-03-22',
        '2018-03-23',
        '2018-03-24',
        '2018-03-31',
        '2018-04-01',
        '2018-04-02',
        '2018-04-14',
        '2018-05-02',
        '2018-06-04',
        '2018-06-05',
        '2018-06-06',
        '2018-06-15',
        '2018-06-16',
        '2018-07-09',
        '2018-08-22',
        '2018-08-30',
        '2018-09-19',
        '2018-09-20',
        '2018-10-30',
        '2018-11-07',
        '2018-11-08',
        '2018-11-16',
        '2019-12-25',
        '2019-02-09',
        '2019-02-11',
        '2019-03-20',
        '2019-03-21',
        '2019-03-22',
        '2019-03-23',
        '2019-03-24',
        '2019-04-01',
        '2019-04-02',
        '2019-04-03',
        '2019-04-21',
        '2019-05-27',
        '2019-06-04',
        '2019-06-05',
        '2019-06-06',
        '2019-06-29',
        '2019-07-12',
        '2019-07-20',
        '2019-08-08',
        '2019-09-09',
        '2019-09-10',
        '2019-10-19',
        '2019-10-27',
        '2019-10-29',
        '2019-11-06',
        '2020-01-29',
        '2020-02-11',
        '2020-03-08',
        '2020-03-19',
        '2020-03-20',
        '2020-03-21',
        '2020-03-22',
        '2020-03-23',
        '2020-03-31',
        '2020-04-01',
        '2020-04-09',
        '2020-05-15',
        '2020-05-24',
        '2020-05-25',
        '2020-06-03',
        '2020-06-04',
        '2020-06-17',
        '2020-07-31',
        '2020-08-08',
        '2020-08-29',
        '2020-08-30',
        '2020-10-08',
        '2020-10-16',
        '2020-10-17',
        '2020-10-25',
        '2020-11-03',
        '2021-01-17',
        '2021-02-10',
        '2021-02-25',
        '2021-03-11',
        '2021-03-19',
        '2021-03-20',
    ])


    @property
    def adhoc_holidays(self):
        return list(chain(self.tatilat))

```

Sincerely,
Mehdi

**Comment by kazemimehdi** [comment]
I thought that assert return error even when two instances of the same object are compared. So I commented this part of the **dispatch_bar_reader.py**:

```
 for t, r in iteritems(self.
     assert trading_calendar == r.trading_calendar,
         "All readers must share target trading_calendar. " \
         "Reader={0} for type={1} uses calendar={2} which does not " \
         "match the desired shared calendar={3} ".format(
             r, t, r.trading_calendar, trading_calendar)
```

It seems that the problem solved. But I am not  happy with the solution. :(

**Comment by cemal95** [comment]
would you, by any chance, know how to solve issue #2700 ?

**Comment by cemal95** [comment]
Did anyone fix this?

**Comment by kazemimehdi** [comment]
As I described, I have fixed this by commenting this part of the code in **dispatch_bar_reader.py** file:

>  for t, r in iteritems(self.
>    assert trading_calendar == r.trading_calendar,
>       "All readers must share target trading_calendar. " \
>        "Reader={0} for type={1} uses calendar={2} which does not " \
>        "match the desired shared calendar={3} ".format(
>               r, t, r.trading_calendar, trading_calendar)

**Comment by h4ppysmile** [comment]
I think this is a better solution:

`            assert isinstance(trading_calendar, type(r.trading_calendar)), \
                "All readers must share target trading_calendar. " \
                "Reader={0} for type={1} uses calendar={2} which does not " \
                "match the desired shared calendar={3} ".format(
                    r, t, r.trading_calendar, trading_calendar)`

**Comment by richafrank** [comment]
Hi @kazemimehdi ,

Sorry for the delay in replying. The issue here is that zipline currently expects that only the registered, e.g. singleton, instances of the calendars are passed around. It looks like you're already registering the calendar properly, so instead of constructing a new instance of the calendar when you call `run_algorithm`, you should pass the registered instance, i.e.
```python
from trading_calendars import get_calendar

results = run_algorithm(
    start=start_date,
    end=end_date,
    trading_calendar=get_calendar('IRTSE'),
    initialize=initialize,
    analyze=analyze,
    handle_data=handle_data,
    capital_base=1000,
    data_frequency='daily',
    bundle='tse_bundle')
```

That code snippet assumes you registered your calendar with `register_calendar('IRTSE', tse_calendar())` - you should use whatever name you used to register the calendar. 

So I don't think a zipline code change is strictly necessary here, though a feature request might be to support multiple instances of the calendars being passed around. I imagine the dict lookup of the singleton is faster than constructing a new instance a bunch, so we'd need to assess our uses. Alternatively, I could also see passing the instance around explicitly to all the consumers, instead of consumers looking it up or constructing it. There would still need to be some kind of check that the bundle's calendar name matches the provided calendar's.

Hopefully that helps.

**Comment by cemal95** [comment]
@richafrank Hi Richard, is it possible you could look at issue #2700 ?
