### ISSUE TITLE
error in get_benchmark_returns_from_file

### ISSUE THREAD

**Issue by cemal95** [quantopian/zipline#2696]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment
* Operating System: Mac OS Catalina 10.15.4
* Python Version: 3.7.4
* Python Bitness: 64
* How did you install Zipline: I installed Zipline through Conda 
* Python packages: 

alembic                   0.7.7                    py35_0    Quantopian
appnope                   0.1.0            py35hd172556_0  
asn1crypto                0.24.0                   py35_0  
bcolz                     0.12.1              np114py35_0    Quantopian
blas                      1.0                         mkl  
bleach                    3.1.4                      py_0  
blosc                     1.16.3               hd9629dc_0  
bottleneck                1.2.1            py35h1d22016_1  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.1.1                      0  
certifi                   2018.8.24                py35_1  
cffi                      1.11.5           py35h6174b99_1  
chardet                   3.0.4                    py35_1  
click                     7.0                        py_0  
contextlib2               0.6.0.post1                py_0  
cryptography              2.3.1            py35hdbc3d79_0  
cycler                    0.10.0           py35hb89929e_0  
cyordereddict             0.2.2                    py35_0    Quantopian
cython                    0.28.5           py35h0a44026_0  
dbus                      1.13.12              h90a0687_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
empyrical                 0.5.0                    py35_0    Quantopian
entrypoints               0.2.3                    py35_2  
expat                     2.2.6                h0a44026_0  
freetype                  2.9.1                hb4e5f40_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.63.1               hd977a24_0  
hdf5                      1.10.2               hfa1e0ec_1  
icu                       58.2                 h4b95b61_1  
idna                      2.7                      py35_0  
import-ipynb              0.1.3                    pypi_0    pypi
intel-openmp              2019.4                      233  
intervaltree              2.1.0                    py35_0    Quantopian
ipykernel                 4.10.0                   py35_0  
ipython                   5.8.0                    py35_0  
ipython_genutils          0.2.0            py35hf129286_0  
ipywidgets                7.4.1                    py35_0  
jinja2                    2.11.1                     py_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py35h2dd9e4b_0  
jupyter                   1.0.0                    py35_7  
jupyter_client            5.3.3                      py_0  
jupyter_console           5.2.0            py35hd2aa692_1  
jupyter_core              4.5.0                      py_0  
kiwisolver                1.0.1            py35h219a9d8_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libxml2                   2.9.9                hf6e021a_1  
libxslt                   1.1.33               h33a18ac_0  
logbook                   0.12.5                   py35_0    Quantopian
lru-dict                  1.1.4                    py35_0    Quantopian
lxml                      4.2.5            py35hef8c89e_0  
lz4-c                     1.8.1.2              h1de35cc_0  
lzo                       2.10                 h362108e_2  
mako                      1.1.2                      py_0  
markupsafe                1.0              py35h1de35cc_1  
matplotlib                3.0.0            py35h54f8f79_0  
mistune                   0.8.3            py35h1de35cc_1  
mkl                       2018.0.3                      1  
multipledispatch          0.6.0                    py35_0  
nb_conda                  2.2.1            py35hd4e941f_0  
nb_conda_kernels          2.1.1                    py35_1    conda-forge
nbconvert                 5.5.0                      py_0  
nbformat                  5.0.4                      py_0  
ncurses                   6.2                  h0a44026_0  
networkx                  1.11                     py35_1  
notebook                  5.6.0                    py35_0  
numexpr                   2.6.1               np114py35_0    Quantopian
numpy                     1.14.2           py35ha9ae307_0  
openssl                   1.0.2u               h1de35cc_0  
pandas                    0.22.0           py35h0a44026_0  
pandas-datareader         0.8.1                      py_0  
pandas_market_calendars   1.2                        py_0    conda-forge
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py35_1  
patsy                     0.5.0                    py35_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.6.0                    py35_0  
pickleshare               0.7.4            py35h9517181_0  
pip                       20.0.2                   pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            1.0.15           py35h93950c5_0  
ptyprocess                0.6.0                    py35_0  
pycparser                 2.19                     py35_0  
pygments                  2.6.1                      py_0  
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.4.6                      py_0  
pyqt                      5.9.2            py35h655552a_2  
pysocks                   1.6.8                    py35_0  
pytables                  3.4.4            py35h13cba08_0  
python                    3.5.6                hc167b69_0  
python-dateutil           2.8.1                      py_0  
pytz                      2019.3                     py_0  
pyzmq                     17.1.2           py35h1de35cc_0  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.7.2                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.20.1                   py35_0    Quantopian
requests-file             1.4.3                    py35_0  
scipy                     1.1.0            py35hcaad992_0  
send2trash                1.5.0                    py35_0  
setuptools                40.2.0                   py35_0  
simplegeneric             0.8.1                    py35_2  
sip                       4.19.8           py35h0a44026_0  
six                       1.11.0                   py35_1  
snappy                    1.1.7                he62c110_3  
sortedcontainers          2.0.5                    py35_0  
sqlalchemy                1.2.11           py35h1de35cc_0  
sqlite                    3.31.1               ha441bb4_0  
statsmodels               0.9.0            py35h917ab60_0  
terminado                 0.8.1                    py35_1  
testpath                  0.4.4                      py_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.10.0                     py_0  
tornado                   5.1.1            py35h1de35cc_0  
trading-calendars         1.11.1                   py35_0    Quantopian
traitlets                 4.3.2            py35hd3d1486_0  
urllib3                   1.23                     py35_0  
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py35_1  
wheel                     0.31.1                   py35_0  
widgetsnbextension        3.4.1                    py35_0  
xz                        5.2.4                h1de35cc_4  
zeromq                    4.2.5                h0a44026_1  
zipline                   1.3.0               np114py35_0    Quantopian
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  

So I have been using Zipline for the last couple of weeks. I used Andreas Clenow's fix for the benchmark; that is to return 0. However, I now have personal data from SPY, which i bought from a data service provider. I used the new get_benchmark_returns_from_file(filelike). I made some changes where in stead of ('date', 'return') format, i have my csv file of SPY data in the form of ('time, 'close') :

import pandas as pd
import requests
from trading_calendars import get_calendar
from datetime import datetime
import pytz
import logbook
import pandas as pd

log = logbook.Logger(__name__)

fl = '/Users/cemalarican/Desktop/THESIS/spy.csv'

def get_benchmark_returns_from_file(filelike=fl):
    """
    Get a Series of benchmark returns from a file
    Parameters
    ----------
    filelike : str or file-like object
        Path to the benchmark file.
        expected csv file format:
        date,return
        2020-01-02 00:00:00+00:00,0.01
        2020-01-03 00:00:00+00:00,-0.02
    """

    log.info("Reading benchmark returns from {}", filelike)

    df = pd.read_csv(
        filelike,
        index_col=['time'],
        parse_dates=['time'],
    ).tz_localize('utc')

    if 'close' not in df.columns:
        raise ValueError("The column 'return' not found in the "
                         "benchmark file \n"
                         "Expected benchmark file format :\n"
                         "date, return\n"
                         "2020-01-02 00:00:00+00:00,0.01\n"
                         "2020-01-03 00:00:00+00:00,-0.02\n")

    return df['close'].sort_index()

# print(get_benchmark_returns_from_file(filelike=fl))

### OUTPUT:
time
1993-02-01 00:00:00+00:00    0.007112
1993-02-02 00:00:00+00:00    0.002118
1993-02-03 00:00:00+00:00    0.010572
1993-02-04 00:00:00+00:00    0.004184
1993-02-05 00:00:00+00:00   -0.000696

##### 
So, it works. 

Also, if you add the first_date and last_data, for example:  start_time = datetime(2015, 1, 1, tzinfo=pytz.UTC), end_time = datetime(2016, 1, 1, tzinfo=pytz.UTC), and return df.loc[first_date, last_date] it also works.

Moreover, I change the loader.py section:
on line 217: 
    try:
        fl = '/Users/cemalarican/Desktop/THESIS/spy.csv'
        data = get_benchmark_returns_from_file(filelike=fl) 

and on line 22: i changed from.benchmarks import  get_benchmark_returns to get_benchmark_returns_from_file.

I hoped to that my algorithm would work, and the get the benchmark performance, like the alpha and the beta or the sharpe ratio. But I get the following error:

i print the equity pairs and the spread, but then below happens:
### THE ERROR:
[Equity(141 [IWF]), Equity(296 [VONG])]
-2.3829999999999956
[Equity(141 [IWF]), Equity(296 [VONG])]
-2.527000000000001
[Equity(141 [IWF]), Equity(296 [VONG])]
-2.3470000000000084

/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)
Traceback (most recent call last):
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/common.py", line 399, in _asarray_tuplesafe
    result[:] = values
ValueError: could not broadcast input array from shape (252,40) into shape (252)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/frame.py", line 2564, in _ensure_valid_index
    value = Series(value)
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/series.py", line 264, in __init__
    raise_cast_failure=True)
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/series.py", line 3277, in _sanitize_array
    subarr = _asarray_tuplesafe(data, dtype=dtype)
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/common.py", line 402, in _asarray_tuplesafe
    result[:] = [tuple(x) for x in values]
ValueError: cannot copy sequence with size 40 to array axis with dimension 252

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cemalarican/Desktop/THESIS/pairsTradingSingle.py", line 76, in <module>
    pairs_sim['IWF VS VONG'] = perf_Algo
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/frame.py", line 2519, in __setitem__
    self._set_item(key, value)
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/frame.py", line 2584, in _set_item
    self._ensure_valid_index(value)
  File "/opt/anaconda3/envs/zipline/lib/python3.5/site-packages/pandas/core/frame.py", line 2566, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

I was hoping that the benchmark would work, but it didnt. For anyone interested, I will share all the SPY data so it can also help others and share our answers. Stay healthy. Peace out.

Kind regards,

Cemal
[SPY.xlsx](https://github.com/quantopian/zipline/files/4548948/SPY.xlsx)

**Comment by cemal95** [comment]
So I found the solution.  I aslo provide the correct data. Basically renaming the get_becnhmark_returns_from_file and provide the file within the function. Note the data that I provided is a full data set of SPY since 1993

**Benchmarks.py: Use the following function:**

import pandas as pd
import requests
from trading_calendars import get_calendar
from datetime import datetime
import pytz
import logbook

import pandas as pd

log = logbook.Logger(__name__)


**def get_benchmark_returns(symbol='SPY'):**
    """
    Get a Series of benchmark returns from a file
    Parameters
    ----------
    filelike : str or file-like object
        Path to the benchmark file.
        expected csv file format:
        date,return
        2020-01-02 00:00:00+00:00,0.01
        2020-01-03 00:00:00+00:00,-0.02
    """
    filelike = 'filepath/file.csv
[SPY.xlsx](https://github.com/quantopian/zipline/files/4558740/SPY.xlsx)

'
    log.info("Reading benchmark returns from {}", filelike)

    df = pd.read_csv(
        filelike,
        index_col=['time'],
        parse_dates=['time'],
    ).tz_localize('utc')

    if 'adj_close' not in df.columns:
        raise ValueError("The column 'return' not found in the "
                         "benchmark file \n"
                         "Expected benchmark file format :\n"
                         "date, return\n"
                         "2020-01-02 00:00:00+00:00,0.01\n"
                         "2020-01-03 00:00:00+00:00,-0.02\n")

    return df['adj_close'].sort_index().pct_change().iloc[1:]
