### ISSUE TITLE
Problem with bundles ingest quandl

### ISSUE THREAD

**Issue by owl2** [quantopian/zipline#2698]
Dear Zipline Maintainers,

# Environment

<details>

* Operating System: Windows 10
* Python Version: 3.5.6
* How did you install Zipline: conda
* Python packages: `$ pip freeze` or `$ conda list`
(Anaconda)
alembic==0.7.7
asn1crypto==0.24.0
bcolz==0.12.1
Bottleneck==1.2.1
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
click==7.1.1
contextlib2==0.6.0.post1
cryptography==2.3.1
cyordereddict==0.2.2
Cython==0.28.5
decorator==4.4.2
empyrical==0.5.0
idna==2.7
intervaltree==2.1.0
Logbook==0.12.5
lru-dict==1.1.4
lxml==4.2.5
Mako==1.1.2
MarkupSafe==1.0
multipledispatch==0.6.0
networkx==1.11
numexpr==2.6.1
numpy==1.14.2
pandas==0.22.0
pandas-datareader==0.8.1
patsy==0.5.0
pycparser==2.20
pyOpenSSL==18.0.0
PySocks==1.6.8
python-dateutil==2.8.1
pytz==2019.3
requests==2.20.1
requests-file==1.4.3
scipy==1.1.0
six==1.11.0
sortedcontainers==2.1.0
SQLAlchemy==1.2.11
statsmodels==0.9.0
tables==3.4.4
toolz==0.10.0
trading-calendars==1.11.2
urllib3==1.23
win-inet-pton==1.0.1
wincertstore==0.2
zipline==1.3.0
</details>

# Description of Issue

After the setting of my Quandl API key, I run "zipline ingest -b quandl", and I hace this problem : 

"
[2020-05-03 18:08:58.231646] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
[2020-05-03 18:08:59.816725] ERROR: zipline.data.bundles.quandl: Exception raised reading Quandl data. Retrying.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 89, in fetch_data_table
    format_metadata_url(api_key)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 433, in _read
    filepath_or_buffer, encoding, compression)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\common.py", line 190, in get_filepath_or_buffer
    req = _urlopen(filepath_or_buffer)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
[2020-05-03 18:08:59.832325] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
[2020-05-03 18:09:00.192787] ERROR: zipline.data.bundles.quandl: Exception raised reading Quandl data. Retrying.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 89, in fetch_data_table
    format_metadata_url(api_key)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 433, in _read
    filepath_or_buffer, encoding, compression)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\common.py", line 190, in get_filepath_or_buffer
    req = _urlopen(filepath_or_buffer)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
[2020-05-03 18:09:00.208369] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
[2020-05-03 18:09:00.395883] ERROR: zipline.data.bundles.quandl: Exception raised reading Quandl data. Retrying.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 89, in fetch_data_table
    format_metadata_url(api_key)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 433, in _read
    filepath_or_buffer, encoding, compression)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\common.py", line 190, in get_filepath_or_buffer
    req = _urlopen(filepath_or_buffer)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
[2020-05-03 18:09:00.395883] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
[2020-05-03 18:09:00.601743] ERROR: zipline.data.bundles.quandl: Exception raised reading Quandl data. Retrying.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 89, in fetch_data_table
    format_metadata_url(api_key)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 433, in _read
    filepath_or_buffer, encoding, compression)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\common.py", line 190, in get_filepath_or_buffer
    req = _urlopen(filepath_or_buffer)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
[2020-05-03 18:09:00.601743] INFO: zipline.data.bundles.quandl: Downloading WIKI metadata.
[2020-05-03 18:09:00.883008] ERROR: zipline.data.bundles.quandl: Exception raised reading Quandl data. Retrying.
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 89, in fetch_data_table
    format_metadata_url(api_key)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\parsers.py", line 433, in _read
    filepath_or_buffer, encoding, compression)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\pandas\io\common.py", line 190, in get_filepath_or_buffer
    req = _urlopen(filepath_or_buffer)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\envs\zipline_2\Scripts\zipline-script.py", line 11, in <module>
    load_entry_point('zipline==1.3.0', 'console_scripts', 'zipline')()
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\__main__.py", line 348, in ingest
    show_progress,
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\core.py", line 451, in ingest
    pth.data_path([name, timestr], environ=environ),
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 209, in quandl_bundle
    environ.get('QUANDL_DOWNLOAD_ATTEMPTS', 5)
  File "C:\Users\User\Anaconda3\envs\zipline_2\lib\site-packages\zipline\data\bundles\quandl.py", line 113, in fetch_data_table
    "Failed to download Quandl data after %d attempts." % (retries)
ValueError: Failed to download Quandl data after 5 attempts.
"

Can you tell me if the problem can came from the missing of an eventual configuration or if it's a problem with the script quandl.py ?

Sincerely,

LMU

**Comment by samatix** [comment]
The issue is due to : 
**urllib.error.HTTPError: [HTTP Error 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429): Too Many Requests**
This means that you have [reached Quandl requests limit ](https://help.quandl.com/article/68-is-there-a-rate-limit-or-speed-limit-for-api-usage). 

You can set a lower QUANDL_DOWNLOAD_ATTEMPTS than 5 as well to see if you are having a specific issue. 

I would suggest that you retry in 10 min or tomorrow. 

Let me know if you still face any issue

**Comment by owl2** [comment]
Hello @samatix, 

I still have the problem.
I changed twice my Quandl API key, and I have the same problem...

**Comment by antek0308** [comment]
Hi, did someone manage to resolve this? I have the same problem

**Comment by samatix** [comment]
Hi @antek0308 , I would suggest to check https://github.com/stefan-jansen/zipline-reloaded. This version of Zipline is not maintained.
