### ISSUE TITLE
AttributeError: module 'zipline' has no attribute 'protocol'

### ISSUE THREAD

**Issue by Ripper1111** [quantopian/zipline#2709]
While installing zipline in Windows 7 i am getting 
Error 
AttributeError: module 'zipline' has no attribute 'protocol'

```
alembic           1.4.2
bcolz             1.2.1
Bottleneck        1.3.2
certifi           2020.4.5.1
chardet           3.0.4
click             7.1.2
contextlib2       0.6.0
cyordereddict     1.0.0
Cython            0.29.17
decorator         4.4.2
empyrical         0.5.3
idna              2.9
intervaltree      3.0.2
Logbook           1.5.3
lru-dict          1.1.6
lxml              4.5.0
Mako              1.1.2
MarkupSafe        1.1.1
networkx          2.4
numexpr           2.7.1
numpy             1.16.6+vanilla
pandas            0.25.3
pandas-datareader 0.8.1
patsy             0.5.1
pip               19.0.3
python-dateutil   2.8.1
python-editor     1.0.4
pytz              2020.1
requests          2.23.0
scipy             1.4.1
setuptools        40.8.0
six               1.14.0
sortedcontainers  2.1.0
SQLAlchemy        1.3.13
statsmodels       0.10.2
tables            3.6.1
toolz             0.10.0
trading-calendars 1.11.7
urllib3           1.25.9
wrapt             1.11.2
zipline           1.3.0

```
Error :

```
import zipline
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "G:\Fiverr\faruqmarican238\ziplinepy35\venv\lib\site-packages\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "G:\Fiverr\faruqmarican238\ziplinepy35\venv\lib\site-packages\zipline\utils\run_algo.py", line 27, in <module>
    from zipline.algorithm import TradingAlgorithm
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "G:\Fiverr\faruqmarican238\ziplinepy35\venv\lib\site-packages\zipline\algorithm.py", line 68, in <module>
    from zipline.finance.blotter import SimulationBlotter
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "G:\Fiverr\faruqmarican238\ziplinepy35\venv\lib\site-packages\zipline\finance\blotter\__init__.py", line 16, in <module>
    from .simulation_blotter import SimulationBlotter
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "G:\Fiverr\faruqmarican238\ziplinepy35\venv\lib\site-packages\zipline\finance\blotter\simulation_blotter.py", line 24, in <module>
    from zipline.finance.order import Order
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "G:\Fiverr\faruqmarican238\ziplinepy35\venv\lib\site-packages\zipline\finance\order.py", line 20, in <module>
    import zipline.protocol as zp
AttributeError: module 'zipline' has no attribute 'protocol'
```

**Comment by george-adams1** [comment]
@Ripper1111 Have you been able to solve this error?

**Comment by yilongeng** [comment]
i have the same problem.
Have anyone solved it?
