### ISSUE TITLE
How to ingest Quandl 

### ISSUE THREAD

**Issue by Jayant-Agarwal** [quantopian/zipline#2815]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:

#2479 

I am currently following a book(Trading Evolved) for learning the algorithmic trading but got **stuck on ingesting quandal what should I do now. I have tried to find the answer but can not get any solution for the same. PLEASE HELP

'''(zip35) C:\Users\jayan>zipline ingest -b quandl
Traceback (most recent call last):
   File "C:\Users\jayan\anaconda3\envs\zip35\Scripts\zipline-script.py", line 33, in <module>
      sys.exit(load_entry_point('zipline==1.4.1', 'console_scripts', 'zipline')())
   File "C:\Users\jayan\anaconda3\envs\zip35\Scripts\zipline-script.py", line 25, in 
      importlib_load_entry_point
   return next(matches).load()
   File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\importlib_metadata\__init__.py", line 
     100, in load
   module = import_module(match.group('module'))
   File "C:\Users\jayan\anaconda3\envs\zip35\lib\importlib\__init__.py", line 126, in import_module
   return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\zipline\__init__.py", line 29, in 
  <module>
 from .utils.run_algo import run_algorithm
 File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\zipline\utils\run_algo.py", line 20, in 
 <module>
 from zipline.data import bundles
 File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\zipline\data\bundles\__init__.py", line 
  2, in <module>
 from . import quandl  # noqa
 File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\zipline\data\bundles\quandl.py", line 
  16, in <module>
from . import core as bundles
File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\zipline\data\bundles\core.py", line 15, 
 in <module>
from ..minute_bars import (
File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\zipline\data\minute_bars.py", line 30, in 
 <module>
import tables
File "C:\Users\jayan\anaconda3\envs\zip35\lib\site-packages\tables\__init__.py", line 99, in <module>
from .utilsextension import (

ImportError: DLL load failed: The specified module could not be found.'''

Thank you to whoever replies to this.

**Comment by jiripik** [comment]
Please try the book [Hands-On Financial Trading with Python](https://www.amazon.com/Hands-Financial-Trading-Python-backtesting-ebook-dp-B08RPBMFMR/dp/B08RPBMFMR/ref=mt_other?_encoding=UTF8&me=&qid=). It does have working Quandl's Zipline feed
