### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by shivam017arora** [quantopian/zipline#2822]
Are you able to import that attribute yourself with something like `from logbook import Logger`, or is zipline's the only code that fails to import it?

Yes I am able to import logger from logbook. When I import Zipline, it gives me the attribute error. (AttributeError: module 'logbook' has no attribute 'Logger')

I installed it using Pip3 on my Macintosh. Python version: 3.8

**Comment by myradmehdizadeh** [comment]
Currently Zipline does not support Python 3.8.
Have you tried Python 3.5 or 3.6?

**Comment by shivam017arora** [comment]
I tried on 3.5, 3.6, 3.7, 3.8 and 3.9. When I finally got it installed, I could use Zipline in my CLI but when I imported "import zipline" it gives me the attribute error. (AttributeError: module 'logbook' has no attribute 'Logger'). 

I have been facing issues installing it for 2 days now. I even reinstalled my macOS due to this. I am in huge pain. Help!

**Comment by myradmehdizadeh** [comment]
What version of python do you currently use?
and can you give a list of all packages of your environment?

**Comment by shivam017arora** [comment]
When I try to install in version 3.5 like you proposed, it gave me this error. 

CLI:

> (base) Shivams-MBP:~ shivamarora$ conda create -n env_zipline python=3.5
> WARNING: A conda environment already exists at '/opt/miniconda3/envs/env_zipline'
> Remove existing environment (y/[n])? y
> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: done
> 
> ## Package Plan ##
> 
>   environment location: /opt/miniconda3/envs/env_zipline
> 
>   added / updated specs:
>     - python=3.5
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   ca-certificates    pkgs/main/osx-64::ca-certificates-2021.5.25-hecd8cb5_1
>   certifi            pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
>   libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
>   libedit            pkgs/main/osx-64::libedit-3.1.20210216-h9ed2024_1
>   libffi             pkgs/main/osx-64::libffi-3.2.1-h0a44026_1007
>   ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
>   openssl            pkgs/main/osx-64::openssl-1.0.2u-h1de35cc_0
>   pip                pkgs/main/osx-64::pip-10.0.1-py35_0
>   python             pkgs/main/osx-64::python-3.5.6-hc167b69_0
>   readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
>   setuptools         pkgs/main/osx-64::setuptools-40.2.0-py35_0
>   sqlite             pkgs/main/osx-64::sqlite-3.33.0-hffcf06c_0
>   tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
>   wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
>   xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
>   zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3
> 
> 
> Proceed ([y]/n)? y
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> #
> # To activate this environment, use
> #
> #     $ conda activate env_zipline
> #
> # To deactivate an active environment, use
> #
> #     $ conda deactivate
> 
> (base) Shivams-MBP:~ shivamarora$ conda activate env_zipline
> (env_zipline) Shivams-MBP:~ shivamarora$ conda install -c ml4t zipline-reloaded
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: - 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - zipline-reloaded -> python[version='>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
> 
> Your python: python=3.5
> 
> If python is on the left-most side of the chain, that's the version you've asked for.
> When python appears to the right, that indicates that the thing on the left is somehow
> not available for the python version you are constrained to. Note that conda will not
> change your python version to a different minor version unless you explicitly specify
> that.

**Comment by shivam017arora** [comment]
When I try for 3.7 as mentioned in the error above:

It gives me this error:

> (env_zipline) Shivams-MBP:~ shivamarora$ conda install -c ml4t zipline-reloaded
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: \ 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> (env_zipline) Shivams-MBP:~ shivamarora$

**Comment by myradmehdizadeh** [comment]
There are similar issue on zipline-reloaded repository. Try reading them. Specially the closed ones.
https://github.com/stefan-jansen/zipline-reloaded/issues?q=is%3Aissue+is%3Aclosed

If you want to use the plain version of zipline, I recommend using Python 3.6.

**Comment by shivam017arora** [comment]
Thanks!

I installed zipline-reloaded using mamba like showed in the issues.

> mamba install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded=2.0.0.post1
> 
>                   __    __    __    __
>                  /  \  /  \  /  \  /  \
>                 /    \/    \/    \/    \
> ███████████████/  /██/  /██/  /██/  /████████████████████████
>               /  / \   / \   / \   / \  \____
>              /  /   \_/   \_/   \_/   \    o \__,
>             / _/                       \_____/  `
>             |/
>         ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
>         ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
>         ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
>         ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
>         ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
>         ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝
> 
>         mamba (0.13.0) supported by @QuantStack
> 
>         GitHub:  https://github.com/mamba-org/mamba
>         Twitter: https://twitter.com/QuantStack
> 
> █████████████████████████████████████████████████████████████
> 
> 
> Looking for: ['zipline-reloaded=2.0.0.post1']
> 
> conda-forge/osx-64       Using cache
> conda-forge/noarch       Using cache
> pkgs/main/osx-64         [====================] (00m:00s) No change
> pkgs/main/noarch         [====================] (00m:00s) No change
> pkgs/r/noarch            [====================] (00m:00s) No change
> pkgs/r/osx-64            [====================] (00m:00s) No change
> ml4t/noarch              [====================] (00m:00s) No change
> ranaroussi/osx-64        [====================] (00m:00s) No change
> ml4t/osx-64              [====================] (00m:00s) No change
> ranaroussi/noarch        [====================] (00m:00s) No change
> Transaction
> 
>   Prefix: /opt/miniconda3/envs/env_zipline
> 
>   Updating specs:
> 
>    - zipline-reloaded==2.0.0.post1
> 
> 
>   Package                  Version  Build                   Channel                  Size
> ───────────────────────────────────────────────────────────────────────────────────────────
>   Install:
> ───────────────────────────────────────────────────────────────────────────────────────────
> 
>   alembic                    1.6.5  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   bcolz-zipline              1.2.3  py37hf1f42d3_0          ml4t/osx-64            880 KB
>   blas                         1.0  mkl                     pkgs/main/osx-64       Cached
>   bottleneck                 1.3.2  py37h37391d0_3          conda-forge/osx-64     117 KB
>   brotlipy                   0.7.0  py37hf967b71_1001       conda-forge/osx-64     357 KB
>   cached-property            1.5.2  hd8ed1ab_1              conda-forge/noarch     Cached
>   cached_property            1.5.2  pyha770c72_1            conda-forge/noarch     Cached
>   cffi                      1.14.5  py37h4d371b4_0          conda-forge/osx-64     218 KB
>   chardet                    4.0.0  py37hf985489_1          conda-forge/osx-64     198 KB
>   click                      8.0.1  py37hf985489_0          conda-forge/osx-64     145 KB
>   cryptography               3.4.7  py37hce4a858_0          conda-forge/osx-64     754 KB
>   decorator                  4.4.2  py_0                    conda-forge/noarch     Cached
>   empyrical-reloaded         0.5.7  py37_0                  ml4t/osx-64             67 KB
>   greenlet                   1.1.0  py37h23ab428_0          pkgs/main/osx-64        78 KB
>   h5py                       3.2.1  nompi_py37hdf859c4_100  conda-forge/osx-64       1 MB
>   hdf5                      1.10.6  hdbbcd12_0              pkgs/main/osx-64       Cached
>   icu                         68.1  h23ab428_0              pkgs/main/osx-64       Cached
>   idna                        2.10  pyh9f0ad1d_0            conda-forge/noarch     Cached
>   importlib-metadata         4.5.0  py37hf985489_0          conda-forge/osx-64      31 KB
>   intervaltree               3.1.0  py_0                    pkgs/main/noarch       Cached
>   iso3166                    1.0.1  pyh9f0ad1d_0            conda-forge/noarch     Cached
>   iso4217             1.6.20180829  py_0                    conda-forge/noarch     Cached
>   libblas                    3.9.0  9_mkl                   conda-forge/osx-64     Cached
>   libcblas                   3.9.0  9_mkl                   conda-forge/osx-64     Cached
>   libgfortran                3.0.1  0                       conda-forge/osx-64     Cached
>   libiconv                    1.16  haf1e3a3_0              conda-forge/osx-64     Cached
>   liblapack                  3.9.0  9_mkl                   conda-forge/osx-64     Cached
>   libxml2                   2.9.12  h93ec3fd_0              conda-forge/osx-64     Cached
>   libxslt                   1.1.33  h5739fc3_2              conda-forge/osx-64     Cached
>   llvm-openmp               11.1.0  hda6cdc1_1              conda-forge/osx-64     Cached
>   logbook                    1.5.3  py37_0                  ml4t/osx-64            103 KB
>   lru-dict                   1.1.6  py37hf967b71_3          conda-forge/osx-64      12 KB
>   lxml                       4.6.3  py37h250624f_0          conda-forge/osx-64       1 MB
>   mako                       1.1.4  pyh44b312d_0            conda-forge/noarch     Cached
>   markupsafe                 2.0.1  py37h271585c_0          conda-forge/osx-64      21 KB
>   mkl                     2021.2.0  h08c4f10_389            conda-forge/osx-64     Cached
>   mkl-service                2.4.0  py37h271585c_0          conda-forge/osx-64      42 KB
>   multipledispatch           0.6.0  py_0                    conda-forge/noarch     Cached
>   multitasking               0.0.9  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   networkx                   2.5.1  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   numexpr                    2.7.3  py37h5873af2_1          pkgs/main/osx-64       124 KB
>   numpy                     1.20.3  py37h84c02c4_1          conda-forge/osx-64       5 MB
>   pandas                     1.2.4  py37hb2f4e1b_0          pkgs/main/osx-64         8 MB
>   pandas-datareader          0.9.0  pyh44b312d_0            conda-forge/noarch     Cached
>   patsy                      0.5.1  py_0                    conda-forge/noarch     Cached
>   pycparser                   2.20  pyh9f0ad1d_2            conda-forge/noarch     Cached
>   pyopenssl                 20.0.1  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   pysocks                    1.7.1  py37hf985489_3          conda-forge/osx-64      27 KB
>   python-dateutil            2.8.1  py_0                    conda-forge/noarch     Cached
>   python-editor              1.0.4  py_0                    conda-forge/noarch     Cached
>   python-interface           1.6.0  py_0                    conda-forge/noarch     Cached
>   python_abi                   3.7  1_cp37m                 conda-forge/osx-64       4 KB
>   pytz                      2021.1  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   requests                  2.25.1  pyhd3deb0d_0            conda-forge/noarch     Cached
>   scipy                      1.6.2  py37hd5f7400_1          pkgs/main/osx-64        14 MB
>   six                       1.16.0  pyh6c4a22f_0            conda-forge/noarch     Cached
>   sortedcontainers           2.4.0  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   sqlalchemy                1.4.17  py37h271585c_0          conda-forge/osx-64       2 MB
>   statsmodels               0.12.2  py37h183f225_0          conda-forge/osx-64      10 MB
>   ta-lib                    0.4.19  py37h7772d1b_0          ml4t/osx-64              1 MB
>   tbb                     2021.2.0  hf7b0b51_0              pkgs/main/osx-64       Cached
>   toolz                     0.11.1  py_0                    conda-forge/noarch     Cached
>   trading-calendars          2.1.1  pyhd3deb0d_0            conda-forge/noarch     Cached
>   typing_extensions       3.10.0.0  pyha770c72_0            conda-forge/noarch      28 KB
>   urllib3                   1.26.5  pyhd8ed1ab_0            conda-forge/noarch     Cached
>   yfinance                  0.1.59  py_0                    ml4t/noarch            Cached
>   zipline-reloaded     2.0.0.post1  py37hf1f42d3_0          ml4t/osx-64              2 MB
>   zipp                       3.4.1  pyhd8ed1ab_0            conda-forge/noarch     Cached
> 
>   Change:
> ───────────────────────────────────────────────────────────────────────────────────────────
> 
>   certifi                2021.5.30  py37hecd8cb5_0          installed                    
>   certifi                2021.5.30  py37hf985489_0          conda-forge/osx-64     141 KB
>   openssl                   1.1.1k  h9ed2024_0              installed                    
>   openssl                   1.1.1k  h0d85af4_0              conda-forge/osx-64     Cached
> 
>   Upgrade:
> ───────────────────────────────────────────────────────────────────────────────────────────
> 
>   ca-certificates        2021.5.25  hecd8cb5_1              installed                    
>   ca-certificates        2021.5.30  h033912b_0              conda-forge/osx-64     Cached
> 
>   Summary:
> 
>   Install: 68 packages
>   Change: 2 packages
>   Upgrade: 1 packages
> 
>   Total download: 49 MB
> 
> ───────────────────────────────────────────────────────────────────────────────────────────
> 
> Finished python_abi                           (00m:00s)               4 KB     30 KB/s
> Finished typing_extensions                    (00m:00s)              28 KB    230 KB/s
> Finished markupsafe                           (00m:00s)              21 KB    162 KB/s
> Finished cffi                                 (00m:00s)             218 KB      1 MB/s
> Finished pysocks                              (00m:00s)              27 KB     54 KB/s
> Finished bottleneck                           (00m:00s)             117 KB    223 KB/s
> Finished brotlipy                             (00m:00s)             357 KB    418 KB/s
> Finished chardet                              (00m:00s)             198 KB    221 KB/s
> Finished cryptography                         (00m:00s)             754 KB    771 KB/s
> Finished lxml                                 (00m:01s)               1 MB    830 KB/s
> Finished sqlalchemy                           (00m:01s)               2 MB      1 MB/s
> Finished h5py                                 (00m:01s)               1 MB    578 KB/s
> Finished certifi                              (00m:00s)             141 KB     54 KB/s
> Finished statsmodels                          (00m:05s)              10 MB      4 MB/s
> Finished mkl-service                          (00m:02s)              42 KB     14 KB/s
> Finished logbook                              (00m:03s)             103 KB     34 KB/s
> Finished importlib-metadata                   (00m:02s)              31 KB      9 KB/s
> Finished pandas                               (00m:05s)               8 MB      2 MB/s
> Finished numpy                                (00m:04s)               5 MB      1 MB/s
> Finished numexpr                              (00m:03s)             124 KB     28 KB/s
> Finished scipy                                (00m:05s)              14 MB      3 MB/s
> Finished greenlet                             (00m:03s)              78 KB     16 KB/s
> Finished lru-dict                             (00m:03s)              12 KB      2 KB/s
> Finished empyrical-reloaded                   (00m:03s)              67 KB     13 KB/s
> Finished ta-lib                               (00m:05s)               1 MB    240 KB/s
> Finished zipline-reloaded                     (00m:05s)               2 MB    308 KB/s
> Finished click                                (00m:03s)             145 KB     24 KB/s
> Finished bcolz-zipline                        (00m:02s)             880 KB    101 KB/s
> Downloading  [===========================================================================] (00m:09s) 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> (env_zipline) Shivams-MBP:~ shivamarora$ conda list
> # packages in environment at /opt/miniconda3/envs/env_zipline:
> #
> # Name                    Version                   Build  Channel
> alembic                   1.6.5              pyhd8ed1ab_0    conda-forge
> bcolz-zipline             1.2.3            py37hf1f42d3_0    ml4t
> blas                      1.0                         mkl  
> bottleneck                1.3.2            py37h37391d0_3    conda-forge
> brotlipy                  0.7.0           py37hf967b71_1001    conda-forge
> ca-certificates           2021.5.30            h033912b_0    conda-forge
> cached-property           1.5.2                hd8ed1ab_1    conda-forge
> cached_property           1.5.2              pyha770c72_1    conda-forge
> certifi                   2021.5.30        py37hf985489_0    conda-forge
> cffi                      1.14.5           py37h4d371b4_0    conda-forge
> chardet                   4.0.0            py37hf985489_1    conda-forge
> click                     8.0.1            py37hf985489_0    conda-forge
> cryptography              3.4.7            py37hce4a858_0    conda-forge
> decorator                 4.4.2                      py_0    conda-forge
> empyrical-reloaded        0.5.7                    py37_0    ml4t
> greenlet                  1.1.0            py37h23ab428_0  
> h5py                      3.2.1           nompi_py37hdf859c4_100    conda-forge
> hdf5                      1.10.6               hdbbcd12_0  
> icu                       68.1                 h23ab428_0  
> idna                      2.10               pyh9f0ad1d_0    conda-forge
> importlib-metadata        4.5.0            py37hf985489_0    conda-forge
> intervaltree              3.1.0                      py_0  
> iso3166                   1.0.1              pyh9f0ad1d_0    conda-forge
> iso4217                   1.6.20180829               py_0    conda-forge
> libblas                   3.9.0                     9_mkl    conda-forge
> libcblas                  3.9.0                     9_mkl    conda-forge
> libcxx                    10.0.0                        1  
> libffi                    3.3                  hb1e8313_2  
> libgfortran               3.0.1                         0    conda-forge
> libiconv                  1.16                 haf1e3a3_0    conda-forge
> liblapack                 3.9.0                     9_mkl    conda-forge
> libxml2                   2.9.12               h93ec3fd_0    conda-forge
> libxslt                   1.1.33               h5739fc3_2    conda-forge
> llvm-openmp               11.1.0               hda6cdc1_1    conda-forge
> logbook                   1.5.3                    py37_0    ml4t
> lru-dict                  1.1.6            py37hf967b71_3    conda-forge
> lxml                      4.6.3            py37h250624f_0    conda-forge
> mako                      1.1.4              pyh44b312d_0    conda-forge
> markupsafe                2.0.1            py37h271585c_0    conda-forge
> mkl                       2021.2.0           h08c4f10_389    conda-forge
> mkl-service               2.4.0            py37h271585c_0    conda-forge
> multipledispatch          0.6.0                      py_0    conda-forge
> multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
> ncurses                   6.2                  h0a44026_1  
> networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
> numexpr                   2.7.3            py37h5873af2_1  
> numpy                     1.20.3           py37h84c02c4_1    conda-forge
> openssl                   1.1.1k               h0d85af4_0    conda-forge
> pandas                    1.2.4            py37hb2f4e1b_0  
> pandas-datareader         0.9.0              pyh44b312d_0    conda-forge
> patsy                     0.5.1                      py_0    conda-forge
> pip                       21.1.1           py37hecd8cb5_0  
> pycparser                 2.20               pyh9f0ad1d_2    conda-forge
> pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
> pysocks                   1.7.1            py37hf985489_3    conda-forge
> python                    3.7.10               h88f2d9e_0  
> python-dateutil           2.8.1                      py_0    conda-forge
> python-editor             1.0.4                      py_0    conda-forge
> python-interface          1.6.0                      py_0    conda-forge
> python_abi                3.7                     1_cp37m    conda-forge
> pytz                      2021.1             pyhd8ed1ab_0    conda-forge
> readline                  8.1                  h9ed2024_0  
> requests                  2.25.1             pyhd3deb0d_0    conda-forge
> scipy                     1.6.2            py37hd5f7400_1  
> setuptools                52.0.0           py37hecd8cb5_0  
> six                       1.16.0             pyh6c4a22f_0    conda-forge
> sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
> sqlalchemy                1.4.17           py37h271585c_0    conda-forge
> sqlite                    3.35.4               hce871da_0  
> statsmodels               0.12.2           py37h183f225_0    conda-forge
> ta-lib                    0.4.19           py37h7772d1b_0    ml4t
> tbb                       2021.2.0             hf7b0b51_0  
> tk                        8.6.10               hb0a8c7a_0  
> toolz                     0.11.1                     py_0    conda-forge
> trading-calendars         2.1.1              pyhd3deb0d_0    conda-forge
> typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
> urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
> wheel                     0.36.2             pyhd3eb1b0_0  
> xz                        5.2.5                h1de35cc_0  
> yfinance                  0.1.59                     py_0    ml4t
> zipline-reloaded          2.0.0.post1      py37hf1f42d3_0    ml4t
> zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
> zlib                      1.2.11               h1de35cc_3  
> (env_zipline) Shivams-MBP:~ shivamarora$ 


But again, as I was experiencing before when I installed using Pip3. 

I go to jupyter notebook and write %load_ext biplane

I get the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-2-f428cd08e5fe> in <module>
----> 1 get_ipython().run_line_magic('load_ext', 'zipline')

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2346                 kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2347             with self.builtin_trap:
-> 2348                 result = fn(*args, **kwargs)
   2349             return result
   2350 

<decorator-gen-57> in load_ext(self, module_str)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     31         if not module_str:
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 
     35         if res == 'already loaded':

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     78             if module_str not in sys.modules:
     79                 with prepended_to_syspath(self.ipython_extension_dir):
---> 80                     mod = import_module(module_str)
     81                     if mod.__file__.startswith(self.ipython_extension_dir):
     82                         print(("Loading extensions from {dir} is deprecated. "

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_bootstrap.py in _gcd_import(name, package, level)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_bootstrap.py in _load_unlocked(spec)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_bootstrap_external.py in exec_module(self, module)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zipline/__init__.py in <module>
     22 
     23 from . import data
---> 24 from . import finance
     25 from . import gens
     26 from . import utils

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zipline/finance/__init__.py in <module>
     14 # limitations under the License.
     15 
---> 16 from . import execution, trading
     17 
     18 __all__ = ["trading", "execution"]

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zipline/finance/trading.py in <module>
     20 from zipline.utils.pandas_utils import normalize_date
     21 
---> 22 log = logbook.Logger("Trading")
     23 
     24 

AttributeError: module 'logbook' has no attribute 'Logger'

**Comment by shivam017arora** [comment]
When I run the command ziplane in CLI, I get the same error:

(base) Shivams-MBP:~ shivamarora$ zipline
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/zipline", line 5, in <module>
    from zipline.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zipline/__init__.py", line 24, in <module>
    from . import finance
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zipline/finance/__init__.py", line 16, in <module>
    from . import execution, trading
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/zipline/finance/trading.py", line 22, in <module>
    log = logbook.Logger("Trading")
AttributeError: module 'logbook' has no attribute 'Logger'
(base) Shivams-MBP:~ shivamarora$

**Comment by agcap1** [comment]
Hey @shivam017arora did you ever figure it out? I'm having the same problem and am ready to throw my computer in the lake. I need help
