### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by taeyurl** [quantopian/zipline#2838]
Dear Zipline Maintainers,

Before I tell you about my issue, let me describe my environment:
* Operating System: Windows
* Python Version: 3.8
* How did you install Zipline: pip

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

Traceback (most recent call last):
  File "zipline/data/bundles/alpaca_api.py", line 12, in <module>
    import zipline.config
  File "c:\users\mpower\zipline-trader\zipline\__init__.py", line 30, in <module>
    from .utils.run_algo import run_algorithm
  File "c:\users\mpower\zipline-trader\zipline\utils\run_algo.py", line 24, in <module>
    from zipline.data import bundles
  File "c:\users\mpower\zipline-trader\zipline\data\bundles\__init__.py", line 2, in <module>
    from . import quandl  # noqa
  File "c:\users\mpower\zipline-trader\zipline\data\bundles\quandl.py", line 16, in <module>
    from . import core as bundles
  File "c:\users\mpower\zipline-trader\zipline\data\bundles\core.py", line 13, in <module>
    from ..adjustments import SQLiteAdjustmentReader, SQLiteAdjustmentWriter
  File "c:\users\mpower\zipline-trader\zipline\data\adjustments.py", line 29, in <module>
    from ._adjustments import load_adjustments_from_sqlite
  File "zipline\data\_adjustments.pyx", line 35, in init zipline.data._adjustments
    from zipline.assets.asset_writer import (
  File "c:\users\mpower\zipline-trader\zipline\assets\__init__.py", line 22, in <module>
    from .assets import (
  File "c:\users\mpower\zipline-trader\zipline\assets\assets.py", line 67, in <module>
    from .asset_writer import (
  File "c:\users\mpower\zipline-trader\zipline\assets\asset_writer.py", line 453, in <module>
    class AssetDBWriter(object):
  File "c:\users\mpower\zipline-trader\zipline\assets\asset_writer.py", line 464, in AssetDBWriter
    def __init__(self, engine, asset_finder=None):
  File "c:\users\mpower\zipline-trader\zipline\utils\preprocess.py", line 109, in _decorator
    return _build_preprocessed_function(
  File "c:\users\mpower\zipline-trader\zipline\utils\preprocess.py", line 247, in _build_preprocessed_function
    new_func.__code__ = CodeType(*map(getitem(args), _code_argorder))
TypeError: an integer is required (got type bytes)

Sincerely,
Paul

**Comment by andycwang** [comment]
***@***.***邮箱联系我，谢谢！

**Comment by taeyurl** [comment]
Hi Andy.

Are you able to help with posted problem on Github?

Thanks, Paul

**Comment by taeyurl** [comment]
Just used 3.7.5..
