### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by strimp099** [quantopian/zipline#394]
Greetings,

Running a dead-simple algo just to get started and receiving errors in what I suspect is an attempted coercion of missing data (converted to np.nan) to integers. The code is as follows:

    from zipline.api import order_target, record, symbol, history, add_history
    import numpy as np

    def initialize(context):
        add_history(100, '1d', 'price')
        context.idx = 0

    def handle_data(context, data):
        context.idx += 1
        if context.idx < 100:
            return
        price_history = history(bar_count=100, frequency='1d', field='price')
        for stock in data:
            print data[stock].price

I run the algo through the CLI as such:

    run_algo.py -f risk_parity.py --start 2013-1-1 --end 2014-9-1 --symbols USCI,SCHB,SCHR,CWI,SCHA,SCHG,PCY,PHB -o risk_parity.pickle

I receive the following error:

    Traceback (most recent call last):
      File "/usr/local/anaconda/bin/run_algo.py", line 24, in <module>
        run_pipeline(print_algo=True, **parsed)
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/utils/cli.py", line 192, in run_pipeline
        perf = algo.run(source)
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/algorithm.py", line 423, in run
        for perf in self.gen:
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/gens/tradesimulation.py", line 106, in transform
        for date, snapshot in stream_in:
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/gens/composites.py", line 34, in date_sorted_sources
        for _, message in sorted_stream:
      File "/usr/local/anaconda/lib/python2.7/heapq.py", line 376, in merge
        h_append([next(), itnum, next])
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/gens/composites.py", line 22, in _decorate_source
        for message in source:
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/gens/composites.py", line 34, in date_sorted_sources
        for _, message in sorted_stream:
      File "/usr/local/anaconda/lib/python2.7/heapq.py", line 376, in merge
        h_append([next(), itnum, next])
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/gens/composites.py", line 22, in _decorate_source
        for message in source:
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/sources/data_source.py", line 64, in next
        return self.mapped_data.next()
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/sources/data_source.py", line 58, in mapped_data
        yield Event(self.apply_mapping(row))
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/sources/data_source.py", line 50, in apply_mapping
        in self.mapping.items()}
      File "/usr/local/anaconda/lib/python2.7/site-packages/zipline-0.7.0-py2.7.egg/zipline/sources/data_source.py", line 49, in <dictcomp>
        for target, (mapping_func, source_key)
    ValueError: cannot convert float NaN to integer

Is there any guidance on this error?

**Comment by DerekHunter** [comment]
Just ran into this problem again this evening. Has any progress been made on it?

**Comment by llllllllll** [comment]
I am unable to reproduce this on master with the provided code and cli args. If you have another reproduction case, please re-open this issue. Sorry that there has been no word on this for so long.

**Comment by cwse89** [comment]
Still getting this issue guys, any solutions out there?

**Comment by FreddieV4** [comment]
Hi @cwse89 would you be able to provide some code that results in this error? I can't reproduce the error from the initial code that OP posted (there have been many API changes since then)

**Comment by lizongkai-big** [comment]
I think this code can help you avoid this error.
```
n = NaN
print n
# three conditional judgements
# if n is nan:
# if n is np.nan:
# if np.isnan(n):
    print 'This num is NaN\n'
else:
    n_int = int(n)
    print n_int
```
