### ISSUE TITLE
Some algos produce an IndexError with history

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#447]
There are a couple of emails on the zipline mailing list that are reporting problems with history. I am able to reproduce on master and get this:

``` python
Traceback (most recent call last):
  File "algo.py", line 143, in <module>
    perf_manual = algo_obj.run(data)
  File "/home/wiecki/working/projects/quant/zipline/zipline/algorithm.py", line 476, in run
    for perf in self.gen:
  File "/home/wiecki/working/projects/quant/zipline/zipline/gens/tradesimulation.py", line 129, in transform
    self.algo.instant_fill,
  File "/home/wiecki/working/projects/quant/zipline/zipline/gens/tradesimulation.py", line 234, in _process_snapshot
    new_orders = self._call_handle_data()
  File "/home/wiecki/working/projects/quant/zipline/zipline/gens/tradesimulation.py", line 258, in _call_handle_data
    self.simulation_dt,
  File "/home/wiecki/working/projects/quant/zipline/zipline/utils/events.py", line 194, in handle_data
    event.handle_data(context, data, dt)
  File "/home/wiecki/working/projects/quant/zipline/zipline/utils/events.py", line 212, in handle_data
    self.callback(context, data)
  File "/home/wiecki/working/projects/quant/zipline/zipline/algorithm.py", line 271, in handle_data
    self._handle_data(self, data)
  File "algo.py", line 105, in handle_data
    price_history = history(bar_count=30, frequency='1d', field='price')
  File "/home/wiecki/working/projects/quant/zipline/zipline/utils/api_support.py", line 51, in wrapped
    return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
  File "/home/wiecki/working/projects/quant/zipline/zipline/algorithm.py", line 996, in history
    return self.history_container.get_history(history_spec, self.datetime)
  File "/home/wiecki/working/projects/quant/zipline/zipline/history/history_container.py", line 837, in get_history
    self.last_known_prior_values,
  File "/home/wiecki/working/projects/quant/zipline/zipline/history/history_container.py", line 46, in ffill_buffer_from_prior_values
    nan_sids = buffer_frame.iloc[0].isnull()
  File "/home/wiecki/envs/zipline_p14/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1194, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/home/wiecki/envs/zipline_p14/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1464, in _getitem_axis
    return self._get_loc(key, axis=axis)
  File "/home/wiecki/envs/zipline_p14/local/lib/python2.7/site-packages/pandas/core/indexing.py", line 91, in _get_loc
    return self.obj._ixs(key, axis=axis)
  File "/home/wiecki/envs/zipline_p14/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1667, in _ixs
    label = self.index[i]
  File "/home/wiecki/envs/zipline_p14/local/lib/python2.7/site-packages/pandas/tseries/index.py", line 1264, in __getitem__
    val = getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by sebnil** [comment]
Is someone actively working on this issue? I am trading on the Swedish market and run into this issue for most of the stocks that I trade with. 
Are there any good alternatives to using the history function as a work around?

**Comment by sebnil** [comment]
I investigated some more and the code below should show the problem:
```
from zipline.api import order_target, history, add_history
from zipline.utils.factory import load_from_yahoo
from zipline.algorithm import TradingAlgorithm


def initialize(context):
    add_history(10, '1d', 'price')
    context.i = 0


def handle_data(context, data):
    context.i += 1

    # this function will crash on some
    prices = history(10, '1d', 'price')

    order_target(context.security, 1000)


if __name__ == '__main__':

    # run the algorithm on these securities one by one
    securities = [
        'SKF-B.ST', # swedish company that does not work
        'VOLV-A.ST', # swedish company that does not work
        'AZN.ST', # swedish company that does not work
        'AAPL', # US company works
        'TSLA', # US company works
    ]
    for security in securities:
        # get data from yahoo
        data = load_from_yahoo(stocks=[security], indexes={}, start='20140101', end='20140501')

        # create and run algorithm
        algo = TradingAlgorithm(
            initialize=initialize,
            handle_data=handle_data)
        algo.security = security

        try:
            results = algo.run(data)
            print('OK running algorithm on security.: {}'.format(security))
        except IndexError:
            print('Could not run algorithm on security: {}'.format(security))


```

**Comment by tobsch** [comment]
Same issue on the german market (CET Timezone). Any ideas?

**Comment by shlomoa** [comment]
My advice is lame, sorry.
Either dump zipline or debug yourself.
I took the second path which turned to a long path joining the first.....

**Comment by tobsch** [comment]
and what did you end up with?

**Comment by kenhersey** [comment]
Hey Thomas - I think I have the cause of this issue identified (or at least one time when this is being hit).

Whenever I have a data file which includes data on a day which zipline considers to not be a trading day, this error is flagged when it hits the ffill_buffer_from_prior_values() function.

To reproduce: just generate a csv file from a yahoo retrieval, and add a line in the datafile for MLK day or some other holiday. Make sure you add it after a point after which the history would have warmed up (else you won't see the issue). That should generate the error.

This also correlates to those who are having trouble with futures data inputs like me and foreign data inputs (tobsch, noted above).

Knowing the cause, I'm hopeful you will know where to resolve, and/or identify a workaround. Perhaps we will need to change the trading calendar to fix this (or have it ignore the calendar).

Best,
Ken

**Comment by tobsch** [comment]
Hi,

that sounds reasonable.
Why don't you integrate a library like this one and let the user define the region?
 
https://github.com/novapost/workalendar

Best,

Tobias

**Comment by kenhersey** [comment]
Interesting package - I wonder if "working day" == "trading day"... likely. But, then we need to be able to define a superset of the calendars if you combine for example different country data in the same portfolio. (Then the ffills would fix the data.)

Thus, my hope is that there is a mechanism that Thomas can readily identify for the user being able to redefine the current trading calendar as the index of our pandas Panel (portfolio), which will be a superset of all the items (securities). If so, that would be proper operation.

**Comment by shlomoa** [comment]
A simulator with one identical method handle_data
Except for that it is totally different.

**Comment by sebnil** [comment]
I solved it by just not using the history function at all. Why does zipline have so much complexity for getting historical data when it can be done using pandas anyway? (not a criticism, but a genuine question)

I did something like this:
```
historical_data = better_history.get_history(context)
```
And then a new file with a simple function:
```
def get_history(context):
    try:
        return context.data[:context.datetime]
    except AttributeError:
        logging.error('context.data is not set. Make sure to include it in context variable.')
        raise
```

**Comment by twiecki** [comment]
Not sure what happened with the crazy re-assignments.

**Comment by twiecki** [comment]
Anyone who could take a look at this? @brianpfink maybe? CC @ehebert @ssanderson @jfkirk

**Comment by ricpruss** [comment]
One work around is to not trade days that the trading calendar thinks are non-trading days.

i.e.
def handle_data(algo, data):
    if not algo.trading_environment.is_trading_day(algo.get_datetime().date()):
        return

    Rest of your algo....

The other is seems to a custom trading calendar, if someone has an easy way to derive a trading calendar from a panel I would prefer that because clearly this solution I gave skips real trading days which are in the history data, this is obviously more true for people not using US trading days..
