### ISSUE TITLE
Port fetch_csv() to zipline

### ISSUE THREAD

**Issue by twiecki** [quantopian/zipline#448]
Quantopian algos can use `fetch_csv()`. It should be pretty straight froward to port it to zipline and increase portability.

**Comment by richafrank** [comment]
Part of https://github.com/quantopian/zipline/pull/858

**Comment by thiagof** [comment]
+1

**Comment by llllllllll** [comment]
done

**Comment by girmax** [comment]
fetch_csv() was ported?

**Comment by richafrank** [comment]
Hi @girmax ,

It looks like you're running `zipline.api.fetch_csv` outside of a trading algorithm, which doesn't have much use, since `fetch_csv` just adds the new data to the running algo.  I think we could have a better error message here.

Instead of calling `fetch_csv` directly from module scope in your notebook, you'll want to call it from `initialize` in your algo, and then run your algo with the zipline [cell magic] (http://www.zipline.io/beginner-tutorial.html#ipython-notebook), for example.

**Comment by adamluc** [comment]
I am working to download the following dataset into a zipline algorithim via fetch_csv and running into an issue. Is there an example zipline algorithm that uses fetch_csv that I can review? Not sure if I am doing something wrong.

Thank you!

First, the code I am using is the following:

System specs: Running zipline v1.0.2, Mac OS El Capitan 10.11.6.

`
from zipline.api import fetch_csv

def initialize(context):
    fetch_csv('https://www.quandl.com/api/v3/datasets/YAHOO/INDEX_VIX.csv?api_key=5aSzjTEym3ZyeocFnynn', symbol='VXST', date_column='Date' )
`
The error I get is the following:
`Traceback (most recent call last):
  File "test-5.py", line 713, in <module>
    algo.run(data, overwrite_sim_params=False)
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/algorithm.py", line 697, in run
    for perf in self.get_generator():
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/algorithm.py", line 596, in get_generator
    return self._create_generator(self.sim_params)
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/algorithm.py", line 567, in _create_generator
    self.initialize(*self.initialize_args, **self.initialize_kwargs)
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/algorithm.py", line 451, in initialize
    self._initialize(self, *args, **kwargs)
  File "test-5.py", line 211, in initialize
    fetch_csv('https://www.quandl.com/api/v3/datasets/YAHOO/INDEX_VIX.csv?api_key=5aSzjTEym3ZyeocFnynn', symbol='VXST', date_column='Date' )
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/utils/api_support.py", line 51, in wrapped
    return getattr(get_algo_instance(), f.__name__)(*args, **kwargs)
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/algorithm.py", line 1034, in fetch_csv
    **kwargs
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/sources/requests_csv.py", line 510, in __init__
    self.df = self.load_df()
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/sources/requests_csv.py", line 283, in load_df
    df = self.fetch_data()
  File "//anaconda/lib/python2.7/site-packages/zipline-0+untagged.4617.ga73aeda-py2.7-macosx-10.6-x86_64.egg/zipline/sources/requests_csv.py", line 580, in fetch_data
    frames_hash = hashlib.md5(str(fd.getvalue()).encode('utf-8'))
  File "//anaconda/lib/python2.7/StringIO.py", line 269, in getvalue
    _complain_ifclosed(self.closed)
  File "//anaconda/lib/python2.7/StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"
ValueError: I/O operation on closed file`
