### ISSUE TITLE
travis failures on master

### ISSUE THREAD

**Issue by dalejung** [quantopian/zipline#506]
```
======================================================================
ERROR: Failure: SSLError ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/dalejung/zipline/tests/risk/test_risk_cumulative.py", line 26, in <module>
    from . import answer_key
  File "/home/travis/build/dalejung/zipline/tests/risk/answer_key.py", line 116, in <module>
    ensure_latest_answer_key()
  File "/home/travis/build/dalejung/zipline/tests/risk/answer_key.py", line 111, in ensure_latest_answer_key
    ANSWER_KEY_DL_TEMPLATE.format(md5=answer_key_dl_checksum))
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/requests/api.py", line 65, in get
    return request('get', url, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Happening since last night. Not sure what the deal is.

**Comment by twiecki** [comment]
@ehebert set the excel spreadsheet up.

**Comment by twiecki** [comment]
From anaconda: `requests 2.5.3 is available. this should fix the SSL problems some people have been seeing with conda. Use "conda update requests" #conda﻿`

**Comment by dalejung** [comment]
yap, started working late yesterday.

**Comment by ehebert** [comment]
Looks like it sorted itself out, but if it 'blips' again we should consider upgrading requests?

**Comment by twiecki** [comment]
That should automatically be updated along with miniconda, I think that's how this resolved itself.

**Comment by ehebert** [comment]
Ah right, because conda doesn't use the same pegged versions as in requirements.txt. Got it.
