### ISSUE TITLE
Cannot run the "manual (advanced)" example from the zipline beginner tutorial.

### ISSUE THREAD

**Issue by mayouf** [quantopian/zipline#543]
Hi everyone,

I am following the zipline  beginner tutorial.

I took the "manual (advanced)" example from http://www.zipline.io/tutorial/. As my purpose is to use zipline to backtest with my own data.

I got an error that I don't know why it comes. Below is the error message and the source code of the example . Anyone knows the reason ??

>>> perf_manual = algo_obj.run(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\algorithm.py", line 423, in run
    for perf in self.gen:
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\gens\tradesimulation.py", line 127, in transform
    self.algo.instant_fill,
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\gens\tradesimulation.py", line 214, in _process_snapshot
    new_orders = self._call_handle_data()
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\gens\tradesimulation.py", line 236, in _call_handle_data
    self.algo.handle_data(self.current_data)
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\algorithm.py", line 226, in handle_data
    self._handle_data(self, data)
  File "<stdin>", line 2, in handle_data
NameError: global name 'order' is not defined
>>> from zipline.algorithm import TradingAlgorithm
>>> from zipline.utils.factory import load_bars_from_yahoo
>>> perf_manual = algo_obj.run(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\algorithm.py", line 423, in run
    for perf in self.gen:
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\gens\tradesimulation.py", line 127, in transform
    self.algo.instant_fill,
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\gens\tradesimulation.py", line 214, in _process_snapshot
    new_orders = self._call_handle_data()
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\gens\tradesimulation.py", line 236, in _call_handle_data
    self.algo.handle_data(self.current_data)
  File "C:\Users\mickael\Anaconda\lib\site-packages\zipline\algorithm.py", line 226, in handle_data
    self._handle_data(self, data)
  File "<stdin>", line 2, in handle_data
NameError: global name 'order' is not defined
>>> 

# --------------------------------------------------------------

import pytz
from datetime import datetime

from zipline.algorithm import TradingAlgorithm
from zipline.utils.factory import load_bars_from_yahoo

# Load data manually from Yahoo! finance
start = datetime(2000, 1, 1, 0, 0, 0, 0, pytz.utc)
end = datetime(2012, 1, 1, 0, 0, 0, 0, pytz.utc)
data = load_bars_from_yahoo(stocks=['AAPL'], start=start,
                            end=end)

# Define algorithm
def initialize(context):
    pass

def handle_data(context, data):
    order(symbol('AAPL'), 10)
    record(AAPL=data[symbol('AAPL')].price)

# Create algorithm object passing in initialize and
# handle_data functions
algo_obj = TradingAlgorithm(initialize=initialize, 
                            handle_data=handle_data)

# Run algorithm
perf_manual = algo_obj.run(data)

[2014-07-25 17:12] INFO: Performance: Simulated 3019 trading days out of 3019.
[2014-07-25 17:12] INFO: Performance: first open: 2000-01-03 14:31:00+00:00
[2014-07-25 17:12] INFO: Performance: last close: 2011-12-30 21:00:00+00:00

AAPL

**Comment by mayouf** [comment]
I found the solution. I was in the  DOC: Fix tutorial import. Closes #430.

Though, I will comment the correction because it is not clearly visible is the #430.

I simply just had to add these two lines at the beginning of the script:

import zipline
from zipline.api import order, record, symbol


So I suggest the http://www.zipline.io/tutorial/ to do this tiny correction.

cheers,

mayouf
