### ISSUE TITLE
Blaze Datasource

### ISSUE THREAD

**Issue by femtotrader** [quantopian/zipline#659]
Hello,

it may be a nice idea to add Blaze as a possible Data source

http://blaze.pydata.org/en/latest/
http://blaze.pydata.org/en/latest/rosetta-pandas.html

Blaze could allow to run backtests without having to store in memory the whole
historical data at startup.

Moreover with a database / table URI, it will allow to easily connect to several database
(thanks to SQLAlchemy)

Blaze comes with a nice tool called odo to output data in many format (SQL database, CSV, JSON...) https://odo.readthedocs.org/

Here is a sample to iterate over rows of any database supported by SQLAlchemy

    import blaze as bz
    from blaze import odo, chunks
    chunksize = 10000
    table_uri = 'dialect+driver://user:password@host:port/database::table'
    dat = bz.Data(table_uri)
    #dat = dat.sort(['Timestamp'])
    if size > 0:
        dat = dat[:size]

    for i, chunk in enumerate(odo(dat, chunks(pd.DataFrame), chunksize=chunksize)):
        print("="*5 + " chunk %d " % (i + 1) + "="*5)
        for j, row in chunk.iterrows():
            print(row)

with `odo(..., chunks(pd.DataFrame))` there is only one chunk (DataFrame) in memory at a time.

Blaze also supports CSV files

Kind regards

**Comment by twiecki** [comment]
I thought about this as well and think it's a great idea.

**Comment by femtotrader** [comment]
One problem could be aligning data for several symbols.

Try first to feed a database with 4 symbols

    #!/usr/bin/env python

    import datetime
    import pytz
    import pandas as pd
    from pandas_datareader import data, wb

    import traceback
    import warnings

    import blaze as bz
    from blaze import odo

    tzinfo = pytz.UTC
    dt_start = datetime.datetime(2011, 1, 1, tzinfo=tzinfo)
    dt_stop = datetime.datetime(2015, 1, 1, tzinfo=tzinfo)
    symbols = ['GOOG', 'AAPL', 'IBM', 'ORCL']
    panel = data.DataReader(symbols, 'yahoo', dt_start, dt_stop)
    db = "symbols_OHLCV_1D"
    db_uri = 'dialect+driver://user:password@host:port/{db}'.format(db=db)
    #odo(panel, db_uri) # see https://github.com/ContinuumIO/odo/issues/268

    symbol = 'AAPL'
    symbol = 'GOOG' # NaN
    for symbol in symbols:
        df = panel.loc[:,:,symbol]
        df = df.reset_index()
        table_uri = 'dialect+driver://user:password@host:port/{db}::{table}'.format(db=db, table=symbol)
        try:
            odo(df, table_uri)
        except:
            warnings.warn(traceback.format_exc())

or for just one symbol

    #!/usr/bin/env python

    import datetime
    import pytz
    import pandas as pd
    from pandas_datareader import data, wb

    import blaze as bz
    from blaze import odo

    tzinfo = pytz.UTC
    dt_start = datetime.datetime(2011, 1, 1, tzinfo=tzinfo)
    dt_stop = datetime.datetime(2015, 1, 1, tzinfo=tzinfo)
    symbol = "GOOG"
    df = data.DataReader(symbol, 'yahoo', dt_start, dt_stop)
    df = df.reset_index()
    table_uri = 'dialect+driver://user:password@host:port/symbols_OHLCV_1D::%s' % symbol
    odo(df, table_uri)

GOOG first data are for 2014-03-27
but for others it's 2011-01-03

Pandas Panel is able to manage data alignement.

**Comment by llllllllll** [comment]
@femtotrader In your first example, I am not sure where you get any benefit out of using blaze vs just using odo. You create an interactive symbol but immediately pass it to odo to materialize into dataframes. You could just pass the resource directly to odo. Also, I would suggest importing odo from the canonical path `from odo import odo`.

I could see value in maybe making `data` in the algo a symbol that allows users to express their computations lazily and then executing that against whatever data backend they have..

**Comment by femtotrader** [comment]
Because I'm doing this just to save (sample) data to a database... we will use Blaze to retrieve data from database to expose then to zipline. That's the job of making a "Blaze datasource" that I'm exposing here.

**Comment by llllllllll** [comment]
err, the issue is that you are not using blaze to retrieve the data from the database, you are using odo for that.

you could do the same thing with just:

```python
table_uri = 'dialect+driver://user:password@host:port/database::table'
for i, chunk in enumerate(odo(table_uri, chunks(pd.DataFrame), chunksize=chunksize)):
    print("="*5 + " chunk %d " % (i + 1) + "="*5)
    for j, row in chunk.iterrows():
```

There is no need to wrap the resource in an `InteractiveSymbol`
        print(row)

**Comment by femtotrader** [comment]
I wonder how you can align data with several symbols because one dataframe is for one symbol.

**Comment by llllllllll** [comment]
> because the dataframe is for one symbol

I have frequently worked with data that has symbol as another column in the table/dataframe. You can then self join to align the data.

**Comment by femtotrader** [comment]
so you will join chunks ?

**Comment by llllllllll** [comment]
If you wanted to do things like joining, then blaze would be your friend here. You could do something like:

```python
import blaze as bz
from odo import odo, resource, chunks

table = resource('...')
s = bz.symbol('s', discover(table))
for chunk in odo(bz.compute(bz.join(s, s, 'knowledge_date'), table), chunks(pd.DataFrame)):
    ...
```

I didn't exec this so it might have slight errors but hopefully you get the idea.

**Comment by femtotrader** [comment]
So you are using Blaze (not only odo) ;-)

Here is how database for OHLCV daily looks like
![Database](https://cloud.githubusercontent.com/assets/5049737/8892880/42964738-3374-11e5-8a82-babad34bcccd.png)

Here is AAPL first rows
![AAPL](https://cloud.githubusercontent.com/assets/5049737/8892881/45d14402-3374-11e5-9bb3-1a6a980049b4.png)

Here is GOOG first rows
![GOOG](https://cloud.githubusercontent.com/assets/5049737/8892882/4a42d1f4-3374-11e5-94c8-bfaacdc5f963.png)

Here is IBM first rows
![IBM](https://cloud.githubusercontent.com/assets/5049737/8892894/f1b4cf78-3374-11e5-9604-6e18f387fa7b.png)

Here is ORCL first rows
![ORCL](https://cloud.githubusercontent.com/assets/5049737/8892891/c51349fe-3374-11e5-9a7a-9a22bc939ff5.png)

To my understanding we should have chunks of Panel with aligned Open, High, Low, Close prices.

**Comment by llllllllll** [comment]
let `ts` be a dictionary mapping symbol to the table with data.
You could at least join this all up into a single table with a concat:

```
import blaze as bz
from toolz import valmap

def reduction(a, b):
    return bz.concat(
        bz.transform(a[1], ticker=a[0]),
        bz.transform(b[1], ticker=b[0]),
    )

unioned = reduce(reduction, valmap(bz.Data, ts).items())
```

Note: I think transform can take a scalar to broadcast as a column but I am not sure.

**Comment by llllllllll** [comment]
Right now, blaze and odo don't really support working with panels. It is most common to work with expressions representing tables, matrices, and arrays.

**Comment by femtotrader** [comment]
I did like you suggest

    #!/usr/bin/env python

    import blaze as bz
    from toolz import valmap, reduce

    def reduction(a, b):
        return bz.concat(
            bz.transform(a[1], ticker=a[0]),
            bz.transform(b[1], ticker=b[0]),
        )

    def table_uri(symbol, period):
        return 'dialect+driver://user:password@host:port/symbols_OHLCV_%s::%s' % (period, symbol)

    symbols = ['AAPL', 'GOOG', 'IBM', 'ORCL']
    ts = {symbol: bz.Data(table_uri(symbol, '1D')) for symbol in symbols}
    unioned = reduce(reduction, valmap(bz.Data, ts).items())

but

    $ python datasource_blaze.py
    Traceback (most recent call last):
      File "datasource_blaze.py", line 18, in <module>
        unioned = reduce(reduction, valmap(bz.Data, ts).items())
      File "datasource_blaze.py", line 8, in reduction
        bz.transform(a[1], ticker=a[0]),
      File "//anaconda/lib/python3.4/site-packages/blaze/expr/collections.py", line 235, in transform
        args = [t] + [v.label(k) for k, v in sorted(kwargs.items(), key=first)]
      File "//anaconda/lib/python3.4/site-packages/blaze/expr/collections.py", line 235, in <listcomp>
        args = [t] + [v.label(k) for k, v in sorted(kwargs.items(), key=first)]
    AttributeError: 'str' object has no attribute 'label'

Any idea ?

**Comment by llllllllll** [comment]
It looks like transform doesn't work with expressions that don't share subexpressions with `t`. Not really sure what the best way to express this kind of transformation in blaze is; however, I would look to restructure the underlying database by merging the tables into a single table with a `symbol` column.

**Comment by llllllllll** [comment]
Zipline has an optional dependency on blaze for use in Pipeline. Zipline can convert simple blaze expressions into a pipeline dataset. See zipline/pipeline/data/loaders/blaze/core.py for more info.
