### ISSUE TITLE
Tutorial example fails when run with TradingAlgorithm 

### ISSUE THREAD

**Issue by leftychen** [quantopian/zipline#755]
I followed the tutorial example run with TradingAlgorithm but got an error:

Traceback (most recent call last):
  File "/Users/Jasonchen/Desktop/Python/ziplinetest/main.py", line 43, in <module>
    handle_data=handle_data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/algorithm.py", line 158, in __init__
    capital_base=self.capital_base
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/utils/factory.py", line 65, in create_simulation_parameters
    emission_rate=emission_rate,
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/finance/trading.py", line 365, in __init__
    self._update_internal()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/finance/trading.py", line 369, in _update_internal
    environment = TradingEnvironment.instance()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/finance/trading.py", line 83, in instance
    environment = TradingEnvironment()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/finance/trading.py", line 101, in __init__
    load(self.bm_symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/data/loader.py", line 184, in load_market_data
    benchmark_returns = update_benchmarks(bm_symbol, last_bm_date)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/data/loader.py", line 141, in update_benchmarks
    for daily_return in get_benchmark_returns(symbol, start_date=start):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/data/benchmarks.py", line 120, in get_benchmark_returns
    data_points = list(get_benchmark_data(symbol, start_date, end_date))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/data/benchmarks.py", line 103, in get_benchmark_data
    raw_benchmark_data = get_raw_benchmark_data(start_date, end_date, symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zipline/data/benchmarks.py", line 81, in get_raw_benchmark_data
    params=params, stream=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/sessions.py", line 374, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/adapters.py", line 174, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 417, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 232, in _get_conn
    return conn or self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 199, in _new_conn
    strict=self.strict)
TypeError: __init__() got an unexpected keyword argument 'strict'

someone could tell me how to fix it?

**Comment by jfkirk** [comment]
@leftychen Could you update your Zipline, install the requirements (some may have changed) and let us know if this is still an issue? If so, we will investigate.

There have been some recent changes to the Benchmarks system that may have resolved your issue.

**Comment by richafrank** [comment]
Let us know if there's something for us to do here!  Closing in the meantime.
