### ISSUE TITLE
OSX Cannot convert 'Py_ssize_t [8]' to Python object

### ISSUE THREAD

**Issue by npezolano** [quantopian/zipline#844]
Using the latest zipline, I get the following error after running `python setup.py build_ext --inplace` or `python setup.py install`

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing 'v0.8.3+44.gabbda17' to '0.8.3+44.gabbda17'
  normalized_version,
running build_ext
Compiling zipline/lib/adjusted_array.pyx because it changed.
Compiling zipline/lib/adjustment.pyx because it changed.
Compiling zipline/lib/rank.pyx because it changed.
Cythonizing zipline/lib/adjusted_array.pyx

Error compiling Cython file:
------------------------------------------------------------

                  uint8_t[:, :] mask,  # None is equivalent to all 0s.
                  dict adjustments):
        cdef Py_ssize_t row, col

        if mask is not NOMASK:
            if not PyObject_RichCompare(mask.shape, data.shape, Py_EQ):
                                     ^
------------------------------------------------------------

zipline/lib/adjusted_array.pyx:115:44: Cannot convert 'Py_ssize_t [8]' to Python object

Error compiling Cython file:
------------------------------------------------------------

                  uint8_t[:, :] mask,  # None is equivalent to all 0s.
                  dict adjustments):
        cdef Py_ssize_t row, col

        if mask is not NOMASK:
            if not PyObject_RichCompare(mask.shape, data.shape, Py_EQ):
                                                       ^
------------------------------------------------------------

zipline/lib/adjusted_array.pyx:115:56: Cannot convert 'Py_ssize_t [8]' to Python object
Traceback (most recent call last):
  File "setup.py", line 250, in <module>
    url="http://zipline.io",
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 97, in finalize_options
    self.check_extensions_list(self.extensions)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 353, in check_extensions_list
    for i, ext in enumerate(extensions):
  File "setup.py", line 55, in __iter__
    self.lazy_cythonize()
  File "setup.py", line 50, in lazy_cythonize
    for ext_args in self
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython-0.22.1-py2.7-macosx-10.10-x86_64.egg/Cython/Build/Dependencies.py", line 785, in cythonize
    cythonize_one(*args[1:])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Cython-0.22.1-py2.7-macosx-10.10-x86_64.egg/Cython/Build/Dependencies.py", line 902, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: zipline/lib/adjusted_array.pyx
```

**Comment by llllllllll** [comment]
Sorry about trouble. What version of cython are you using? ping @richafrank, could you try to repro on the particular commit?

Are you using conda or virtualenv?

**Comment by npezolano** [comment]
Cython-0.22.1 and python 2.7

**Comment by llllllllll** [comment]
Hmm, I am not sure what might be causing this. I would highly recommend trying to install zipline in a virtual environment even though I am not sure that this is related. I will try to repro when I have access to an OSX machine.

**Comment by richafrank** [comment]
@llllllllll On OSX Yosemite, I made a new Python 2.7.10 virtualenv and pip installed etc/requirements.txt.  Running `python setup.py build_ext --inplace` in the root of the zipline git repo ([this commit] (https://github.com/quantopian/zipline/commit/abbda17239d715e33064844c130061b0dac8be5d)), I saw a bunch of warnings, but no errors:
```
...
clang -bundle -undefined dynamic_lookup -L/usr/local/opt/tcl-tk/lib build/temp.macosx-10.10-x86_64-2.7/zipline/data/_adjustments.o -o build/lib.macosx-10.10-x86_64-2.7/zipline/data/_adjustments.so
copying build/lib.macosx-10.10-x86_64-2.7/zipline/assets/_assets.so -> zipline/assets
copying build/lib.macosx-10.10-x86_64-2.7/zipline/lib/adjusted_array.so -> zipline/lib
copying build/lib.macosx-10.10-x86_64-2.7/zipline/lib/adjustment.so -> zipline/lib
copying build/lib.macosx-10.10-x86_64-2.7/zipline/lib/rank.so -> zipline/lib
copying build/lib.macosx-10.10-x86_64-2.7/zipline/data/_equities.so -> zipline/data
copying build/lib.macosx-10.10-x86_64-2.7/zipline/data/_adjustments.so -> zipline/data
```

`python setup.py install` also worked for me:
```
...
Finished processing dependencies for zipline==0.8.3+44.gabbda17
```
After those steps, I end up with the following in my virtualenv:
```
bcolz==0.10.0
Bottleneck==1.0.0
click==4.0
contextlib2==0.4.0
cyordereddict==0.2.2
Cython==0.22.1
decorator==4.0.4
Logbook==0.10.0
networkx==1.9.1
numexpr==2.4.3
numpy==1.9.2
pandas==0.16.1
patsy==0.4.0
python-dateutil==2.4.2
pytz==2015.4
requests==2.7.0
scipy==0.15.1
six==1.9.0
SQLAlchemy==1.0.8
statsmodels==0.6.1
toolz==0.7.4
wheel==0.24.0
zipline==0.8.3+44.gabbda17
```

**Comment by npezolano** [comment]
Thanks, For anyone else who runs into this remove anything mac ports and use anaconda or brew for python post OSX 10.11

**Comment by richafrank** [comment]
Oh, interesting - Thanks for sharing the solution!
