### ISSUE TITLE
test_lse_calendar_vs_environment fails when cached yahoo data is more than a day old

### ISSUE THREAD

**Issue by jikamens** [quantopian/zipline#93]
Run at 23:22 US/Eastern:

```
FAIL: test_lse_calendar_vs_environment (tests.test_tradingcalendar.TestTradingCalendar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jik/repo/zipline/tests/test_tradingcalendar.py", line 56, in test_lse_calendar_vs_environment
self.check_days(env_days, cal_days)
  File "/home/jik/repo/zipline/tests/test_tradingcalendar.py", line 63, in check_days
"{diff} should be empty".format(diff=diff)
AssertionError: <class 'pandas.tseries.index.DatetimeIndex'>
[2013-02-19 00:00:00]
Length: 1, Freq: None, Timezone: UTC should be empty
'1 != 0' = '%s != %s' % (safe_repr(1), safe_repr(0))
"<class 'pandas.tseries.index.DatetimeIndex'>\n[2013-02-19 00:00:00]\nLength: 1, Freq: None, Timezone: UTC should be empty" = self._formatMessage("<class 'pandas.tseries.index.DatetimeIndex'>\n[2013-02-19 00:00:00]\nLength: 1, Freq: None, Timezone: UTC should be empty", '1 != 0')
>>  raise self.failureException("<class 'pandas.tseries.index.DatetimeIndex'>\n[2013-02-19 00:00:00]\nLength: 1, Freq: None, Timezone: UTC should be empty")
```

**Comment by dmichalowicz** [comment]
Calendars are now in https://github.com/quantopian/trading_calendars
