### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nanmean' when importing zipline

### ISSUE THREAD

**Issue by markusschaller** [quantopian/zipline#967]
After setting up a new virtualenv and installing zipline with "pip install zipline" I opened a python shell and did an "import zipline" resulting in the following exception:
```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/Devel/zipenv/lib/python3.4/site-packages/zipline/__init__.py", line 26, in <module>
    from . import finance
  File "/home/dev/Devel/zipenv/lib/python3.4/site-packages/zipline/finance/__init__.py", line 16, in <module>
    from . import execution, trading
  File "/home/dev/Devel/zipenv/lib/python3.4/site-packages/zipline/finance/execution.py", line 22, in <module>
    import zipline.utils.math_utils as zp_math
  File "/home/dev/Devel/zipenv/lib/python3.4/site-packages/zipline/utils/math_utils.py", line 26, in <module>
    nanmean = bn.nanmean
AttributeError: 'module' object has no attribute 'nanmean'
```

**Comment by richafrank** [comment]
Hi @markusschaller, what do you have for `zipline.__version__` and `bottleneck.__version__`?

**Comment by markusschaller** [comment]
Here's the complete pip freeze output: 

```
bcolz==0.10.0                                                                                                                                                                                                                                
Bottleneck==1.0.0                                                                                                                                                                                                                            
click==4.0                                                                                                                                                                                                                                   
contextlib2==0.4.0                                                                                                                                                                                                                           
cyordereddict==0.2.2                                                                                                                                                                                                                         
Cython==0.22.1                                                                                                                                                                                                                               
decorator==4.0.6                                                                                                                                                                                                                             
Logbook==0.10.0                                                                                                                                                                                                                              
networkx==1.9.1                                                                                                                                                                                                                              
numexpr==2.4.3                                                                                                                                                                                                                               
numpy==1.9.2                                                                                                                                                                                                                                 
pandas==0.16.1                                                                                                                                                                                                                               
patsy==0.4.0                                                                                                                                                                                                                                 
python-dateutil==2.4.2                                                                                                                                                                                                                       
pytz==2015.4                                                                                                                                                                                                                                 
requests==2.7.0
scipy==0.15.1
six==1.9.0
SQLAlchemy==1.0.8
statsmodels==0.6.1
toolz==0.7.4
wheel==0.24.0
zipline==0.8.3
```

**Comment by richafrank** [comment]
Interesting.  Are you able to do yourself what zipline tries to do?
```python
import bottleneck as bn
nanmean = bn.nanmean
```

**Comment by markusschaller** [comment]
That is already unsuccessful:
```
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bottleneck as bn
>>> nanmean = bn.nanmean
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'nanmean'
```
Very strange: I set up zipline in an Virtualenv on an virtual VM on my private computer, and everything worked fine, no attribute errors.  Both Linux VMs are Ubuntu 14.04.3 LTS (Lubuntu at home and Kubuntu at work). But apparently, there are differences in both setups ...

**Comment by richafrank** [comment]
Hmm, you could try reinstalling bottleneck.  You could also uninstall it entirely, as zipline uses it for an optional performance boost over the numpy versions.

**Comment by markusschaller** [comment]
If bottleneck is optional, shouldn't there be a try...except around the bottleneck import statement [here](../blob/e576231ae5a90e0c2d5457ef3ed335f928a160c4/zipline/pipeline/factors/technical.py) ?. Doing this and uninstalling bottleneck then lead to a successful zipline import :-)

**Comment by richafrank** [comment]
Yes, I agree - looks like it should import from [math_utils] (https://github.com/quantopian/zipline/blob/ef4f642e62a5d33699c87d44883428b63a7d0559/zipline/utils/math_utils.py#L33), which already has the try-except.

cc @ssanderson regarding https://github.com/quantopian/zipline/blob/e576231ae5a90e0c2d5457ef3ed335f928a160c4/zipline/pipeline/factors/technical.py

**Comment by richafrank** [comment]
The optionality of bottleneck in math_utils should be fixed by https://github.com/quantopian/zipline/commit/69cc5e65649ae91b1fd8e338c1e5f91a9c6f8e94.  Going to close this, but let us know if there's something else to be done.
